content/start/dark-mode/index-en-US.md

Fixes # correct MacOs to the official brand name macOS. `zh-cn` version of the doc is checked and everything seems to be alright.
🇨🇳 Chinese
- 修复文档错字 MacOs --> macOS
---
🇺🇸 English
- Fix typo brand name of macOS

fix: typo of macOS

---

packages/semi-foundation/anchor/anchor.scss
packages/semi-foundation/anchor/variables.scss
packages/semi-foundation/checkbox/checkboxFoundation.ts

[中文模板 / Chinese Template](./PULL_REQUEST_TEMPLATE.zh-CN.md)
Fixes typo

fix: radius and group typo

---

content/input/slider/index-en-US.md

Fixes #
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

docs(slider): Update slider docs

---

packages/semi-animation-react/src/Transition.tsx
packages/semi-ui/collapsible/index.tsx

fix: 修复collapsible组件默认打开时，组件高度没有完全展开问题

---

packages/semi-ui/navigation/Header.tsx

Fixes #
🇨🇳 Chinese
- 修复  NavItemProps linkOptions type
---
🇺🇸 English
- Fix ...

fix: linkOptions type definition

---

CONTRIBUTING-en-US.md

Fixes #
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

fix(docs)：docsite-spelling

---

packages/semi-ui/input/textarea.tsx

Fixes TextArea TextAreaProps ref TypeScript definition bug
🇨🇳 Chinese
- 修复 TextArea TextAreaProps 类型定义问题
---
🇺🇸 English
- Fix TypeScript bug of TextArea TextAreaProps

fix(textarea): TextAreaProps ts definition bug

---

content/input/radio/index-en-US.md
content/input/radio/index.md
content/start/changelog/index-en-US.md
content/start/changelog/index.md
content/start/update-to-v2/index-en-US.md
content/start/update-to-v2/index.md
packages/semi-ui/button/index.tsx
packages/semi-ui/iconButton/index.tsx
packages/semi-ui/radio/context.ts
packages/semi-ui/radio/radio.tsx
packages/semi-ui/radio/radioGroup.tsx

Fixes #
🇨🇳 Chinese
- 修复 Radio 和 Button 类型定义的一些问题
---
🇺🇸 English
- Fix some problems with Radio and Button type definition

Fix components ts

---

packages/semi-foundation/README.md

Fixes #
🇨🇳 Chinese
- 修复 ...
semi-foundation/README.md 语法
---
🇺🇸 English
- Fix ...
semi-foundation/README.md  gammar

fix: semi-foundation/README.md gammar optimize

---

packages/semi-ui/select/_story/select.stories.tsx
packages/semi-ui/select/index.tsx

Fixed `Select` component `renderSelectedItems` typescript bug (need carefully review)
🇨🇳 Chinese
- 修复 Select 组件 renderSelectedItems 类型定义问题
---
🇺🇸 English
- Fixed `Select` component `renderSelectedItems` typescript bug

fix(select): renderSelectedItems ts bug

---

src/components/Footer/index.jsx

在点击官网底部第三方连接的时候，会在当前页面跳转，打开一个新窗口会更友好一点

docs: 文档底部链接使用新窗口打开方式

---

content/show/table/index-en-US.md
content/show/table/index.md

Table component adds a zebra pattern table demo

docs(table): add zebra stripped demo

---

packages/semi-foundation/toast/toastFoundation.ts
packages/semi-ui/toast/index.tsx

Fixes #166
🇨🇳 Chinese
- 修复 Toast 的类型定义
---
🇺🇸 English
- Fix TypeScript definition of Toast

fix(toast): update TypeScript definition of Toast

---

packages/semi-ui/list/index.tsx

Fixes List typescript definition bug
🇨🇳 Chinese
- 修复 List 类型定义错误问题
---
🇺🇸 English
- Fix List typescript definition bug

fix(list): List ts definition bug

---

packages/semi-ui/transfer/index.tsx

Fixes #
🇨🇳 Chinese
- 修复Transfer在treeList类型下搜索物料问题
---
🇺🇸 English
- Fix the problem that Transfer searches for materials under treeList type

fix(transfer): treeList search not effect #163

---

packages/semi-ui/anchor/__test__/anchor.test.js

Fixes #
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

test(anchor): Update anchor component test

---

packages/semi-foundation/utils/Event.ts

Fixed Tooltip event callback was not remove correctly
🇨🇳 Chinese
- 修复 Tooltip 事件回调没有正确移除问题
---
🇺🇸 English
- Fixed Tooltip event callback was not remove correctly

fix(tooltip): event callback was not remove correctly

---

content/start/getting-started/index-en-US.md
content/start/getting-started/index.md

docs:with pnpm

---

packages/semi-foundation/rating/foundation.ts
packages/semi-ui/rating/__test__/rating.test.js

Fixes [#103 ](https://github.com/DouyinFE/semi-design/issues/103)
🇨🇳 Chinese
- 修复 rating重复点击没有更新
---
🇺🇸 English
- Fix rating repeated click is not updated

fix: rating repeated click is not update (#103)

---

packages/semi-ui/locale/source/ja_JP.ts

Fixes #
🇨🇳 Chinese
-  更改日语翻译文件
- jumpTo -> ページへ
- selectDate -> 日付を選ぶ  
-------
🇺🇸 English
- change jaJP locale file translate
- jumpTo -> ページへ
- selectDate -> 日付を選ぶ
-------
🇯🇵 Japaness  
- 日本語翻訳変更
- jumpTo -> ページへ
- selectDate -> 日付を選ぶ

feat: change jumpTo & selectDate ja_JP text

---

packages/semi-ui/form/arrayField.tsx

Fixes # ArrayField children props type Definition
🇨🇳 Chinese
- 修复 ...
ArrayField children props  类型定义
---
🇺🇸 English
- Fix ...

fix: arrayField children props types

---

content/navigation/tabs/index.md
packages/semi-foundation/tabs/foundation.ts
packages/semi-foundation/tabs/tabs.scss
packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tabs/__test__/tabs.test.js
packages/semi-ui/tabs/_story/tabs.stories.js
packages/semi-ui/tabs/index.tsx
packages/semi-ui/tabs/interface.ts

-  Tabs add `closable` attribute：
```ts
<Tabs closable type="card" defaultActiveKey="1">
<TabPane tab="文档" itemKey="1">
文档
</TabPane>
<TabPane tab="快速起步" itemKey="2">
快速起步
</TabPane>
<TabPane tab="帮助" itemKey="3">
帮助
</TabPane>
</Tabs>
```
When the tab close icon is clicked, the current tab will be deleted.
🇨🇳 Chinese
- Tabs增加closable属性：
```ts
<Tabs closable type="card" defaultActiveKey="1">
<TabPane tab="文档" itemKey="1">
文档
</TabPane>
<TabPane tab="快速起步" itemKey="2">
快速起步
</TabPane>
<TabPane tab="帮助" itemKey="3">
帮助
</TabPane>
</Tabs>
```
当点击tab的关闭图标时，会将当前tab删除。
---
🇺🇸 English
-  Tabs add `closable` attribute：
```ts
<Tabs closable type="card" defaultActiveKey="1">
<TabPane …
```

feat(tabs): tabs add closable  function

---

CONTRIBUTING-en-US.md

fix CONTRIBUTING markdown format.
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

chore: remove unnecessary space

---

package.json
src/components/side-nav.js
src/sitePages/newHome/components/comments/comments.jsx

docs(SideNav): use `a` tag for navigation

---

packages/semi-foundation/table/foundation.ts
packages/semi-ui/table/Table.tsx

Fixed Table resizable bug 
🇨🇳 Chinese
- 修复 Table resizable 表格问题 #154
---
🇺🇸 English
- Fixed Table resizable bug #154

fix(table): resizable bug

---

packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.js
packages/semi-ui/select/index.tsx

Fixes #
🇨🇳 Chinese
- Select 支持打开下拉框后，可以自动滚动到已选中的项目
---
🇺🇸 English
- Select supports to open the drop-down box, you can automatically scroll to the selected item

feat: [Select] support scroll into view #169

---

packages/semi-icons/package.json

Fixes #
🇨🇳 Chinese
- 修复semi-icons依赖缺少classnames问题
---
🇺🇸 English
- Fix semi-icons dependencies missing classnames problem
#231

fix: semi-icons add dependencies classnames #231

---

packages/semi-foundation/table/foundation.ts
packages/semi-ui/table/ColumnFilter.tsx
packages/semi-ui/table/Table.tsx

fix(table): resolve some ts error

---

packages/semi-foundation/input/input.scss
packages/semi-foundation/input/variables.scss

Fixed Input border hover color is not correct
🇨🇳 Chinese
- 修复 Input hover 态边框 CSS 属性不正确问题
---
🇺🇸 English
- Fixed Input border hover color is not correct

style(input): border hover color is not correct

---

packages/semi-foundation/table/table.scss
packages/semi-ui/table/_story/FixAllColumnsWithoutWidth.tsx
packages/semi-ui/table/_story/table.stories.js
packages/semi-ui/table/_story/table.stories.tsx

Fixed Table align bug when all columns do not have width
- before
- after
🇨🇳 Chinese
- 修复 Table 组件所有列都没有设置列宽时，表格无法对齐问题
---
🇺🇸 English
- Fixed Table align bug when all columns do not have width

fix(table): resolve align bug when all columns do not have width

---

content/feedback/spin/index-en-US.md
content/feedback/spin/index.md
packages/semi-ui/spin/index.tsx

Fixes #
🇨🇳 Chinese
- 修复Spin API ts 文档
---
🇺🇸 English
- Fix Spin API ts description

docs: fix Spin API ts description

---

content/input/taginput/index-en-US.md
content/input/taginput/index.md
packages/semi-foundation/tagInput/foundation.ts
packages/semi-ui/tagInput/__test__/tagInput.test.js
packages/semi-ui/tagInput/_story/tagInput.stories.js
packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- TagInput 新增 onKeyDown
---
🇺🇸 English
- TagInput supports onKeyDown

feat: [TagInput] support onKeyDown #255

---

packages/semi-icons/README.md
packages/semi-illustrations/README.md

Fixes #
🇨🇳 Chinese
---
🇺🇸 English

chore(readme): adjust readme

---

packages/semi-ui/cascader/index.tsx

Fixes #
🇨🇳 Chinese
- Cascader 从 semi-ui 导出 CascaderType 和 ShowNextType
---
🇺🇸 English
- Cascader exports CascaderType and ShowNextType from semi-ui

chore: [Cascader] export CascaderType and ShowNextType ts

---

packages/semi-foundation/datePicker/foundation.ts

Fixed DatePicker compatiableParse function ts error

fix(datepicker): compatiableParse function ts error close#274

---

packages/semi-foundation/select/option.scss
packages/semi-foundation/select/select.scss

Fixes #
🇨🇳 Chinese
- 修复 ...
fix: fix select not import option scss
---
🇺🇸 English
- Fix ...
fix: fix select not import option scss

fix: fix select not import option scss

---

content/navigation/tabs/index-en-US.md
content/navigation/tabs/index.md
packages/semi-foundation/tabs/foundation.ts
packages/semi-foundation/tabs/tabs.scss
packages/semi-ui/datePicker/yearAndMonth.tsx
packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tabs/TabPane.tsx
packages/semi-ui/tabs/__test__/tabs.test.js
packages/semi-ui/tabs/index.tsx
packages/semi-ui/tabs/interface.ts
packages/semi-ui/tooltip/index.tsx

Feat tabs closable and on tab close
Fixes #
🇨🇳 Chinese
- 修复 ...
1.  close icon hover 样式调整为 color text-1
2. 删除了 close icon margin right 8px
3. 去除了 interface import
3. 移动 closable api 从 tab 到了 tabPlane 上
4. 新增 onTabClose Api 
5. 优化部分函数命名
---
🇺🇸 English
- Fix ...

Feat tabs closable and on tab close

---

packages/semi-ui/table/interface.ts

Table ts interface `Pagination` rename to `TablePagination` to avoid conflict with Pagination component

fix(table): Pagination rename to TablePagination

---

packages/semi-foundation/tree/foundation.ts
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/tree/interface.ts

Fixes #
🇨🇳 Chinese
- 将 Tree 的 interface ExpanedOtherProps 修正为 ExpandedOtherProps
---
🇺🇸 English
- Modify Tree's interface ExpanedOtherProps to ExpandedOtherProps

chore: [Tree] modify ExpanedOtherProps to ExpandedOtherProps #297

---

packages/semi-ui/gulpfile.js

Fix the problem in the compile stage. Need to deal with the format of `export from`
Fixes #
🇨🇳 Chinese
- 修复在compilelib阶段的问题。需要处理 export from 这类格式的模块化
---
🇺🇸 English
- Fix the problem in the compile stage. Need to deal with the format of `export from`

fix: Fix bugs in the compile stage

---

packages/semi-ui/navigation/index.tsx
packages/semi-ui/toast/index.tsx

Fixes #
🇨🇳 Chinese
- 修复Motion interface引入路径不正确的问题（Toast、Navigation）
---
🇺🇸 English
- Fix ...

fix: Motion interface import pathwrong

---

packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.js
packages/semi-ui/select/index.tsx
packages/semi-ui/select/utils.tsx

Fixes #
🇨🇳 Chinese
- 修复 Select 虚拟化使用崩溃问题
---
🇺🇸 English
- Fix the crash when using Select virtualization

fix: [select] fix scrollIntoView crash for virtualization Select #308

---

content/start/dark-mode/index-en-US.md
content/start/dark-mode/index.md
gatsby-node.js
packages/semi-foundation/timeline/timeline.scss
packages/semi-foundation/timeline/variables.scss

- Add block dark mode demo @pointhalo 
- Timeline content add color scss variable(prevent inheritance from body) @pointhalo 
- Remove `data_client.json` fs.copyFileSync used by doc search @DaiQiangReal please check this

docs(darkmode): add demo and Timeline content add color scss variable

---

packages/semi-icons/package.json
packages/semi-icons/scripts/compileDist.js
packages/semi-icons/webpack.config.js
packages/semi-illustrations/package.json
packages/semi-illustrations/scripts/compileDist.js
packages/semi-illustrations/webpack.config.js

Fixes #
🇨🇳 Chinese
- 新增icon和illustration的umd打包产物
---
🇺🇸 English
- Added umd package products of icon and illustration
#215

support icon and illustrations umd file#215

---

content/start/getting-started/index-en-US.md
content/start/getting-started/index.md

Fixes #
🇨🇳 Chinese
- 添加UMD使用文档
---
🇺🇸 English
- Add UMD documentation
#215

docs: update umd usage

---

.codesandbox/ci.json
package.json

- Automatically build a codesandbox environment for every single PR(or every commit in the PR)
Based on this, we can
- Avoid pulling code and building code when verifying code effects on the PR
How to verify code?
- Use building result and write/copy demo in the codesandbox

chore(codesandbox): add codesandbox ci

---

packages/semi-ui/form/field.tsx
packages/semi-ui/inputNumber/index.tsx

Fixed InputNumber loss editor api syntax hint error
🇨🇳 Chinese
- 修复 InputNumber 在编辑器没有 API 语法提示问题
---
🇺🇸 English
- Fixed InputNumber lossing API hint error in code editor

fix(inputnumber): editor api syntax hint error #327

---

packages/semi-ui/pagination/index.tsx
packages/semi-ui/resizeObserver/index.tsx
packages/semi-ui/tooltip/index.tsx

Fixed Pagination,Tooltip,ResizeObserver TS error

fix(ts): Pagination,Tooltip,ResizeObserver

---

packages/semi-foundation/input/input.scss
packages/semi-foundation/input/variables.scss

Fixed Input focus hover state border color bug
🇨🇳 Chinese
- 修复 Input focus 时 hover 态边框颜色错误问题 #234
（暗色模式的样式问题是 header 物料的样式覆盖了，不在这个 PR 修 ）
---
🇺🇸 English
- Fixed Input focus hover state border color bug #234

fix(input): focus hover state border color bug #234

---

content/input/checkbox/index-en-US.md
content/input/checkbox/index.md
packages/semi-foundation/checkbox/checkbox.scss
packages/semi-foundation/checkbox/variables.scss
packages/semi-foundation/radio/radio.scss
packages/semi-foundation/radio/variables.scss
packages/semi-ui/checkbox/__test__/checkboxGroup.test.js
packages/semi-ui/checkbox/_story/checkbox.stories.js
packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/radio/__test__/radioGroup.test.jsx
packages/semi-ui/radio/_story/radio.stories.js
packages/semi-ui/radio/radio.tsx

Fixes #
🇨🇳 Chinese
- 修复鼠标移入/移出选中按钮过程中，鼠标出现状态切换的样式问题 #319
- 修复选中态 hover/active 时选中按钮会出现外边框的问题 #319 
- 优化卡片类型 selected+disabled 态的样式 #319 
---
🇺🇸 English
- Fix the style of the state switching of the mouse when the mouse is moved in/out of the checked button #319 
- Fix the border of the checked button will appear when the checked button is hover/active #319 
- Optimize the style of the checked+disabled state of the card/pureCard type #319

fix: [Checkbo/Radio] style of checked and disabled cardType #319

---

content/show/timeline/index-en-US.md
content/show/timeline/index.md
packages/semi-ui/timeline/__test__/timeline.test.js
packages/semi-ui/timeline/item.tsx

close #359  
🇨🇳 Chinese
- Timeline time 支持 ReactNode 类型  [#359](https://github.com/DouyinFE/semi-design/issues/359)
---
🇺🇸 English
- Timeline time supports ReactNode type  [#359](https://github.com/DouyinFE/semi-design/issues/359)

feat(Timeline): The time props of the Timeline supports ReactNode

---

packages/semi-ui/tree/_story/tree.stories.js
packages/semi-ui/tree/treeNode.tsx

Fixes #364 
🇨🇳 Chinese
- 修复 Tree 组件 onContextMenu 事件不冒泡
---
🇺🇸 English
- Fix Tree component onContextMenu event no bubbling

fix(tree): contextmenu event can bubbling

---

packages/semi-foundation/checkbox/checkboxFoundation.ts
packages/semi-ui/button/Button.tsx
packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/checkbox/checkboxGroup.tsx
packages/semi-ui/select/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 Select/Checkbox/CheckboxGroup/Button 缺失 id 的问题 #353 
---
🇺🇸 English
- Select/Checkbox/CheckboxGroup/Button support id #353

feat: [Select/Checkbox/Button] add id #353

---

packages/semi-foundation/modal/variables.scss
packages/semi-foundation/sideSheet/variables.scss
packages/semi-foundation/upload/variables.scss
packages/semi-theme-default/scss/global.scss

Fixes #
🇨🇳 Chinese
- 修复 --semi-overlay-bg 全局css 变量未按规范命名，缺少color前缀的问题
---
🇺🇸 English
- Fix ...
fix_lack_color_overlay-bg

fix: token overlay-bg lack color prefix

---

packages/semi-ui/package.json

I search this package in npmjs.com, but the search result page can not jump directly to a Git repository
🇨🇳 Chinese
- 修复 无
---
🇺🇸 English
- Fix none
add bugs, homepage, repository property to the package.json

Add extra info to package json

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md
packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/__test__/cascader.test.js
packages/semi-ui/cascader/_story/cascader.stories.js
packages/semi-ui/cascader/index.tsx

Feat #302 
🇨🇳 Chinese
-  级联选择器多选时，enableLeafClick属性为true支持末级节点整行点击触发选中
---
🇺🇸 English
- Fix ...

feat: cascader add enableLeafClick

---

packages/semi-webpack/README.md
packages/semi-webpack/src/semi-webpack-plugin.ts

Feature: support extracting css in webpack
🇨🇳 Chinese
- 支持将组件CSS提取到独立的文件
---
🇺🇸 English
- Support extracting component CSS to a separate file

feat: support for extracting css in webpack

---

packages/semi-foundation/select/select.scss

- [ x ] Bugfix
Fixes #375 
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix #375

fix(select) #375

---

packages/semi-scss-compile/src/bin.ts
packages/semi-scss-compile/src/index.ts
packages/semi-scss-compile/src/utils/compiler.ts
packages/semi-scss-compile/src/utils/generateSCSSMap.ts
packages/semi-scss-compile/src/utils/writeFile.ts

Fixes #
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

Fix scss charset warning in vite

---

packages/semi-foundation/cascader/cascader.scss
packages/semi-ui/cascader/_story/cascader.stories.js

Fixes #
🇨🇳 Chinese
- 修复Cascader multiple+disabled 时标签样式不符合预期
---
🇺🇸 English
- Modify style when multiple and disabled

style: [Cascader] modify style when multiple and disabled #400

---

content/show/sidesheet/index-en-US.md
content/show/sidesheet/index.md
packages/semi-foundation/sideSheet/sideSheetFoundation.ts
packages/semi-ui/sideSheet/SideSheetContent.tsx
packages/semi-ui/sideSheet/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

a11y:sidesheet

---

packages/semi-foundation/timeline/timeline.scss
packages/semi-ui/timeline/_story/timeline.stories.js

Fixes timeline custom dot property does not align with another dot
🇨🇳 Chinese
- 修复  timeline dot 不对齐
---
🇺🇸 English
- Fix  timeline custom dot property does not align with another dot

style: fix timeline custom dot props not align

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md
packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/__test__/cascader.test.js
packages/semi-ui/cascader/index.tsx
packages/semi-ui/cascader/item.tsx

Fixes #
🇨🇳 Chinese
- Cascader 支持 separator
---
🇺🇸 English
- Cascader supports separator

feat: [Cascader] support separator #408

---

content/basic/icon/index-en-US.md
content/basic/icon/index.md
packages/semi-icons/src/components/Icon.tsx
src/components/IconList/index.scss

#360 
🇨🇳 Chinese
- Icon支持跟随当前上下文字体大小
---
🇺🇸 English
- Icon supports following the current context font size

feat: Icon size support inherit

---

packages/semi-ui/rating/item.tsx

Reverts DouyinFE/semi-design#358

Revert "fix(rating): size props working error when set number #356"

---

content/other/locale/index-en-US.md
content/other/locale/index.md
packages/semi-ui/locale/source/es.ts
src/templates/scope.js

支持西班牙语
🇨🇳 Chinese
- LocaleProvider 支持西班牙语 [@chenjunxyf](https://github.com/chenjunxyf)
---
🇺🇸 English
- LocaleProvider support Spanish [@chenjunxyf](https://github.com/chenjunxyf)

feat(locale): support spanish

---

packages/semi-foundation/notification/notification.scss
packages/semi-foundation/notification/variables.scss

Reverts DouyinFE/semi-design#430

Revert "修正了多色模式下，背景色透明导致的内容穿透"

---

packages/semi-ui/empty/index.tsx

Fixed Empty `this.updateMode` `undefined` bug
🇨🇳 Chinese
- 修复 Empty `this.updateMode` 未定义问题
---
🇺🇸 English
- Fixed Empty `this.updateMode` `undefined` bug

fix(empty): this.updateMode undefined bug

---

content/navigation/navigation/index.md

Fixes #
🇨🇳 Chinese
- 修复 ...
更改导航向为导航项
---
🇺🇸 English
- Fix ...
change a word

docs: contributing typo

---

packages/semi-ui/tabs/index.tsx

fix: fix tabPlane tab props error in umd
Fixes #
fix tabPlane tab props error in umd。Remove logic of getting props by propTypes, cause propTypes will be treeshaked while building umd.
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

fix: fix tabPlane tab props error in umd

---

content/navigation/steps/index-en-US.md
content/navigation/steps/index.md
packages/semi-ui/steps/basicStep.tsx
packages/semi-ui/steps/basicSteps.tsx
packages/semi-ui/steps/fillStep.tsx
packages/semi-ui/steps/fillSteps.tsx
packages/semi-ui/steps/navStep.tsx
packages/semi-ui/steps/navSteps.tsx

Fixes #
🇨🇳 Chinese
- Steps新增a11y支持
---
🇺🇸 English
- Steps新增a11y支持

feat: [Steps] support a11y

---

content/input/transfer/index-en-US.md
content/input/transfer/index.md
packages/semi-foundation/transfer/transfer.scss
packages/semi-ui/transfer/index.tsx

feat: a11y transfer
🇨🇳 Chinese
- Transfer支持A11y ARIA
---
🇺🇸 English
- Support A11y ARIA for Transfer

feat: a11y transfer

---

content/show/dropdown/index-en-US.md
content/show/dropdown/index.md
packages/semi-ui/dropdown/dropdownItem.tsx
packages/semi-ui/dropdown/dropdownMenu.tsx

Fixes #
🇨🇳 Chinese
- Dropdown 新增a11y ARIA支持
---
🇺🇸 English
- Dropdown support a11y ARIA

feat: [Dropdown] support a11y ARIA

---

content/show/card/index-en-US.md
content/show/card/index.md
packages/semi-ui/card/_story/card.stories.js
packages/semi-ui/card/_story/card.stories.tsx
packages/semi-ui/card/index.tsx

Fixes #
🇨🇳 Chinese
- chore: Card 支持 a11y aria
---
🇺🇸 English
- chore: Card support a11y aria

chore: [Card] support a11y aria-*

---

content/input/taginput/index-en-US.md
content/input/taginput/index.md
packages/semi-foundation/tagInput/foundation.ts
packages/semi-ui/tagInput/_story/tagInput.stories.js
packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- chore: TagInput 支持 A11y aria
---
🇺🇸 English
- chore: TagInput supports A11y aria

feat: [TagInput] support ally aria-*

---

README-zh_CN.md
README.md

docs(readme): add cypress badge

---

packages/semi-foundation/table/table.scss

Fixed Tabel head row paddingY not same with design draft bug #460
🇨🇳 Chinese
- 修复 Table head row paddingY 与设计稿不符问题，统一调整为 8px #460
---
🇺🇸 English
- Fixed Tabel head row paddingY not same with design draft bug and updated to `8px` #460
```jsx
import React from 'react';
import { Table } from '@douyinfe/semi-ui';
const { Column } = Table;
function App() {
const [size, setSize] = useState('default');
const data = [
{
key: '1',
name: 'Semi Design 设计稿.fig',
nameIconSrc: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/figma-icon.png',
size: '2M',
owner: '姜鹏志',
updateTime: '2020-02-02 05:13',
avatarBg: 'grey'
},
{
key: '2',
name: 'Semi Design 分享演示文稿', …
```

style(table): head row paddingY update to 8px #460

---

packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-ui/datePicker/__test__/datePicker.test.js
packages/semi-ui/datePicker/_story/datePicker.stories.js
packages/semi-ui/datePicker/datePicker.tsx
packages/semi-ui/datePicker/monthsGrid.tsx

修复 dateRange 类型 DatePicker，triggerRender 传入时选择完日期面板没有关闭问题
- before
- after
🇨🇳 Chinese
- 修复 dateRange 类型 DatePicker，triggerRender 传入时选择完日期面板没有关闭问题 #422
---
🇺🇸 English
- Fix the issue that the dateRange type DatePicker, when triggerRender is passed in, the panel does not close after selecting the date #422
```jsx
import { DatePicker, Space, Button } from '@douyinfe/semi-ui';
const FixTriggerRenderClosePanel = () => {
const [value, setValue] = useState([]);
const handleChange = v => {
console.log('change', v);
setValue(v);
};
const formatValue = (dates) => {
const dateStrs = dates.map(v => String(v));
return dateStrs.join(' ~ ');
};
const showClear = Array.isArray(value) && …
```

fix(datepicker): dateRange triggerRender close panel bug #410

---

packages/semi-foundation/inputNumber/foundation.ts
packages/semi-ui/inputNumber/_story/inputNumber.stories.js
packages/semi-ui/inputNumber/index.tsx

Fixed InputNumber precision format bug in controlled mode
🇨🇳 Chinese
- 修复 InputNumber 精度格式化在受控模式下不正确问题
---
🇺🇸 English
- Fixed InputNumber precision format bug in controlled mode

fix(inputnumber): input value format bug #431

---

content/feedback/banner/index-en-US.md
content/feedback/banner/index.md
packages/semi-ui/banner/index.tsx

为 banner 添加 a11y aria
🇨🇳 Chinese
- Banner 组件添加 A11y Aria
---
🇺🇸 English
- Banner component add A11y Aria

feat(a11y): banner a11y

---

content/input/taginput/index-en-US.md
content/input/taginput/index.md
packages/semi-ui/tagInput/__test__/tagInput.test.js
packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- fix: 修复 TagInput 设置 value 为 undefined 无法生效的问题
---
🇺🇸 English
- fix: [TagInput] set value to falsely has no effect

fix: [TagInput] set value to falsely has no effect #483

---

content/navigation/breadcrumb/index-en-US.md
content/navigation/breadcrumb/index.md
packages/semi-foundation/breadcrumb/foundation.ts
packages/semi-ui/breadcrumb/_story/breadcrumb.stories.js
packages/semi-ui/breadcrumb/index.tsx
packages/semi-ui/breadcrumb/item.tsx

Fixes #
🇨🇳 Chinese
- feat: breadcrumb 支持 a11y 语义化
---
🇺🇸 English
- feat: breadcrumb support a11y aria

feat: [Breadcrumb] add a11y aria-*

---

packages/semi-ui/list/item.tsx

list support a11y ARIA
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

feat(list): support a11y ARIA

---

content/basic/layout/index-en-US.md
content/basic/layout/index.md
packages/semi-ui/layout/Sider.tsx
packages/semi-ui/layout/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 ...
---
🇺🇸 English
- Fix ...

a11y: layout

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
content/navigation/tree/index-en-US.md
content/navigation/tree/index.md
packages/semi-foundation/tree/foundation.ts
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/tree/_story/tree.stories.js
packages/semi-ui/tree/index.tsx
packages/semi-ui/tree/treeNode.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- feat: Tree 支持 A11y aria
- feat: TreeSelect 支持 A11y aria
---
🇺🇸 English
- feat: Tree supports A11y aria
- feat: TreeSelect supports A11y aria

feat: [Tree/TreeSelect] support A11y aria

---

packages/semi-foundation/form/foundation.ts
packages/semi-ui/form/_story/Validate/validateDemo.jsx

Fixes #510
🇨🇳 Chinese
- Fix: 修复Form formApi.validate 局部校验触发范围不准确的问题
---
🇺🇸 English
- Fix: Fix the inaccurate trigger range of Form formApi.validate partial verification

fix: form validate partial, close #510

---

content/input/upload/index-en-US.md
content/input/upload/index.md
packages/semi-ui/upload/fileCard.tsx
packages/semi-ui/upload/index.tsx

Fixes #
🇨🇳 Chinese
- Upload 完善a11y ARIA #205 
---
🇺🇸 English
- Upload 完善a11y ARIA #205

feat(upload): support a11y ARIA

---

.github/workflows/cypress.yml

Fixes #
🇨🇳 Chinese
- Fix: 修复 fork仓库同步upstream代码ci测试报错
---
🇺🇸 English
- Fix: fix fork repository synchronization upstream code ci test error

chore(ci): avoid cypress workflow running through fork

---

packages/semi-foundation/notification/notificationListFoundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 notification 显示收起顺序，看起来更正常
---
🇺🇸 English
- Fix: Fix notification animation order，make it more reasonable.

fix: fix notification show and hide order

---

.github/workflows/chromatic.yml

Fixes #
🇨🇳 Chinese
- Fix: 修复 fork仓库同步upstream代码ci测试缺少项目token报错
---
🇺🇸 English
- Fix: fix fork repository synchronization upstream code ci test missing project token error

chore(ci): fix fork repository missing project token

---

packages/semi-ui/dropdown/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Dropdown menu 类型定义异常问题
---
🇺🇸 English
- Fix: fix Dropdown props menu type definition
- [] Test or no need

fix(dropdown): menu types

---

packages/semi-ui/inputNumber/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 InputNumber 传入 defaultValue 是警告问题 [@chenc041](https://github.com/chenc041)  [#537](https://github.com/DouyinFE/semi-design/issues/537)
---
🇺🇸 English
- Fix: fixed warning when InputNumber given defaultValue [@chenc041](https://github.com/chenc041) [#537](https://github.com/DouyinFE/semi-design/issues/537)

fix(inputnumber): reduce unused value passed to input component

---

gatsby-node.js
package.json
src/html.js
yarn.lock

Fixes #
🇨🇳 Chinese
- Feat: 新增主题切换器
---
🇺🇸 English
- Feat: add theme switcher

feat: add theme switcher trigger

---

packages/semi-foundation/inputNumber/constants.ts
packages/semi-foundation/inputNumber/foundation.ts
packages/semi-ui/inputNumber/__test__/inputNumber.test.js

Fixes InputNumber button right click bug
🇨🇳 Chinese
- Fix: 修复 InputNumber 按钮右键点击时数字自动增/减问题 #
---
🇺🇸 English
- Fix: fix InputNumber button right click bug
- bug video
- [event.button MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent/button)

fix(inputnumber): button right click bug

---

cypress/integration/table.spec.js
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/table.stories.js
packages/semi-ui/table/_story/v2/FixedColumnsChange/index.jsx

Fixed #381
🇨🇳 Chinese
- Fix: 修复 columns 变化后分页器返回到第一页问题 #381
---
🇺🇸 English
- Fix: fixed page back to one when columns change bug #381

fix(table): page back to one when columns change #381

---

packages/semi-ui/timePicker/__test__/timePicker.test.js

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

test(timepicker): update test cases

---

packages/semi-foundation/table/variables.scss

插值语法在拼接字符串或者去除字符串的引号时有用，其他场景无需使用插值语法
https://sass-lang.com/documentation/interpolation
```scss
$prefix: semi;
$border: "solid";
$width: 24px;
#{$prefix}-button-bg: red; // ✅
$semi-button-color: 1px #{$border} red; // ✅
$semi-button-width: #{$width}; // ❌
$semi-button-width: $width; // ✅
```

chore(table): update table/variables.scss code style

---

gatsby-node.js
src/components/header.js

Fixes #
🇨🇳 Chinese
---
🇺🇸 English

feat: update header use process.env

---

packages/semi-foundation/select/optionFoundation.ts
packages/semi-ui/select/option.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 `isDisbled` 单词拼写
---
🇺🇸 English
- Fix: fix ...

fix(typo): change `isDisbled` to `isDisabled`

---

cypress/integration/table.spec.js
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/table.stories.js
packages/semi-ui/table/_story/v2/FixedHeaderMerge/index.jsx

Fixes #619
🇨🇳 Chinese
- Fix: 修复 Table JSX columns 表头合并问题 #619
---
🇺🇸 English
- Fix: fixed Table header merge bug when using JSX columns #619

fix(table): jsx nested columns bug #619

---

packages/semi-foundation/slider/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 slider 在 shadowRoot、WebComponent 或其他 DocumentFragment 下报错的问题
---
🇺🇸 English
- Fix: fix slider throw error in shadowDOM or other DocumentFragment env

fix: fix slider throw error in shadowDOM or other DocumentFragment env

---

content/show/scrolllist/index-en-US.md
content/show/scrolllist/index.md
packages/semi-ui/scrollList/_story/ScrollList/index.js
packages/semi-ui/scrollList/_story/WheelList/index.js
packages/semi-ui/scrollList/scrollItem.tsx

Fixes #
🇨🇳 Chinese
- feat: ScrollList 支持 A11y ARIA
---
🇺🇸 English
- feat: ScrollList supports A11y ARIA

feat(scrolllist): a11y aria

---

packages/semi-foundation/datePicker/foundation.ts
packages/semi-foundation/datePicker/inputFoundation.ts
packages/semi-foundation/datePicker/monthFoundation.ts
packages/semi-ui/datePicker/dateInput.tsx
packages/semi-ui/datePicker/datePicker.tsx
packages/semi-ui/datePicker/month.tsx
packages/semi-ui/datePicker/monthsGrid.tsx
packages/semi-ui/datePicker/navigation.tsx
packages/semi-ui/datePicker/quickControl.tsx
packages/semi-ui/datePicker/yearAndMonth.tsx

Fixes #
🇨🇳 Chinese
- Feat: DatePicker 支持 A11y ARIA
---
🇺🇸 English
- Fix: DatePicker supports A11y ARIA

feat(datepicker): a11y aria #205

---

packages/semi-foundation/table/utils.ts
packages/semi-ui/table/_story/table.stories.js
packages/semi-ui/table/_story/v2/FixedResizable/index.jsx

Fixes #650
问题原因见 #650
🇨🇳 Chinese
- Fix: 修复 resizable Table 动态删除列时列宽计算错误问题 #650
---
🇺🇸 English
- Fix: fixed resizable Table columns width bug when update `columns` #650

fix(table): resizable column width bug #650

---

packages/semi-foundation/cascader/cascader.scss
packages/semi-foundation/cascader/variables.scss

Fixes:  [#636](https://github.com/DouyinFE/semi-design/issues/636)
🇨🇳 Chinese
- style: [breaking change] 修复 Cascader 在多选模式下标签对齐，移除 $spacing-cascader_selection_tag-marginX，新增$spacing-cascader_selection_tag-marginLeft和$spacing-cascader_selection_tag-marginRight #636 
---
🇺🇸 English
- style:  [breaking change] fix Cascader tag alignment in multi-select mode, remove $spacing-cascader_selection_tag-marginX，add $spacing-cascader_selection_tag-marginLeft和$spacing-cascader_selection_tag-marginRight  #636

style(cascader): tag alignment in multi-select mode

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md
packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/index.tsx
packages/semi-ui/cascader/item.tsx

chore: [Cascader] display the layer relationship of items by a11y
feat: [Cascader] support aria-*
Fixes #
🇨🇳 Chinese
- chore: Cascader 支持 aria-*
---
🇺🇸 English
- chore: Cascader support aria-*

feat: [Cascader] support a11y aria-*

---

packages/semi-foundation/table/table.scss

Fixes: [#638](https://github.com/DouyinFE/semi-design/issues/638)
🇨🇳 Chinese
- Fix:  修复 `Table` 表头文字不支持选中
---
🇺🇸 English
- Fix: fix `Table` header does not support text select

style(table): support text select in table header

---

packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss
packages/semi-theme-default/scss/_palette.scss
packages/semi-theme-default/scss/global.scss

A11y 主题微调
🇨🇳 Chinese
- Syle: 微调默认主题的 5 个 CSS token 和 Table 空文本的文本色以适配 A11y #205
---
🇺🇸 English
- Style: Updated default theme's 5 CSS tokens and Table empty text text color to fit A11y #205

style: a11y theme update

---

content/input/button/index-en-US.md
content/input/button/index.md
packages/semi-foundation/button/button.scss
packages/semi-foundation/button/variables.scss

Button 新增焦点样式
🇨🇳 Chinese
- Feat: Button 新增焦点样式
---
🇺🇸 English
- Feat: Button added focus style

feat(button): keyboard and focus #205

---

.vscode/settings.json
cypress/integration/tooltip.spec.js
packages/semi-ui/tooltip/_story/tooltip.stories.js
packages/semi-ui/tooltip/index.tsx

Fixes #675
🇨🇳 Chinese
- Fix: 修复 tooltip content中组件无法autoFocus的问题
---
🇺🇸 English
- Fix: fix tooltip content autoFocus unexpected behaviour

fix: tootip content autoFocus fix complete

---

packages/semi-foundation/button/constants.ts
packages/semi-ui/button/index.tsx

Fixes Button strings TS error
- before
- after
🇨🇳 Chinese
- Fix: 修复 Button type 等属性 dts 类型错误问题
---
🇺🇸 English
- Fix: Fixed the dts type error of props such as Button type

Fix button dts

---

packages/semi-foundation/tag/tag.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复3px留白问题 ...
---
🇺🇸 English
- Fix: fix [Tag] 3px white space problem ...

fix: [Tag] 3px white space problem

---

cypress/integration/datePicker.spec.js
packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/SubNav.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Navigation limitIndent 为 false 时的缺失 key 的警告
---
🇺🇸 English
- Fix: fix navigation lacking key warning, when limitIndent is false #679

fix: fix nav lacking key warning, when limitIndent false #679

---

content/input/button/index-en-US.md
content/input/button/index.md
packages/semi-ui/button/__test__/button.test.js
packages/semi-ui/button/buttonGroup.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
ButtonGroup 支持 className
---
🇺🇸 English
- Fix: fix ...
ButtonGroup support calssName props

fix: (ButtonGroup) support className props 

---

content/input/datepicker/index-en-US.md
content/input/datepicker/index.md
cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/_utils/formatter.ts
packages/semi-foundation/datePicker/_utils/getInsetInputFormatToken.ts
packages/semi-foundation/datePicker/_utils/getInsetInputValueFromInsetInputStr.ts
packages/semi-foundation/datePicker/constants.ts
packages/semi-foundation/datePicker/datePicker.scss
packages/semi-foundation/datePicker/foundation.ts
packages/semi-foundation/datePicker/inputFoundation.ts
packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-foundation/datePicker/rtl.scss
packages/semi-foundation/datePicker/variables.scss
packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/datePicker/_story/v2/InsetInput.jsx
packages/semi-ui/datePicker/_story/v2/InsetInputE2E.jsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/dateInput.tsx
packages/semi-ui/datePicker/datePicker.tsx
packages/semi-ui/datePicker/index.tsx
packages/semi-ui/datePicker/insetInput.tsx
packages/semi-ui/datePicker/monthsGrid.tsx
packages/semi-ui/input/_story/input.stories.js

DatePicker 支持内嵌输入框，通过 inlineInput 打开 #294
🇨🇳 Chinese
- Feat: DatePicker 支持内嵌样式输入框 #294
---
🇺🇸 English
- Feat: DatePicker supports inline input in panel #294

feat(datepicker): support inlineInput API #294

---

packages/semi-ui/notification/useNotification/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: fix notice useNotification same ID

---

.gitignore
.storybook/base/base.js
.storybook/base/utils.js
.storybook/js/main.js
cypress/fixtures/placeholder.json
cypress/integration/modal.spec.js
cypress/integration/notification.spec.js
cypress/integration/textarea.spec.js
cypress/integration/toast.spec.js
cypress/plugins/index.js
cypress/support/index.js
jest.config.js
nyc.config.js
package.json
packages/semi-ui/_base/_story/index.stories.js
packages/semi-ui/_portal/_story/portal.stories.js
packages/semi-ui/_utils/hooks/usePrevFocus.ts
packages/semi-ui/input/_story/input.stories.js
packages/semi-ui/modal/_story/modal.stories.js
packages/semi-ui/modal/useModal/HookModal.tsx
packages/semi-ui/notification/_story/useNotification/index.jsx
packages/semi-ui/toast/_story/toast.stories.js
yarn.lock

test: merge cypress and enzyme code coverage

---

packages/semi-foundation/utils/getHighlight.ts
packages/semi-ui/select/__test__/select.test.js
packages/semi-ui/select/option.tsx

Fixes #743  
🇨🇳 Chinese
- Fix: 修复 filter 以特殊字符过滤时崩溃
---
🇺🇸 English
- Fix: fix filter text start with special chars

fix(select): filter text start with special chars

---

.github/workflows/cypress.yml
cypress/integration/helloworld.spec.js

Fixes https://github.com/cypress-io/github-action/issues/446
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

test: fix cypress permission problem

---

packages/semi-foundation/cascader/constants.ts
packages/semi-foundation/tagInput/constants.ts
packages/semi-ui/form/_story/demo.jsx

有时候需要动态表单验证rules有可能是`[]`，Cascader与TagInput就会提示一下警告
🇨🇳 Chinese
- Fix: 修复validateStatus类型检查缺少success
---
🇺🇸 English
- Fix: fix validateStatus type check lack success

fix: validateStatus type check lack success

---

packages/semi-foundation/divider/constants.ts
packages/semi-foundation/divider/divider.scss
packages/semi-foundation/divider/variables.scss
packages/semi-ui/divider/__test__/divider.test.js
packages/semi-ui/divider/_story/Demo.tsx
packages/semi-ui/divider/_story/divider.stories.js
packages/semi-ui/divider/_story/divider.stories.tsx
packages/semi-ui/divider/index-en-US.md
packages/semi-ui/divider/index.md
packages/semi-ui/divider/index.tsx
packages/semi-ui/index.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

feat: add divider component

---

packages/semi-ui/badge/index.tsx

修复 Badge 不能搭配Tooltip使用的问题
🇨🇳 Chinese
- Fix: 修复 Badge 不能搭配 Tooltip使用的问题
---
🇺🇸 English
- Fix: Fixed an issue where Badge could not be used with Tooltip

fix: badge can't work with tooltip

---

packages/semi-foundation/datePicker/variables.scss
packages/semi-foundation/form/variables.scss
packages/semi-foundation/input/variables.scss
packages/semi-foundation/popover/variables.scss
packages/semi-foundation/scrollList/variables.scss
packages/semi-foundation/select/variables.scss
packages/semi-foundation/tabs/variables.scss
packages/semi-foundation/tooltip/variables.scss

Fixes #
🇨🇳 Chinese
---
🇺🇸 English

fix: scss optimize

---

.gitignore
content/show/list/index-en-US.md
content/show/list/index.md

第一次选择时, 会丢失原有值
Fixes # fix doc case bug for list component
🇨🇳 Chinese
- Fix: 修复`list`组件的文档 多选案例
---
🇺🇸 English
- Fix: fix ...
Need to ignore local folders generated by vscode plugin

fix: list组件的文档案例 复选框example错误, 应该接受一个数组而不是一个string

---

packages/semi-foundation/avatar/avatar.scss
packages/semi-foundation/avatar/rtl.scss

Fixes Avatar 文本内容居中方式（C2D无法动态计算绝对定位，因此换个方案）
🇨🇳 Chinese
- Fix: 更新 Avatar 文本内容居中方式，由绝对定位改为由父级布局居中
---
🇺🇸 English
- Fix: Update the centering method of Avatar text content, from absolute positioning to centering by the parent layout

Fix avatar position

---

packages/semi-foundation/form/form.scss

Fixes #
🇨🇳 Chinese
- Fix: 去除 Form label user-select:none，允许用户选中
---
🇺🇸 English
- Fix: remove Form label user-select:none， allow user select

Fix form label allow select

---

packages/semi-ui/collapse/item.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 collapse 将部分props透传至 dom 导致存在无用属性warning的问题
---
🇺🇸 English
- Fix: Fix the problem that collapse dom has useless attributes

fix:(collapse) dom usless attribute

---

packages/semi-foundation/select/select.scss

Fixes #
🇨🇳 Chinese
- Style: 修复 Select focus 和 hover 同时应用，border 颜色不正常的问题
---
🇺🇸 English
- Style: Fix the problem that the border color is not right when Select focus and hover are applied at the same time

fix: (select) fix select focus&hover border style

---

packages/semi-foundation/select/select.scss
packages/semi-ui/form/hoc/withField.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Form Validate 特殊情景下内部使用旧值的问题
---
🇺🇸 English
- Fix: Fix the problem that the old value is used internally in the special case of Form Validate

fix:(form) #796

---

packages/semi-ui/banner/_story/banner.stories.js
packages/semi-ui/banner/index.tsx

feat(a11y): banner Icon label change
Fixes #
🇨🇳 Chinese
- Feat: Banner 新增 A11y 键盘和焦点适配 #205
---
🇺🇸 English
- Feat: Banner adds A11y keyboard and focus adaptation #205

feat(a11y): banner Icon aria change

---

packages/semi-foundation/switch/constants.ts
packages/semi-foundation/switch/foundation.ts
packages/semi-foundation/switch/switch.scss
packages/semi-foundation/switch/variables.scss
packages/semi-ui/switch/index.tsx

feat(a11y): switch focus
Fixes #
🇨🇳 Chinese
- Feat: Switch 新增 A11y 键盘和焦点适配 #205
---
🇺🇸 English
- Feat: Switch adds A11y keyboard and focus adaptation #205

feat(a11y): switch focus

---

packages/semi-ui/cascader/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复cascader在多选时，设定displayProp非value/label时候出错问题
---
🇺🇸 English
- Fix: fix cascader's displayProp error when mutiple selection

fix: [cascader] displayProp error when mutiple selection

---

content/navigation/tabs/index-en-US.md
content/navigation/tabs/index.md

给Tabs增加faq
🇨🇳 Chinese
- Documentation: 给Tabs增加faq
---
🇺🇸 English
- Documentation: add faq to tabs doc

feat: add faq to tabs doc

---

content/show/carousel/index-en-US.md
content/show/carousel/index.md
packages/semi-foundation/carousel/carousel.scss
packages/semi-foundation/carousel/foundation.ts
packages/semi-ui/carousel/CarouselArrow.tsx
packages/semi-ui/carousel/CarouselIndicator.tsx
packages/semi-ui/carousel/index.tsx
packages/semi-ui/carousel/interface.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复自动播放时点击箭头切换或指示器切换不能即时响应问题
---
🇺🇸 English
- Fix: Fix the problem that clicking the arrow switch or the indicator switch does not respond instantly during autoplay

修复自动播放时点击箭头切换或指示器切换不能即时响应问题

---

content/feedback/banner/index-en-US.md
content/feedback/banner/index.md
content/input/switch/index-en-US.md
content/input/switch/index.md

Fixes #
🇨🇳 Chinese
- Fix: 
---
🇺🇸 English
- Fix:

docs: add a11y docs about switch and banner

---

packages/semi-foundation/form/foundation.ts
packages/semi-foundation/form/interface.ts
packages/semi-ui/form/baseForm.tsx

Fixes #808
🇨🇳 Chinese
- Fix: 修复Form组件在`Nextjs`中使用时，`x-form-id`在服务端和客户端不匹配的报错问题 #808
---
🇺🇸 English
- Fix: Fixed the error that the x-form-id does not match between the server and the client when the Form component is used in Nextjs

fix: [Form]x-form-id does not match between server and client

---

packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/checkbox/checkboxInner.tsx

Fixes # 
🇨🇳 Chinese
- Fix: 修复单个Checkbox使用时因为参数类型问题导致控制台出现warning提示
---
🇺🇸 English
- Fix: Fixed a warning prompt on the console due to the parameter type problem when using a single Checkbox

fix: fix checkbox relative props

---

content/show/tag/index-en-US.md
content/show/tag/index.md
packages/semi-ui/select/index.tsx
packages/semi-ui/tag/group.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- Documentation: 规范 TagGroup tagList props 类型
---
🇺🇸 English
- Documentation: Specification TagGroup tagList props type

fix: add doc  #834

---

packages/semi-ui/select/index.tsx

Fixes #840
🇨🇳 Chinese
- Fix:  Select aria-controls 在 SSR 场景不一致问题 #840
---
🇺🇸 English
- Fix: Select aria-controls are inconsistent in SSR scenarios #840

fix(select): aria-controls value bug in ssr #840

---

cypress/integration/table.spec.js
packages/semi-ui/table/HeadTable.tsx
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/v2/FixedOnHeaderRow/index.jsx
packages/semi-ui/table/_story/v2/index.js

Fixes #849
🇨🇳 Chinese
- Fix: 修复 Table onHeaderRow 在配置 scroll 属性时不生效问题 #849
---
🇺🇸 English
- Fix: fix Table onHeaderRow does not take effect when setting scroll prop #849

fix(table): onHeaderRow does not take effect bug #849

---

content/input/upload/index-en-US.md
content/input/upload/index.md

Fixes #
🇨🇳 Chinese
- Docs: 增加Upload在directory为true的情况下，点击上传和拖拽上传时行为不同的说明
---
🇺🇸 English
- Docs: Added a description that when the directory is true, Upload behaves differently when clicking upload and dragging upload

docs: update upload doc

---

packages/semi-ui/modal/Modal.tsx
packages/semi-ui/modal/confirm.tsx
packages/semi-ui/modal/useModal/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 useModal typescript 返回类型不严谨的问题
---
🇺🇸 English
- Fix: Fix the problem that the return type of useModal typescript is not strict

fix: useModal return type error  #833

---

packages/semi-foundation/tag/tag.scss
packages/semi-foundation/tag/variables.scss

Fixes #
🇨🇳 Chinese
- Feat: Tag solid 模式关闭按钮新增颜色 token
---
🇺🇸 English
- Feat: Tag solid closable icon token

Feat: tag solid closable icon token

---

content/navigation/tabs/index-en-US.md
content/navigation/tabs/index.md
packages/semi-foundation/tabs/foundation.ts
packages/semi-foundation/tabs/tabs.scss
packages/semi-foundation/tabs/variables.scss
packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tabs/TabPane.tsx
packages/semi-ui/tabs/index.tsx
packages/semi-ui/tabs/interface.ts

Fixes #
🇨🇳 Chinese
- Feat: Tabs 新增 A11y 键盘和焦点适配  #205 
---
🇺🇸 English
- Feat: Tabs add A11y keyboard and focus adaptation #205

feat(a11y): add keyboard and focus events to tabs

---

content/navigation/tabs/index-en-US.md
content/navigation/tabs/index.md
packages/semi-foundation/tabs/foundation.ts
packages/semi-foundation/tabs/tabs.scss
packages/semi-foundation/tabs/variables.scss
packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tabs/TabPane.tsx
packages/semi-ui/tabs/index.tsx
packages/semi-ui/tabs/interface.ts

Reverts DouyinFE/semi-design#852

Revert "feat(a11y): add keyboard and focus events to tabs"

---

packages/semi-ui/select/index.tsx

- Fixes https://github.com/DouyinFE/semi-design/issues/714
🇨🇳 Chinese
- 修复开启虚拟化且无数据时额外的空白容器
---
🇺🇸 English
- Fix blank virtualize container without data

fix(ui-select): blank virtualize container without data

---

packages/semi-ui/slider/index.tsx

Close #618
🇨🇳 Chinese
- Feat: Slider 支持点击 marks 改变滑块位置 #618
---
🇺🇸 English
- Feat: Slider supports clicking marks to change the slider position #618
的确需要增加热区，这里加上了 see https://github.com/DouyinFE/semi-design/issues/618

increase slider hot area #618

---

packages/semi-ui/progress/index.tsx

- [x ] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.
feat(#456)
background-color属性不支持渐变色，故改为background

feat(progress): 支持线性渐变背景颜色

---

content/show/modal/index-en-US.md
content/show/modal/index.md
cypress/integration/modal.spec.js
cypress/support/index.js
package.json
packages/semi-foundation/utils/FocusHandle.ts
packages/semi-ui/button/Button.tsx
packages/semi-ui/modal/Modal.tsx
packages/semi-ui/modal/ModalContent.tsx
yarn.lock

Fixes #
🇨🇳 Chinese
- Feat: Modal 新增 A11y 键盘和焦点适配。 #205 
---
🇺🇸 English
- Fix: Modal adds A11y keyboard and focus adaptation. #205

feat(a11y): modal keyboard focus

---

content/input/checkbox/index-en-US.md
content/input/checkbox/index.md
cypress/integration/checkbox.spec.js
packages/semi-foundation/checkbox/checkbox.scss
packages/semi-foundation/checkbox/checkboxFoundation.ts
packages/semi-foundation/checkbox/variables.scss
packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/checkbox/checkboxInner.tsx

Fixes #
🇨🇳 Chinese
- Feat: Checkbox 新增 A11y 键盘和焦点适配 #205
---
🇺🇸 English
- Feat: Checkbox add A11y keyboard and focus adaptation #205

feat(a11y): checkbox keyboard focus

---

packages/semi-foundation/checkbox/checkboxFoundation.ts
packages/semi-ui/checkbox/checkbox.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复checkbox ally 焦点问题
---
🇺🇸 English
- Fix: fix checkbox ally focus issue

fix: checkbox a11y focus error

---

packages/semi-foundation/button/button.scss
packages/semi-foundation/button/variables.scss

Fixes #
🇨🇳 Chinese
- Feat: Button 组件新增 borderless 模式下文字颜色 token
---
🇺🇸 English
- Feat: Add some text color token to borderless theme Button.

[Button] Fix button borderless token

---

content/navigation/tree/index-en-US.md
content/navigation/tree/index.md

Fixes #
🇨🇳 Chinese
- Docs: 增加searchRender API 和 search方法的示例
---
🇺🇸 English
- Docs: Added example of searchRender API and search method

docs: [Tree] Added example of searchRender API and search method

---

packages/semi-ui/gulpfile.js

Fixes #
🇨🇳 Chinese
- Fix: 修复 esm / cjs 构建产物，滚动条样式部分场景失效的问题
---
🇺🇸 English
- Fix: Fix the issue that scroll bar style is invalid in some scenes.

Fix: fix  gulp compile

---

content/input/radio/index-en-US.md
content/input/radio/index.md
cypress/integration/radio.spec.js
packages/semi-foundation/radio/radio.scss
packages/semi-foundation/radio/radioFoundation.ts
packages/semi-foundation/radio/variables.scss
packages/semi-ui/radio/_story/radio.stories.js
packages/semi-ui/radio/radio.tsx
packages/semi-ui/radio/radioInner.tsx

Feat related to #205 
🇨🇳 Chinese
- feat: Radio新增 A11y 键盘适配
---
🇺🇸 English
- feat:  Added A11y keyboard adaptation for Radio

feat(a11y): Radio a11y keyboard #205

---

cypress/integration/cascader.spec.js
packages/semi-ui/cascader/_story/cascader.stories.js

…hangeWithObject
Fixes #
🇨🇳 Chinese
- Fix: 增加当设置onChangeWithObject，mutiple，value传入的值为undefined时的单测。
---
🇺🇸 English
- Fix: Add a cypress test when onChangeWithObject, mutiple, and value are set to undefined.

test: [cascader] add cypress for undefined value while mutiple and onChangeWithObject

---

cypress/integration/autoComplete.spec.js
cypress/integration/calendar.spec.js
cypress/integration/cascader.spec.js
cypress/integration/timePicker.spec.js
cypress/integration/tooltip.spec.js
cypress/integration/tree.spec.js
cypress/integration/treeSelect.spec.js
packages/semi-foundation/cascader/foundation.ts
packages/semi-foundation/input/foundation.ts
packages/semi-foundation/input/textareaFoundation.ts
packages/semi-foundation/select/foundation.ts
packages/semi-foundation/tagInput/foundation.ts
packages/semi-foundation/timePicker/foundation.ts
packages/semi-foundation/tree/treeUtil.ts
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/calendar/_story/calendar.stories.js
packages/semi-ui/cascader/index.tsx
packages/semi-ui/input/index.tsx
packages/semi-ui/input/textarea.tsx
packages/semi-ui/select/index.tsx
packages/semi-ui/tagInput/index.tsx
packages/semi-ui/timePicker/TimePicker.tsx
packages/semi-ui/treeSelect/_story/treeSelect.stories.js
packages/semi-ui/treeSelect/index.tsx
yarn.lock

add cypress test to tree, treeSelect, cascader, calendar, etc.

test: add cypress test to tree, treeSelect, cascader, calendar, etc

---

package.json
packages/semi-eslint-plugin/README-zh_CN.md
packages/semi-eslint-plugin/README.md
packages/semi-eslint-plugin/__tests__/index.js
packages/semi-eslint-plugin/src/rules/no-import.ts
packages/semi-foundation/anchor/foundation.ts
packages/semi-foundation/calendar/foundation.ts
packages/semi-foundation/datePicker/foundation.ts
packages/semi-foundation/datePicker/inputFoundation.ts
packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-foundation/form/utils.ts
yarn.lock

Fixes #
🇨🇳 Chinese
- Fix: 修复部分组件 foundation 中包含 React 相关类型定义问题 #923
---
🇺🇸 English
- Fix: Fix some component foundation contains React related type definition problem #923

fix: remove react interface from semi-foundation #923

---

packages/semi-foundation/overflowList/foundation.ts

🇨🇳 Chinese
- Fix: 修复设置collapsible = true时，Tabs滚动到视窗外时TabBar出现箭头
---
🇺🇸 English
- Fix: fix when setting collapsible = true, TabBar appears arrow when Tabs is scrolled out of viewport

fix: fix tabs when vertical scroll and collapse shows extra arrow

---

content/input/autocomplete/index-en-US.md
content/input/autocomplete/index.md
cypress/integration/autoComplete.spec.js
packages/semi-foundation/autoComplete/foundation.ts
packages/semi-ui/autoComplete/_story/CustomTrigger/index.jsx

🇨🇳 Chinese
-  Feat: AutoComplete  A11y 优化键盘适配  #205 
---
🇺🇸 English
- Feat: AutoComplete optimize A11y keyboard adaptation #205

feat(a11y): optimize keyboard event to autoComplete

---

content/show/avatar/index-en-US.md
content/show/avatar/index.md
cypress/integration/avatar.spec.js
packages/semi-foundation/avatar/avatar.scss
packages/semi-foundation/avatar/foundation.ts
packages/semi-foundation/avatar/variables.scss
packages/semi-foundation/checkbox/checkboxFoundation.ts
packages/semi-foundation/radio/radioFoundation.ts
packages/semi-foundation/switch/foundation.ts
packages/semi-ui/avatar/_story/avatar.stories.js
packages/semi-ui/avatar/avatarGroup.tsx
packages/semi-ui/avatar/index.tsx

Feat related to #205 
🇨🇳 Chinese
- feat: Avatar新增 A11y 焦点及键盘适配
---
🇺🇸 English
- feat: Avatar adds A11y focus and keyboard adaptation

feat(a11y): avatar add focus & keyboard event #205

---

packages/semi-foundation/tree/tree.scss
packages/semi-foundation/tree/variables.scss

Fixes #804 
🇨🇳 Chinese
- Fix: 移除Tree中无用的css token
---
🇺🇸 English
- Fix: remove useless css tokens in Tree

fix: [Tree]remove useless token #804 

---

.github/workflows/test.yml
cypress/integration/anchor.spec.js

合并 Jest 和 Cypress 代码覆盖率。
合并后的效果：
- code coverage badge 会展示合并后的代码覆盖率，合并后代码[行覆盖率为 89.7%](https://codecov.io/gh/DouyinFE/semi-design/branch/test-code-coverage/graph/badge.svg)
合并后的问题：
- test 运行时间会达到 ~ 25 min，jest 和 cypress 是并行运行的，不过 cypress 运行时间略长
- cypress 部分 case 运行可能失败（偶尔出现），运行失败会终止代码合并的流程，暂时的解决办法是 skip 掉部分 cypress 用例

Combine Test code coverage

---

packages/semi-foundation/avatar/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: avatar outline syntax style

---

packages/semi-ui/table/Body/index.tsx
packages/semi-ui/table/_story/v2/FixedVirtualizedEmpty.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes #
🇨🇳 Chinese
- Fix: 修复虚拟化 Table 空数据时虚拟列表占位问题 #942
---
🇺🇸 English
- Fix: Fixed the virtual list occupying problem when virtualizing Table empty data

fix: table virtualized empty height

---

content/show/popover/index-en-US.md
content/show/popover/index.md
packages/semi-foundation/tooltip/foundation.ts

🇨🇳 Chinese
- Feat:  returnFocusOnClose 支持trigger hover和focus
---
🇺🇸 English
- Feat: returnFocusOnClose supports trigger hover and focus

feat(tooltip): returnFocusOnClose supports trigger hover and focus

---

packages/semi-ui/tree/treeNode.tsx

…results
Fixes #
🇨🇳 Chinese
- Fix: 修复Tree搜索结果高亮大小写敏感问题
---
🇺🇸 English
- Fix: fix the case-sensitive issue of tree search highlighting result

fix: [tree] Fix the case-sensitive issue of tree search highlighting result

---

content/show/sidesheet/index-en-US.md
content/show/sidesheet/index.md
packages/semi-foundation/sideSheet/sideSheetFoundation.ts
packages/semi-ui/sideSheet/__test__/sideSheet.test.js
packages/semi-ui/sideSheet/_story/__snapshots__/sideSheet.stories.tsx.snap
packages/semi-ui/sideSheet/_story/sideSheet.stories.js
packages/semi-ui/sideSheet/index.tsx

✅ Closes: #916
Fixes #
🇨🇳 Chinese
- Feat: 支持 `SideSheet` 组件的 `lazyRender` 属性
---
🇺🇸 English
- Feat: Support `SideSheet`  -> `lazyRender` attribute

feat: 🎸 Support lazyRender attribute

---

packages/semi-ui/form/_story/form.stories.tsx
packages/semi-ui/form/hoc/withField.tsx
packages/semi-ui/form/interface.ts
packages/semi-ui/upload/_story/upload.stories.tsx

- withField 增加 ref 相关的类型合并，解决如下报错
🇨🇳 Chinese
- Fix: 修复Form Field 组件上使用 ref 时 ts 类型检查报错，提示不存在属性 ref 的问题, #943 
---
🇺🇸 English
- Fix: fix form field component throw error when using with ref, #943

Fix ts error when using ref in Form.Field component

---

packages/semi-illustrations/src/index.ts

🇨🇳 Chinese
- Fix: 修复 @douyinfe/semi-illustrations 按需加载失效的问题, #961 
---
🇺🇸 English
- Fix: Fix the problem that @douyinfe/semi-illustrations failed to load on demand, #961

Fix illustration shaking 

---

packages/semi-foundation/checkbox/checkbox.scss

Fixes # 
🇨🇳 Chinese
- style: 修改 Checkbox选择器inner-pureCardType的优先级
---
🇺🇸 English
- style: modify the priority of inner-pureCardType selector in Checkbox

style: modify the priority of inner-pureCardType selector in Checkbox

---

content/input/datepicker/index-en-US.md
content/input/datepicker/index.md
packages/semi-eslint-plugin/README-zh_CN.md
packages/semi-eslint-plugin/README.md
packages/semi-foundation/datePicker/foundation.ts
packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-ui/datePicker/__test__/datePicker.test.js
packages/semi-ui/datePicker/_story/v2/FixTriggerRender.tsx
packages/semi-ui/datePicker/_story/v2/index.js

先在 1.38.19 修了，从 1.x 搬运过来
🇨🇳 Chinese
- Fix: 修复 DatePicker 在 triggerRender 范围选择场景选择日期交互问题 #676
---
🇺🇸 English
- Fix: Fixed DatePicker in triggerRender range selection scene to select date interaction issue #676

fix: datePicker triggerRender disabled bug #676

---

packages/semi-foundation/dropdown/foundation.ts
packages/semi-foundation/dropdown/menuFoundation.ts
packages/semi-foundation/utils/a11y.ts
packages/semi-ui/tooltip/index.tsx

🇨🇳 Chinese
- Fix: 修复自定义属性data-popupId名称没有小写导致的warning #969 
---
🇺🇸 English
- Fix: fix the warning caused by the name of the custom attribute data-popupId not being all lowercase  #969

fix: make data-popupid lowercase

---

.eslintrc.js
content/input/slider/index-en-US.md
content/input/slider/index.md
cypress/integration/slider.spec.js
packages/semi-foundation/slider/foundation.ts
packages/semi-foundation/slider/slider.scss
packages/semi-foundation/slider/variables.scss
packages/semi-foundation/utils/a11y.ts
packages/semi-ui/slider/_story/slider.stories.js
packages/semi-ui/slider/index.tsx
packages/semi-ui/tooltip/index.tsx

Feat related to #205 
🇨🇳 Chinese
- feat: Slider 新增 A11y 焦点及键盘适配
---
🇺🇸 English
- feat: Slider adds A11y focus and keyboard adaptation

feat(a11y): slider add focus & keyboard event #205

---

content/input/cascader/index.md
packages/semi-ui/cascader/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: Cascader 新增 position API 控制弹层方向
---
🇺🇸 English
- Feat: Cascader adds position API to control the direction of the bullet layer

feat: [cascader] position

---

packages/semi-foundation/typography/typography.scss
packages/semi-ui/typography/_story/typography.stories.js
packages/semi-ui/typography/base.tsx
packages/semi-ui/typography/text.tsx

Reverts DouyinFE/semi-design#973

Revert "fix: [Typography] fix misalignment of the icon and text of the Text c…"

---

packages/semi-animation-react/_story/Animation.react.stories.js
packages/semi-foundation/timePicker/foundation.ts
packages/semi-ui/timePicker/TimePicker.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修正 handle 拼写错误的问题
---
🇺🇸 English
- Fix: fix ...
下次不要这么粗心哦

fix: 修正 handle 拼写错误的问题

---

content/input/select/index-en-US.md
content/input/select/index.md
cypress/integration/select.spec.js
packages/semi-foundation/select/foundation.ts
packages/semi-foundation/select/select.scss
packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/popover/index.tsx
packages/semi-ui/select/__test__/select.test.js
packages/semi-ui/select/index.tsx
packages/semi-ui/select/option.tsx
packages/semi-ui/tag/index.tsx
packages/semi-ui/tag/interface.ts
packages/semi-ui/tooltip/index.tsx

🇨🇳 Chinese
-  Feat: Select 新增 A11y 键盘和焦点适配  #205 
---
🇺🇸 English
- Feat: Select add A11y keyboard and focus adaptation #205

feat(a11y): add keyboard and focus event to select

---

packages/semi-ui/datePicker/__test__/datePicker.test.js

Change the way the preset gets the button in the jest test

test: change get class name

---

packages/semi-ui/empty/index.tsx

Reverts DouyinFE/semi-design#1025

Revert "fix: Empty component darkmode judge, fix #1023"

---

packages/semi-foundation/timePicker/foundation.ts

Fixes #918 
🇨🇳 Chinese
- Fix: 修复 TimePicker 设置为 undefined 是无反应的问题 #918
---
🇺🇸 English
- Fix: Fix TimePicker set to undefined is unresponsive #918

fix: 修复 timepicker 设置为 undefined 是无反应的问题, resolve #918

---

src/components/ComponentOverview/card.jsx

Fixes #
🇨🇳 Chinese
- Fix: Overview组件纵览中卡片点击优化
---
🇺🇸 English
- Fix: Overview Click to jump optimization

docs: overview Click to jump optimization

---

packages/semi-foundation/anchor/anchor.scss
packages/semi-foundation/anchor/variables.scss
packages/semi-ui/anchor/index.tsx
packages/semi-ui/anchor/link.tsx

🇨🇳 Chinese
- Feat: Anchor 新增 A11y 焦点适配 #205 
---
🇺🇸 English
- Feat: Anchor add A11y focus adaptation #205

Anchor add A11y focus adaptation

---

content/show/tag/index-en-US.md
content/show/tag/index.md
packages/semi-ui/tag/_story/tag.stories.js
packages/semi-ui/tag/group.tsx
packages/semi-ui/tag/index.tsx
packages/semi-ui/tag/interface.ts

Fixes #945 
🇨🇳 Chinese
- Fix: 修复 tagGroup closable 关闭后,  数量指示器不变的问题 #945 
---
🇺🇸 English
- Fix: fix the problem that the quantity indicator does not change after tagGroup closable is closed #945

fix(taggroup): 修复 tagGroup closable 关闭后, 数量指示器不变的问题，resolve #945

---

packages/semi-foundation/carousel/foundation.ts
packages/semi-foundation/switch/foundation.ts
packages/semi-ui/carousel/index.tsx
packages/semi-ui/radio/_story/radio.stories.js
packages/semi-ui/rating/__test__/rating.test.js
packages/semi-ui/select/__test__/select.test.js
packages/semi-ui/select/_story/select.stories.js
packages/semi-ui/steps/_story/steps.stories.js
packages/semi-ui/switch/_story/switch.stories.js
packages/semi-ui/switch/_story/switch.stories.tsx
packages/semi-ui/transfer/_story/transfer.stories.js
packages/semi-ui/upload/_story/upload.stories.js

There are **too many** spelling mistakes in the code, please check it carefully. I only fixed part of it.
🇨🇳 Chinese
- Fix: 修复部分拼写错误
---
🇺🇸 English
- Fix: fix part of spelling issues

fix(typo): resolve some spelling mistakes

---

content/show/tag/index-en-US.md
content/show/tag/index.md
packages/semi-ui/tag/_story/tag.stories.js
packages/semi-ui/tag/group.tsx
packages/semi-ui/tag/interface.ts

Fixes #
🇨🇳 Chinese
- Feat: TagGroup增加onTagClose方法
---
🇺🇸 English
- Feat: TagGroup adds onTagClose method

feat: [TagGroup] TagGroup adds onTagClose method

---

packages/semi-animation-react/package.json
packages/semi-next/package.json

🇨🇳 Chinese
- Chore: 移除semi-animation-react 的 peerDependences : react-dom、react、prop-type；移除 semi-next的 dependence: @types/next
---
🇺🇸 English
- Fix: fix ...

Chore animation dep

---

content/input/checkbox/index-en-US.md
content/input/checkbox/index.md
content/input/radio/index-en-US.md
content/input/radio/index.md
packages/semi-foundation/radio/radioFoundation.ts
packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/radio/radio.tsx

Fixes #
🇨🇳 Chinese
- Feat: Checkbox & Radio 增加 type API
---
🇺🇸 English
- Fix: add type API for Checkbox & Radio

feat: add type API for checkbox & radio

---

content/show/tag/index-en-US.md
content/show/tag/index.md

Fixes #
🇨🇳 Chinese
- docs: 优化Tag的color API 的使用例子
---
🇺🇸 English
- docs: Optimizing the usage example of Tag's color API
用户反馈希望可以看到Tag 的color API可用值的所有示例

docs: Optimizing the usage example of color API

---

content/show/popover/index-en-US.md
content/show/popover/index.md

🇨🇳 Chinese
- Docs: Popover 新增 FAQ
---
🇺🇸 English
- Docs: Popover added FAQ

docs: add Faq to popover

---

content/feedback/popconfirm/index-en-US.md
content/feedback/popconfirm/index.md
content/show/dropdown/index-en-US.md
content/show/dropdown/index.md
content/show/popover/index-en-US.md
content/show/popover/index.md

🇨🇳 Chinese
- doc: Popconfirm / Dropdown 新增 FAQ
---
🇺🇸 English
- doc: Popconfirm / Dropdown added FAQ

docs: add Faq to popover/popconfirm/dropdown

---

packages/semi-foundation/table/mixin.scss
packages/semi-foundation/table/rtl.scss
packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...
删除 css 样式简写写法， 防止 scss 编译时 优先级问题仍使用旧 token

fix: table scss remove simple format token

---

packages/semi-foundation/radio/radio.scss
packages/semi-foundation/radio/rtl.scss
packages/semi-ui/radio/_story/radio.stories.js
packages/semi-ui/radio/radio.tsx
packages/semi-ui/radio/radioGroup.tsx

重构了 Radio 的布局，去掉了一些绝对定位，使用 flex 布局代替 0e1c4ff56dfe02d988863ab128fc95ab322afc12
修复了 RadioGroup 第一次渲染时 value 不正确问题 0f3654c8f92e560fc4a5ce59e5b96829260c67eb
🇨🇳 Chinese
- Refactor: 重构了 Radio 的布局，去掉了一些绝对定位，使用 flex 布局代替
- Fix：修复了 RadioGroup 第一次渲染时 value 不正确问题
---
🇺🇸 English
- Refactor: Refactored Radio's layout, removed some absolute positioning, and used flex layout instead
- Fix：Fixed incorrect value of RadioGroup on first render

refactor: radio style

---

packages/semi-foundation/checkbox/checkbox.scss
packages/semi-foundation/checkbox/rtl.scss
packages/semi-ui/checkbox/_story/checkbox.stories.js
packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/checkbox/checkboxGroup.tsx

使用 flex 布局和 gap 替换 Checkbox 中的 margin 布局
🇨🇳 Chinese
- Refactor: 使用 flex 布局和 gap 替换 Checkbox 中的 margin 布局
- Breaking change：使用 CheckboxGroup 时，如果给子级 Checkbox 嵌套一层 div 或者 span 等元素，这时 Checkbox 将不带 margin-bottom。单独给每个 Checkbox 嵌套元素样式上不受影响。
---
🇺🇸 English
- Refactor：Replace margin layout in Checkbox with flex layout and gap
- Breaking change：When using CheckboxGroup, if the child Checkbox is nested with a layer of elements such as div or span, then the Checkbox will not have margin-bottom. Styling each Checkbox nested element individually is unaffected.

Refactor checkbox

---

packages/semi-ui/avatar/index.tsx
packages/semi-ui/checkbox/checkbox.tsx
packages/semi-ui/radio/radio.tsx

给 Checkbox,Radio,Avatar 添加 elementType static 属性，用于 C2D 简单地识别这些组件
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: add elementType to Checkbox,Radio,Avatar

---

packages/semi-foundation/tree/tree.scss
packages/semi-ui/transfer/_story/transfer.stories.js
packages/semi-ui/treeSelect/_story/treeSelect.stories.js

修复 #1073 CheckboxGroup 样式修改影响 TreeSelect 和 Transfer 样式问题
- TreeSelect
修复前 👇🏻
修复后 👇🏻
- Transfer
修复前 👇🏻
修复后 👇🏻
🇨🇳 Chinese
- Fix: 修复 #1073 CheckboxGroup 样式修改影响 TreeSelect 和 Transfer 样式问题
---
🇺🇸 English
- Fix: Fix #1073 CheckboxGroup style modification affects TreeSelect and Transfer styles

fix: TreeSelect and Transfer CheckboxGroup row-gap bug #1073

---

packages/semi-ui/tag/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Tag tagKey 类型定义错误问题
---
🇺🇸 English
- Fix: fixed type error of Tag component tagKey prop

fix: tag tagKey propType

---

packages/semi-foundation/slider/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Slider 在传入部分 steps 值时定位显示不正确的问题, #1043 
---
🇺🇸 English
- Fix: Fixed an issue where Slider was incorrectly positioned when passing in partial steps values, #1043

fix: fix slider #1043

---

packages/semi-ui/tag/group.tsx
packages/semi-ui/tag/interface.ts

Fixes #
🇨🇳 Chinese
- Chore: 将TagGroupProps interface声明移动到interface.ts
---
🇺🇸 English
- Chore: Move the interface TagGroupProps declaration to interface.ts

fix: [tagGroup] Move the inteface declaration to interface.ts

---

packages/semi-ui/transfer/_story/transfer.stories.js

Fixes storybook demo repeat declare

fix: fix the repeat declare problem

---

packages/semi-ui/tabs/_story/Demo.tsx
packages/semi-ui/tabs/interface.ts

Fixes #952 
🇨🇳 Chinese
- Fix: 修复 DefaultTabBar 类型有误 
---
🇺🇸 English
- Fix: fix DefaultTabBar type error

fix: fix defaultTabBar type error

---

packages/semi-foundation/sideSheet/sideSheet.scss

🇨🇳 Chinese
- Style: Sidesheet body 添加 overflow: auto 默认样式，内容超出时不再需要自行通过 props.bodyStyle 添加 overflow相关样式
---
🇺🇸 English
- Style: Sidesheet body Add overflow: auto default style, you no longer need to add overflow related styles through props.bodyStyle when the content exceeds

style: sidesheet body add overflow: auto

---

packages/semi-animation-react/getBabelConfig.js
packages/semi-animation-react/package.json
packages/semi-animation/getBabelConfig.js
packages/semi-animation/package.json
packages/semi-foundation/getBabelConfig.js
packages/semi-foundation/package.json
packages/semi-ui/getBabelConfig.js
packages/semi-ui/package.json

移除 semi-foundation 、semi-ui中的 corejs 依赖
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: remove corejs

---

.vscode/settings.json
content/basic/tokens/index-en-US.md
content/basic/tokens/index.md
scripts/designToken.js
src/components/DesignToken/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

Token table add animation

---

content/show/tag/index-en-US.md
content/show/tag/index.md
packages/semi-foundation/tag/tag.scss
packages/semi-foundation/tag/variables.scss
packages/semi-ui/tag/_story/tag.stories.js
packages/semi-ui/tag/index.tsx
packages/semi-ui/tag/interface.ts

support #89 
🇨🇳 Chinese
- Feat: Tag 新增 shape 选择，可选 square、circle
---
🇺🇸 English
- Feat: Tag adds shape selection, optional square, circle

feat: add shape option to tag

---

content/show/modal/index-en-US.md
content/show/modal/index.md

Fixes #
🇨🇳 Chinese
- Docs: 更新 Modal FAQ
---
🇺🇸 English
- Docs: Update Modal FAQ

docs: update faq in modal

---

packages/semi-foundation/select/foundation.ts

Reverts DouyinFE/semi-design#1126

Revert "fix: [Select] Fixed the problem that Select did not focus on the firs…"

---

packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
packages/semi-foundation/navigation/foundation.ts
packages/semi-foundation/tree/treeUtil.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复dataPicker组件 foundation 中包含 React 相关类型定义问题
- Fix: 修复navigation、tree组件 foundation 在高版本typescript中报错问题
---
🇺🇸 English
- Fix: Fix dataPicker component foundation contains React related type definition problem
- Fix: Fixed navigation and tree component foundation reporting errors in high version typescript

fix: navigation dataPicker and tree component type fix

---

content/input/button/index-en-US.md
content/input/button/index.md
packages/semi-ui/button/buttonGroup.tsx

Fixes # 
🇨🇳 Chinese
- Fix: 修复ButtonGroup未支持style
---
🇺🇸 English
- Fix: fix ButtonGroup does not support style

fix: [Button] Fix ButtonGroup does not support style

---

content/show/image/index-en-US.md
content/show/image/index.md

Fixes #
🇨🇳 Chinese
- Fix: 修改Image 的 fallback 传入值
---
🇺🇸 English
- Fix: modify the fallback incoming value of Image

docs: Modify Image fallback content

---

.storybook/base/preview.tsx
content/other/locale/index-en-US.md
content/other/locale/index.md
packages/semi-ui/locale/source/fr.ts
packages/semi-ui/locale/source/ro.ts
src/templates/scope.js

新增罗马尼亚语（ro）支持
🇨🇳 Chinese
- Feature: LocaleProvider 新增罗马尼亚语（ro）
---
🇺🇸 English
- Feature: LocaleProvider added Romanian(ro)

feat(LocaleProvider): add Romanian(ro)

---

content/input/upload/index-en-US.md
content/input/upload/index.md
packages/semi-ui/upload/_story/upload.stories.js
packages/semi-ui/upload/index.tsx

🇨🇳 Chinese
- Feat: Upload 组件对外暴露 openFileDialog 方法，使用户可以手动打开文件选择窗口。
---
🇺🇸 English
- Feat: the Upload component exposes the openFileDialog method so that the user can manually open the file selection dialog.

Upload open file select dialog manually

---

content/start/changelog/index-en-US.md
content/start/changelog/index.md
packages/semi-foundation/tree/foundation.ts
packages/semi-ui/breadcrumb/item.tsx
packages/semi-ui/dropdown/index.tsx
packages/semi-ui/modal/ModalContent.tsx
packages/semi-ui/navigation/Footer.tsx
packages/semi-ui/navigation/OpenIconTransition.tsx
packages/semi-ui/navigation/SubNav.tsx
packages/semi-ui/table/Body/index.tsx
packages/semi-ui/timeline/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: ts error in high typescipt version && modal focus logic

---

content/show/table/index-en-US.md
content/show/table/index.md
packages/semi-foundation/table/table.scss
packages/semi-ui/table/HeadTable.tsx
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/v2/index.js
packages/semi-ui/table/_story/v2/stickyHeader/index.scss
packages/semi-ui/table/_story/v2/stickyHeader/index.tsx
packages/semi-ui/table/interface.ts
src/demos/StickyHeaderTable/index.tsx
src/templates/postTemplate.js

Table 新增表头  sticky  API
```
<Table sticky={{ top: 100 }} columns={columns} dataSource={dataSource} />
<Table sticky={true} columns={columns} dataSource={dataSource} />
```
🇨🇳 Chinese
- Feat: Table 新增表头  sticky  API
---
🇺🇸 English
- Fix: Table adds header sticky API

feat: Table add sticky API

---

packages/semi-foundation/avatar/avatar.scss
packages/semi-foundation/avatar/variables.scss

Fixes #
🇨🇳 Chinese
- Style:  Avatar 方形头像增加圆角
---
🇺🇸 English
- Style: add rounded corners to square avatars

style: add rounded corners to square Avatar

---

packages/semi-ui/image/image.tsx
packages/semi-ui/image/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 scss 在 ImagePreview 中未导入问题
---
🇺🇸 English
- Fix: fix scss not imported in ImagePreview

fix: [Image] fix scss not imported in ImagePreview

---

packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/_cssAnimation/index.tsx
packages/semi-ui/tabs/TabPane.tsx
packages/semi-ui/tooltip/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 弹层组件 挂载 Childern 两次的问题
---
🇺🇸 English
- Fix: Fix popover mounts content twice bug.

fix: fix popover mount content twice

---

packages/semi-foundation/select/select.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 Select 部分主题 token 不生效的问题
---
🇺🇸 English
- Fix: fix some Select theme token won't take effect bug.

fix: fix select_scss_importOrder for option scss override theme variable

---

cypress/integration/carousel.spec.js
cypress/integration/datePicker.spec.js

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: fix cypress faild

---

packages/semi-foundation/table/foundation.ts
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/__test__/table.test.js
packages/semi-ui/table/_story/v2/Fixed1188/index.tsx
packages/semi-ui/table/_story/v2/index.js

🇨🇳 Chinese
- Fix: 修复 Table defaultFiltertedValue 和 defaultSortOrder 未包含在 onChange 中问题 #1188
---
🇺🇸 English
- Fix: Fix Table defaultFiltertedValue and defaultSortOrder not included in onChange #1188

fix: Table defaultFilterdValue and defaultSortOrder bug #1188

---

content/show/table/index-en-US.md
content/show/table/index.md
packages/semi-ui/table/interface.ts

Fixes #1191
fix table render type definition bug
🇨🇳 Chinese
- Fix: 更新Table组件Columns属性的render的类型
- Doc: 更新Table组件Columns属性的文档
---
🇺🇸 English
- Fix: Update the type of render of the Columns property of the Table component
- Doc: Update the documentation of the Columns property of the Table component

fix: Table render type definition bug

---

cypress/integration/timePicker.spec.js
packages/semi-foundation/datePicker/datePicker.scss
packages/semi-foundation/timePicker/timePicker.scss
packages/semi-ui/timePicker/__test__/timePicker.test.js

1. Timepicker 和 DatePicker 中的 scrollbar 新增适配 firefox 和 ie
2. 更新 Timpicker 的测试用例
1. The scrollbar in Timepicker and DatePicker is added to adapt to firefox and ie
2. Update Timpicker's test case
🇨🇳 Chinese
---
🇺🇸 English

timpicker scrollbar adapt to firefox and ie and update test case

---

packages/semi-foundation/utils/uuid.ts
packages/semi-ui/autoComplete/index.tsx
packages/semi-ui/collapse/collapse-context.tsx
packages/semi-ui/dropdown/index.tsx
packages/semi-ui/modal/confirm.tsx
packages/semi-ui/modal/useModal/HookModal.tsx
packages/semi-ui/navigation/index.tsx
packages/semi-ui/popconfirm/index.tsx
packages/semi-ui/popover/index.tsx
packages/semi-ui/tabs/interface.ts
packages/semi-ui/timePicker/TimePicker.tsx
packages/semi-ui/toast/index.tsx
packages/semi-ui/tooltip/_story/tooltip.stories.jsx
packages/semi-ui/tooltip/index.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

Js2css motion type fix

---

packages/semi-ui/collapsible/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: collapsible onMotionEnd exec fallback

---

packages/semi-foundation/dropdown/dropdown.scss
packages/semi-foundation/popover/popover.scss
packages/semi-foundation/tooltip/tooltip.scss
packages/semi-ui/tooltip/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 
---
🇺🇸 English
- Fix: fix ...

fix: fix popover content autoFocus

---

packages/semi-ui/_cssAnimation/index.tsx
packages/semi-ui/tooltip/index.tsx

- 修复前：https://codesandbox.io/s/react18-semi2-22-7yui5y
- 修复后：https://codesandbox.io/s/react18-semi2-22-2-alpha-1-e752dp
🇨🇳 Chinese
- Fix: 修复 Tooltip、Popover 组件关闭时闪烁问题（影响 v2.22） #1225
---
🇺🇸 English
- Fix: Fix the flickering problem when Tooltip and Popover components are closed (affecting v2.22) #1225

fix: fix tooltip animation in react18 #1225

---

.github/workflows/chromatic.yml
.github/workflows/cypress.yml
.github/workflows/lighthouse.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/test:coverage.yml

Cypress 时有误报，影响飞书通知有效性。本次拆分 workflow 以单独获取 Jest 和 Cypress 测试结果，单独通知：
- 把 jest 测试和 cypress 拆开
- coverage 单独拆出来
- 增加 cypress workflow 通知（轻服务）

Test cypress

---

package.json
packages/semi-ui/tabs/TabPane.tsx
packages/semi-ui/tabs/interface.ts
src/components/Footer/index.jsx
src/components/layout.js
src/components/side-nav.js
src/sitePages/newHome/components/operateButton/operateButton.jsx
src/sitePages/newHome/components/operateButton/operateButton.module.scss
src/styles/doc.scss
src/styles/layout.scss
src/templates/postTemplate.js
yarn.lock

🇨🇳 Chinese
- Docs: 站点新增无障碍（A11y）支持
---
🇺🇸 English
- Docs: Added accessibility (A11y) support to Semi site

A11y site support

---

.gitignore
cypress/integration/image.spec.js
cypress/support/index.js
packages/semi-foundation/image/imageFoundation.ts
packages/semi-foundation/image/previewFooterFoundation.ts
packages/semi-foundation/image/previewImageFoundation.ts
packages/semi-foundation/image/previewInnerFoundation.ts
packages/semi-ui/image/_story/image.stories.jsx
packages/semi-ui/image/image.tsx
packages/semi-ui/image/interface.tsx
packages/semi-ui/image/preview.tsx
packages/semi-ui/image/previewImage.tsx
packages/semi-ui/image/previewInner.tsx

Fixes #1216
🇨🇳 Chinese
- Test：增加 Image 组件的测试用例 #1216 
---
🇺🇸 English
- Test:  Add test case for Image component #1216

test: [Image] add test cases

---

packages/semi-icons/CONTRIBUTING.md

🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

docs: add the contribution steps to semi-icon package

---

packages/semi-ui/select/index.tsx
packages/semi-ui/tooltip/index.tsx

Fixes #763
🇨🇳 Chinese
- Fix: 修复Select和Tooltip组件未处理传入NaN的情况
---
🇺🇸 English
- Fix: fix the case that the Select and Tooltip components did not process the incoming NaN

fix: [Select] [Tooltip] additional handling with isNaN

---

packages/semi-foundation/modal/modalFoundation.ts
packages/semi-foundation/sideSheet/sideSheetFoundation.ts
packages/semi-ui/modal/Modal.tsx
packages/semi-ui/sideSheet/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 SideSheet Modal 挂载子组件时机滞后的问题
---
🇺🇸 English
- Fix: Fixed the lag when SideSheet Modal mounts subcomponents

fix: fix form in sidesheet, form constructor not mount at first trick

---

packages/semi-foundation/tabs/tabs.scss
packages/semi-foundation/tabs/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

[Tabs] Tabs add token

---

packages/semi-foundation/anchor/animation.scss
packages/semi-foundation/autoComplete/animation.scss
packages/semi-foundation/breadcrumb/animation.scss
packages/semi-foundation/button/animation.scss
packages/semi-foundation/carousel/animation.scss
packages/semi-foundation/cascader/animation.scss
packages/semi-foundation/checkbox/animation.scss
packages/semi-foundation/collapsible/animation.scss
packages/semi-foundation/datePicker/animation.scss
packages/semi-foundation/dropdown/animation.scss
packages/semi-foundation/input/animation.scss
packages/semi-foundation/inputNumber/animation.scss
packages/semi-foundation/navigation/animation.scss
packages/semi-foundation/pagination/animation.scss
packages/semi-foundation/radio/animation.scss
packages/semi-foundation/rating/animation.scss
packages/semi-foundation/scrollList/animation.scss
packages/semi-foundation/select/animation.scss
packages/semi-foundation/slider/animation.scss
packages/semi-foundation/steps/animation.scss
packages/semi-foundation/switch/animation.scss
packages/semi-foundation/table/animation.scss
packages/semi-foundation/tabs/animation.scss
packages/semi-foundation/tagInput/animation.scss
packages/semi-foundation/timePicker/utils/animation.scss
packages/semi-foundation/transfer/animation.scss
packages/semi-foundation/tree/animation.scss
packages/semi-theme-default/scss/animation.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: replace animation token with none token

---

gatsby-node.js
packages/semi-foundation/switch/rtl.scss
packages/semi-foundation/switch/switch.scss
packages/semi-foundation/switch/variables.scss

Fixes #
🇨🇳 Chinese
- Style: Switch 组件 Design Token更新，新增 `$spacing-switch_knob-left`；`$motion-switch_unchecked-translateX`更正为更符合语义的 `$spacing-switch_unchecked-translateX
---
🇺🇸 English
- Fix: fix ...

feat: add switch token

---

content/start/changelog/index-en-US.md
content/start/changelog/index.md
packages/semi-foundation/form/form.scss
packages/semi-foundation/form/variables.scss

Form 组件 Design Token 修正
`$spacing-form_label_extra_posBottom-marginTop` ->  `$spacing-form_extra_posBottom-marginTop`
`$spacing-form_label_extra_posMid-marginBottom` -> `$spacing-form_extra_posMid-marginBottom`
`$spacing-form_label_extra_posMid-marginTop` -> `$spacing-form_extra_posMid-marginTop`
并更正相关文档描述，原先名称与 label相关，实际上作用区域与label完全无关。且原先描述完全就是错误的。
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

Fix form token extra

---

content/navigation/navigation/index-en-US.md
content/navigation/navigation/index.md
packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/index.tsx
packages/semi-ui/navigation/nav-context.ts

chore: add docs
Fixes #
🇨🇳 Chinese
- Feat: Navigation 新增 renderWrapper API 用于更便捷地与 react-router、next、gatsby 等路由库结合
---
🇺🇸 English
- Feat: Navigation adds renderWrapper API for easier use of routing libraries such as react-router

feat: nav add react-router support

---

packages/semi-foundation/switch/rtl.scss
packages/semi-foundation/switch/switch.scss
packages/semi-foundation/switch/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: switch add more token

---

packages/semi-ui/timePicker/TimePicker.tsx

🇨🇳 Chinese
- Fix: TimePicker 在生产环境输出 console log
---
🇺🇸 English
- Fix: remove TimePicker console.log

fix(TimePicker): remove console.log

---

packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/tooltip/_story/tooltip.stories.jsx

**before behavior：**
**current behavior after fix:**
🇨🇳 Chinese
- Fix: 修复 Tooltip trigger 被遮挡时弹层也被遮挡问题
---
🇺🇸 English
- Fix: Fix the problem when trigger be blocked the wrapper did not offset

fix: fix the problem when trigger be blocked the wrapper did not offset

---

content/feedback/toast/index-en-US.md
content/feedback/toast/index.md

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

docs: improve toast api usage

---

packages/semi-foundation/tag/tag.scss
packages/semi-foundation/tag/variables.scss

🇨🇳 Chinese
- Style: Tag 关闭按钮增加 hover 态和 active 态颜色
---
🇺🇸 English
- Style: Tag close button add hover and active color

feat: add hover and active color to tag close

---

packages/semi-ui/form/_story/form.stories.tsx
packages/semi-ui/form/hoc/withFormApi.tsx
packages/semi-ui/form/hoc/withFormState.tsx

- 参考 withField的 类型定义，优化 withFormState、withFormApi的类型
之前的写法，无法推断检验组件的props
🇨🇳 Chinese
- Chore：优化 HOC：withFormApi、withFormState 的类型定义
---
🇺🇸 English
- Chore：Improve  type define of  HOC: withFormApi、withFormState

chore: update withFormState、withFormApi type define

---

packages/semi-foundation/button/iconButton.scss
packages/semi-foundation/carousel/carousel.scss
packages/semi-foundation/modal/modal.scss
packages/semi-foundation/notification/notification.scss
packages/semi-foundation/popover/popover.scss
packages/semi-foundation/sideSheet/sideSheet.scss
packages/semi-foundation/skeleton/skeleton.scss
packages/semi-foundation/spin/spin.scss
packages/semi-foundation/tabs/tabs.scss
packages/semi-foundation/toast/toast.scss
packages/semi-foundation/tooltip/tooltip.scss
packages/semi-icons/src/styles/icons.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复部分组件在 React18 下动画闪烁的问题
---
🇺🇸 English
- Fix: Fixed the animation flickering problem of some components under React18

fix: add animation-fill-mode: forwards to all animation

---

packages/semi-foundation/tooltip/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复Tooltip position 为 topLeft 时，自动调整位置不正确问题。
---
🇺🇸 English
- Fix: fix the problem that the automatic adjustment position is incorrect when the Tooltip position is topleft

fix: fix the problem that the automatic adjustment position is incorrect when the position is topleft

---

cypress/integration/table.spec.js
packages/semi-foundation/table/foundation.ts
packages/semi-foundation/table/utils.ts
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/v2/emptyFilters.tsx
packages/semi-ui/table/_story/v2/index.js

Table 筛选器功能支持不传 filters，筛选功能通过受控使用 #1201
🇨🇳 Chinese
- Feat: Table 筛选器功能支持不传 filters，筛选功能通过受控使用 #1201
---
🇺🇸 English
- Feat: Table filter function supports not passing filters, and the filtering function is controlled by filteredValue #1201

feat(table): support empty filters #1201

---

content/input/input/index-en-US.md

Remove duplicate attributes of input component in the documentation Fixes #
🇨🇳 Chinese
- Fix: 删除input 多余的attributes
---
🇺🇸 English
- Fix: Remove duplicate attributes of input component in the documentation

Docs: remove duplicate attributes

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md

Fixes #
🇨🇳 Chinese
- Docs: 文档 API 显示有误内容修改
---
🇺🇸 English
- Docs: Correct the incorrect content displayed in the API in the documentation

docs: fix docs error

---

packages/semi-ui/transfer/index.tsx

Fixes # The internal variable prefixcls of Transfer does not use small camelcase
🇨🇳 Chinese
- Fix: 修复 Transfer 内部变量 prefixcls 未使用小驼峰，与其他组件有差异  
---
🇺🇸 English
- Fix: fix ...

fix: transfer prefixCls spell

---

packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tooltip/index.tsx

Fixes #693
🇨🇳 Chinese
- Fix: 修复 Tabs 滚动折叠有概率失效问题 #693 
---
🇺🇸 English
- Fix: fix Tabs collapsible  has a probability of failure problem  #693

fix: collapse tabs click inner portal sometimes did not work

---

packages/semi-foundation/toast/toast.scss
packages/semi-foundation/toast/variables.scss

Fixes #
🇨🇳 Chinese
- Design Token: Toast 新增 token 用于定制多色样式下不同背景色 `$color-toast_warning_light-icon` `$color-toast_success_light-icon` `$color-toast_info_light-icon` `$color-toast_danger_light-icon`
---
🇺🇸 English
- Design Token: Toast adds a new token for customizing different background colors in multi-color styles `$color-toast_warning_light-icon` `$color-toast_success_light-icon` `$color-toast_info_light-icon` `$color-toast_danger_light-icon`

feat: toast new token

---

packages/semi-foundation/dropdown/dropdown.scss
packages/semi-ui/dropdown/_story/C2D/index.tsx
packages/semi-ui/dropdown/_story/dropdown.stories.jsx
packages/semi-ui/dropdown/dropdownItem.tsx

新增 showTick 和 hover，C2D 单独绘制f Dropdown.Item 时使用。
Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

other: Dropdown item 新增 showTick 和 hover 属性

---

packages/semi-ui/form/__test__/field.test.js
packages/semi-ui/form/hoc/withField.tsx

Fixes #1375
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: [Form] validate race condition problem

---

packages/semi-ui/form/_story/Validate/validateDemo.jsx
packages/semi-ui/form/_story/form.stories.jsx
packages/semi-ui/form/hoc/withField.tsx
src/sitePages/newHome/components/operateButton/operateButton.jsx
src/templates/postTemplate.js

src中的修改可忽略，顺带修复一些文档站点的warning
🇨🇳 Chinese
- Fix:  修复Form Field 级别校验，使用 props.validate 时存在竞态异步，后执行的校验会被前执行的校验覆盖的问题, #1375 
---
🇺🇸 English
- Fix: Fix Form Field level validation. When using props.validate, there is a race condition asynchronous, and the validation performed later will be overwritten by the validation performed before, #1375
Demo
```
class RaceAsyncDemo extends React.Component {
constructor() {
super();
this.asyncValidate = this.asyncValidate.bind(this);
}
asyncValidate(val, values) {
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
let time = 1000; 
if (val === 'semi') {
time = 4000;
} 
return sleep(time).then(() => {
if (!val) {
return …
```

Fix race async validator when using field props.validate

---

content/input/upload/index-en-US.md
content/input/upload/index.md
src/sitePages/newHome/components/operateButton/operateButton.jsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: change_upload_demoURL

---

content/input/taginput/index-en-US.md
content/input/taginput/index.md
packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 TagInput showContentTooltip 类型不完整问题
---
🇺🇸 English
- Fix:fix the incomplete type of TagInput showContentTooltip

chore: improve taginput doc

---

packages/semi-ui/resizeObserver/index.tsx

Fixes #1393 
🇨🇳 Chinese
- Fix: 修复 React18 严格模式下 overflowList 没有正常显示问题
---
🇺🇸 English
- Fix: fix the problem that overflowList does not display normally in React18 strict mode

fix: under react18 and strictmode new overflowList do not visibility

---

cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-ui/datePicker/_story/v2/FixRangePanelShift.jsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/monthsGrid.tsx

Fixes #1221 
面板漂移行为出现在 v2.11.0 版本后 
影响此行为的 commit https://github.com/DouyinFE/semi-design/commit/c5d42ebbf4de7b8da39cb685724431b486d5eb67
🇨🇳 Chinese
- Fix: 修复 DatePicker 选择时间范围时面板移动问题 #1221
---
🇺🇸 English
- Fix: fixed DatePicker panel shifting bug when selecting date range #1221

fix: [DatePicker] range type ui shift bug #1221

---

content/other/locale/index-en-US.md
content/other/locale/index.md
yarn.lock

Docs: 新增多语言 demo：Transfer、Image、Form
🇨🇳 Chinese
- Docs: 新增多语言 demo：Transfer、Image、Form
---
🇺🇸 English
- Docs: add i18n demo：Transfer、Image、Form

feat: add i18n demo

---

content/input/form/index-en-US.md
content/input/form/index.md
packages/semi-foundation/form/form.scss
packages/semi-ui/form/_story/InputGroup/groupProps.jsx
packages/semi-ui/form/_story/Layout/layoutDemo.jsx
packages/semi-ui/form/_story/form.stories.jsx
packages/semi-ui/form/group.tsx

🇨🇳 Chinese
- Feat: Form.InputGroup 支持配置 extraText, extraTextPosition，对齐 Field Component #1313 
- Docs: 优化 Form 组件英文文档描述 及 Demo 
---
🇺🇸 English
- Feat: Form.InputGroup support extraText, extraTextPosition, #1313
- - Docs: Improve Form english document

Form.InputGroup support extraText, extraTextPosition

---

packages/semi-foundation/slider/slider.scss
packages/semi-foundation/slider/variables.scss
packages/semi-ui/slider/index.tsx

Fixes #
🇨🇳 Chinese
- Design Token: Slider 新增 `$spacing-slider_handle-translateY` `$spacing-slider_vertical_handle-translateX` `$spacing-slider_dot-translateX` `$spacing-slider_vertical_dot-translateY` Token，用于控制水平和垂直状态 把手和数值刻度线的水平和垂直偏移
---
🇺🇸 English
- Design Token: Slider adds `$spacing-slider_handle-translateY` `$spacing-slider_vertical_handle-translateX` `$spacing-slider_dot-translateX` `$spacing-slider_vertical_dot-translateY` Token, which is used to control the horizontal and vertical state handles and value scale lines horizontal and vertical offset

feat: (slider) add some tokens

---

cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/foundation.ts
packages/semi-ui/datePicker/_story/v2/InsetInputControlled.tsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/dateInput.tsx
packages/semi-ui/datePicker/datePicker.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 DatePicker 内嵌输入框受控模式下 dateTimeRange 回显错误问题 #1413
---
🇺🇸 English
- Fix: Fix the dateTimeRange input display error of DatePicker component in insetInput controlled mode #1413

fix: [DatePicker] insetInput show date bug in controlled mode #1413

---

content/other/locale/index.md
packages/semi-ui/locale/source/ar.ts
packages/semi-ui/locale/source/de.ts
packages/semi-ui/locale/source/en_GB.ts
packages/semi-ui/locale/source/es.ts
packages/semi-ui/locale/source/fr.ts
packages/semi-ui/locale/source/it.ts
packages/semi-ui/locale/source/ja_JP.ts
packages/semi-ui/locale/source/nl_NL.ts
packages/semi-ui/locale/source/pt_BR.ts
packages/semi-ui/locale/source/ro.ts
packages/semi-ui/locale/source/ru_RU.ts
packages/semi-ui/locale/source/th_TH.ts
packages/semi-ui/locale/source/tr_TR.ts
packages/semi-ui/locale/source/vi_VN.ts
packages/semi-ui/locale/source/zh_CN.ts

Reverts DouyinFE/semi-design#1416

Revert "WIP: fix i18n translate"

---

cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/monthsGridFoundation.ts
packages/semi-ui/datePicker/_story/v2/FixMultiplePanelShift.tsx
packages/semi-ui/datePicker/_story/v2/index.js

Fixes #1422
🇨🇳 Chinese
- Fix: 修复 DatePicker 多选面板移动问题 #1422
---
🇺🇸 English
- Fix: Fix DatePicker panel moving in multiple mode #1422

fix: [DatePicker] multiple selected panel ui shift #1422

---

content/feedback/popconfirm/index-en-US.md
content/feedback/popconfirm/index.md
cypress/integration/popconfirm.spec.js
packages/semi-foundation/popconfirm/popconfirmFoundation.ts
packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/popconfirm/_story/popconfirm.stories.jsx
packages/semi-ui/popconfirm/index.tsx
packages/semi-ui/popover/index.tsx
packages/semi-ui/tooltip/index.tsx

close 掉之前没有完成的 Feat #205
🇨🇳 Chinese
- Feat: Popconfirm 支持 A11y 键盘和焦点 #205
---
🇺🇸 English
- Feat: Popconfirm supports A11y keyboard and focus #205

feat(a11y): Popconfirm support focus and keyboard

---

packages/semi-foundation/select/select.scss
packages/semi-foundation/select/variables.scss
packages/semi-foundation/treeSelect/treeSelect.scss
packages/semi-foundation/treeSelect/variables.scss

Fixes #
🇨🇳 Chinese
- design token: select 新增 `$color-select-bg-focus`
- fix: treeSelect 修复部分场景下，hover 时 border 颜色异常的问题
---
🇺🇸 English
- design token: select Add `$color-select-bg-focus`
- fix: treeSelect fixes the problem that the border color is abnormal when hovering in some scenes

fix: fix treeselect hover border && select add bg-focus token

---

packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/tooltip/_story/tooltip.stories.jsx

Fixes #1449 
🇨🇳 Chinese
- Fix: 修复 Tooltip 在右侧被遮挡时浮层漂移到视口左侧
---
🇺🇸 English
- Fix: fix when the Tooltip is blocked on the right side, the floating layer drifts to the left side of the viewport

fix: When the tooltip is blocked on the right side, the floating layer floats to the left side of the viewport

---

packages/semi-ui/dropdown/_story/dropdown.stories.jsx
packages/semi-ui/dropdown/dropdownItem.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Dropdown showTick 失效问题（影响范围 2.27.1 ~ 2.30.0） #1457
---
🇺🇸 English
- Fix: fixed showTick bug in Dropdown(the bug affects 2.27.1 ~ 2.30.0) #1457

fix(dropdown): fixed Dropdown showTick bug #1457

---

packages/semi-ui/tag/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Tooltip 下 Tag 无法通过键盘聚集问题
---
🇺🇸 English
- Fix: fix the problem that Tags cannot be gathered through the keyboard under Tooltip

fix: tabindex is transparently passed to tag in any case

---

packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/nav-context.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Nav tooltip 相关延迟 props 不生效的问题 #1454 
---
🇺🇸 English
- Fix: Fix the problem that the delay props related to Nav tooltip does not take effect #1454

fix: fix nav tooltip delay

---

packages/semi-eslint-plugin/__tests__/index.js
packages/semi-eslint-plugin/src/rules/no-import.ts
packages/semi-foundation/table/utils.ts
packages/semi-ui/_utils/index.tsx
packages/semi-ui/table/ResizableTable.tsx
packages/semi-ui/table/_story/v2/fixedResizableWithForm.tsx
packages/semi-ui/table/_story/v2/index.js
packages/semi-ui/table/utils.ts

Fixes #1506 
顺便修改了一下 eslint-plugin-semi-design 在 story 引入 @douyinfe/semi-ui 时报引用错误问题
🇨🇳 Chinese
- Fix: 修复 resizable Table 与 form 同时使用在 dev 环境下报错问题 #1506
---
🇺🇸 English
- Fix: Fix the problem of using resizable Table and form at the same time in the dev environment to report an error #1506

fix: fixed resizable table with form threw error in dev #1506

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
cypress/integration/treeSelect.spec.js
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx
yarn.lock

Fixes # 
🇨🇳 Chinese
- Feat: TreeSelect 新增 clickTriggerToHide 参数支持设置在面板打开状态下，点击 Trigger 部分是否触发面板关闭
---
🇺🇸 English
- Fix: TreeSelect has added a clickTriggerToHide parameter to support setting whether to click the Trigger part to trigger the panel to close when the panel is open
clickTriggerToHide 的默认值为 true 是为了保持效果和历史版一致
需要注意的是，因为历史原因，和 Select 组件中同样功能的参数 clickToHide 默认值不同，在下一个大版本中，需要注意这块的功能的统一性。同时在参数命名上，使用 clickTriggerToHide，和 clickContentToHide 在描述上更准确

feat: [TreeSelect] add clicktriggertohide API

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx

Fixes #
🇨🇳 Chinese
- Docs: 优化 TreeSelect 中文档示例
---
🇺🇸 English
- Fix: fix ...

docs: [TreeSelect] custom trigger example optimization

---

packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss
packages/semi-ui/table/_story/v2/index.js
packages/semi-ui/table/_story/v2/zebra.tsx

related to #1418 
🇨🇳 Chinese
- Fix: 修复 Table 设置斑马纹无效问题（影响范围：v2.29 - 2.32）
---
🇺🇸 English
- Fix: fix the problem that the table setting zebra pattern is invalid(Range of influence: v2.29 - 2.32)

fix: setting zebra pattern is invalid

---

packages/semi-foundation/table/utils.ts
packages/semi-ui/table/Table.tsx

问题原因：ResizableTable.jsx withResizeWidth 存在 deep clone，深克隆 ReactNode 会报错
解决办法：
- 移除掉 table foundation 中的 cloneDeep，column 的深克隆统一使用 packages/semi-ui/_utils/index.tsx 下的  cloneDeep
- 移除掉 table foundation 中的 mergeColumns，防止以后再使用此函数深克隆，替换为 packages/semi-ui/table/utils.ts 下的 mergeColumns
- withResizeWidth 中的深克隆改为浅克隆
🇨🇳 Chinese
- Fix: 修复 resizable Table 在 dev 环境下报错问题 [#1506](https://github.com/DouyinFE/semi-design/issues/1506)
---
🇺🇸 English
- Fix: Fix resizable Table error reporting in dev environment [#1506](https://github.com/DouyinFE/semi-design/issues/1506)

fix: fixed resizable Table bug #1506

---

packages/semi-ui/modal/Modal.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Modal getPopupContainer 执行时机不正确的问题，预期为 Modal 打开时执行
---
🇺🇸 English
- Fix: Fix the problem that the execution timing of Modal getPopupContainer is incorrect, it is expected to be executed when Modal is opened

fix: modal popupContainer exec time

---

packages/semi-ui/typography/title.tsx

Fixes #1545
🇨🇳 Chinese
- Fix: 修复 Typography 的 copyable 类型错误
---
🇺🇸 English
- Fix: fix Typography copyable type

fix: Typography copyable type

---

packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/_story/cascader.stories.jsx
packages/semi-ui/cascader/index.tsx
yarn.lock

Fixes #
🇨🇳 Chinese
- feat：级联选择框新增 focus/blur 方法 #566 
---
🇺🇸 English
- feat: Cascader add  focus blur methods #566

feat: cascader add focus/blur methods

---

package.json
packages/semi-ui/table/Body/BaseRow.tsx
packages/semi-ui/table/_story/v2/Fixed1556/index.tsx
packages/semi-ui/table/_story/v2/index.js
yarn.lock

Fixes #1556
🇨🇳 Chinese
- Fix: 修复  Table hideExpandedColumn 为 false 时 indent 问题 #1556
---
🇺🇸 English
- Fix: fixed Table indent bug when hideExpandedColumn is false #1556

fix: Table indent bug when hideExpandedColumn is false #1556

---

packages/semi-ui/form/_story/InputGroup/groupProps.jsx
packages/semi-ui/form/group.tsx

🇨🇳 Chinese
- Fix: 修复InputGroup不受Form disabled控制的bug
---
🇺🇸 English
- Fix: fix the bug that InputGroup is not controlled by Form disabled

fix: fix input group is not controlled by form disabled

---

packages/semi-ui/typography/_story/typography.stories.jsx
packages/semi-ui/typography/util.tsx

Fixes #1577 
🇨🇳 Chinese
- Fix: 修复 Typography 在设置 white-space 为 nowrap 时截断出错问题 #1577 
---
🇺🇸 English
- Fix: fix Typography truncation error when setting white-space to nowrap #1577

Fix/typo: fix Typography truncation error when setting white-space to nowrap

---

packages/semi-ui/table/Table.tsx

Fixes #1466
已在 Next 项目验证 OK
🇨🇳 Chinese
- Fix: 修复 Table SSR 时未展示数据问题 #1466
---
🇺🇸 English
- Fix: fixed Table SSR dataSource is empty bug #1466

fix: fixed Table SSR dataSource is empty bug #1466

---

src/sitePages/newHome/components/theme/theme.js

Fixes #
🇨🇳 Chinese
- Fix: 修复主页中不同主题背景色错误问题
---
🇺🇸 English
- Fix: fix the wrong background color of different themes on the homepage

fix: Fix the wrong background color of different themes on the homepage

---

cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/foundation.ts
packages/semi-ui/datePicker/_story/v2/FixDisabledDate.tsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/datePicker.tsx

Fixes #1592
问题原因：错误使用了 stateValue，未选择结束时， stateValue 为空
更新后：与上次临时选中的日期进行比较
🇨🇳 Chinese
- Fix: 修复 DatePicker disabeldDate 无法选择禁用边界日期问题 #1592 
---
🇺🇸 English
- Fix: Fix DatePicker disabeldDate cannot select disabled border dates #1592

fix: fix datePicker disabledDate bug #1592

---

packages/semi-foundation/slider/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复部分情境下 垂直 slider 点击跳转值错误的问题
---
🇺🇸 English
- Fix: Fix the problem that the vertical slider click jump value is wrong in some situations

fix: fix vertical slider click rail always jump to 1 in some sitiuation 

---

content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-ui/select/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: Select 新增 search 方法
- Fix: 修复 handleInputChange 参数类型与 Input onChange 参数类型不匹配问题
---
🇺🇸 English
- Feat: Select add new ref method search 
- Fix: fix the problem that the parameter type of handleInputChange does not match the parameter type of Input onChange

feat: add search ref method on select

---

packages/semi-foundation/datePicker/datePicker.scss

Fixes #1561
Chromatic 测试了一下，没问题
🇨🇳 Chinese
- Fix: 移除 DatePicker 最外层 vertical-align top 样式 #1561
---
🇺🇸 English
- Fix: remove the outermost vertical-align top style of DatePicker #1561

style: fixed DatePicker vertical-align bug #1561

---

packages/semi-foundation/table/table.scss
packages/semi-ui/table/_story/v2/FixedColumnAlign/index.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes #1599
- 修复前
- 修复后
🇨🇳 Chinese
- Fix: 修复 Table  表头 column align 对齐 bug（v2.34 ~ 2.35 受影响） #1599
---
🇺🇸 English
- Fix: fix Table header column align bug（v2.34 ~ 2.35 affected） #1599

fix: Table column align bug #1599

---

content/input/slider/index-en-US.md
content/input/slider/index.md

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

docs(Slider): improve docs

---

.github/workflows/cypress.yml
.github/workflows/lighthouse.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test-coverage.yml
.github/workflows/test.yml
package.json

lerna 刚发布了 7.0 latest，移除了 lerna bootstrap 命令，我们可以后面再升级 lerna，先用 lerna 6
Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: udpate ci lerna version

---

packages/semi-ui/pagination/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: [Pagination] fix error x-semi-props for newxText

---

packages/semi-ui/image/preview.tsx

Fixes #1657 
🇨🇳 Chinese
- Fix: 修复 ImagePreview 中 className 不生效问题 #1657
---
🇺🇸 English
- Fix: Fix the problem that className does not take effect in ImagePreview #1657

fix: Fix the problem that className does not take effect in ImagePreview

---

content/show/badge/index-en-US.md
content/show/badge/index.md
packages/semi-foundation/badge/badge.scss
packages/semi-foundation/badge/variables.scss
packages/semi-ui/badge/_story/badge.stories.jsx
packages/semi-ui/badge/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: Badge 新增 success 类型
---
🇺🇸 English
- Fix: Badge add succss type

feat: Badge add succss type

---

packages/semi-ui/toast/useToast/index.tsx

…ponent reRender
Fixes #
🇨🇳 Chinese
- Fix: 修复 toast useToast 返回值在用户函数 re render 后失效的问题
---
🇺🇸 English
- Fix: fix toast useToast return value no effect when user function component re render.

fix: fix toast useToast return value no effect when user function com

---

packages/semi-ui/input/textarea.tsx

Fixes #1689
🇨🇳 Chinese
- Fix: 修复 Textarea 更新 placeholder 时不会触发重新计算高度
---
🇺🇸 English
- Fix: Fix the issue where the Textarea does not resize when the placeholder changes

fix: fix textarea does not resize when placeholder changes

---

lerna.json
packages/semi-animation-react/package.json
packages/semi-animation-styled/package.json
packages/semi-animation/package.json
packages/semi-eslint-plugin/package.json
packages/semi-foundation/package.json
packages/semi-foundation/pagination/foundation.ts
packages/semi-icons/package.json
packages/semi-illustrations/package.json
packages/semi-next/package.json
packages/semi-rspack/package.json
packages/semi-scss-compile/package.json
packages/semi-theme-default/package.json
packages/semi-ui/package.json
packages/semi-ui/pagination/_story/pagination.stories.jsx
packages/semi-ui/pagination/index.tsx
packages/semi-webpack/package.json

根据用户反馈，在 total 为 亿级别时，small pagination有明显卡顿，对代码不合理之处做改进，数据对比详见
https://bytedance.feishu.cn/docx/OumodNXtWoVYfXxHRBtcB0s2nxd
主要将 renderSmallPage中的  Array.from操作由每次重新计算降为按需计算
🇨🇳 Chinese
- Perf:  优化 Pagination small size 在亿级别数据时展示卡顿的问题
---
🇺🇸 English
- Fix: fix ...

perf: improve pagination small size render

---

packages/semi-foundation/form/foundation.ts
packages/semi-foundation/form/interface.ts
packages/semi-ui/form/baseForm.tsx
packages/semi-ui/form/interface.ts

Fixes #
🇨🇳 Chinese
- Feat: Form onSubmit、onSubmitFail 增加 event 参数透出, #1728 
---
🇺🇸 English
- Feat: Form onSubmit、onSubmitFail add event params, #1728

Feat on submit add event

---

packages/semi-foundation/image/variables.scss
packages/semi-foundation/skeleton/variables.scss

Fixes #1719 
🇨🇳 Chinese
- Style: Skeleton 的默认圆角从 4px 修改为 --semi-border-radius-small(3px)
---
🇺🇸 English
- Fix: Skeleton's default rounded corners changed from 4px to --semi-border-radius-small(3px)

style: change skeleton radius form 4px to --semi-border-radius-small

---

cypress/e2e/image.spec.js
packages/semi-ui/image/_story/image.stories.jsx
packages/semi-ui/image/interface.tsx
packages/semi-ui/image/preview.tsx
packages/semi-ui/image/previewInner.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ImagePreview 中 defaultCurrentIndex 错误的类型定义
---
🇺🇸 English
- Fix: fix wrong type definition for defaultCurrentIndex in ImagePreview

fix: fix error type define for defaultCurrentIndex in ImagePreview

---

content/show/table/index-en-US.md
content/show/table/index.md
packages/semi-ui/table/ResizableHeaderCell.tsx
packages/semi-ui/table/TableHeader.tsx
packages/semi-ui/table/TableHeaderRow.tsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/ColumnResize/index.tsx
packages/semi-ui/table/_story/v2/index.js
packages/semi-ui/table/interface.ts
yarn.lock

支持 resize 以实现，resizable Table 的固定列不可以拖拽。
🇨🇳 Chinese
- Feat: Table column 支持设置 resize 属性 #1762 #1650
---
🇺🇸 English
- Feat：Table column support resize prop #1762 #1650

feat：Table column support resize prop

---

packages/semi-ui/collapse/item.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 collapse aria_owns 在 SSR 下 Client 和 Server 属性不匹配的问题 #1763
---
🇺🇸 English
- Fix: fix collapse aria-owns in SSR not match with server result. #1763

fix:fix collapse aria_owns in SSR not match

---

content/show/dropdown/index.md
content/show/popover/index.md
content/show/tooltip/index.md
packages/semi-foundation/tooltip/constants.ts
packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/tooltip/_story/tooltip.stories.jsx
packages/semi-ui/tooltip/index.tsx

🇨🇳 Chinese
- Feat: Tooltip、Popover、Dropdown增加 trigger=contextMenu 右键点击触发 #396 
---
🇺🇸 English
- Feat: Tooltip、Popover、Dropdown add trigger=contextMenu support right click to show #396

Tooltip Popover Dropdown add trigger=contextMenu

---

content/show/table/index.md

Fixes #
🇨🇳 Chinese
- Docs: 优化展开按钮部分中文描述
---
🇺🇸 English
- Docs: Optimize the Chinese description of the expand button

docs: Optimize the Chinese description of the expand button

---

packages/semi-foundation/navigation/subNavFoundation.ts
packages/semi-foundation/tooltip/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 弹层组件 和 Navigation 在部分场景内存泄漏的问题。
---
🇺🇸 English
- Fix: Fix the problem of memory leaks in some scenes of pop-up layer components and Navigation

[fix] fix: cleartimeout memory leak

---

packages/semi-foundation/image/previewInnerFoundation.ts

Fixes #1783
🇨🇳 Chinese
- Fix: 修复 ImagePreview 下载文件名
---
🇺🇸 English
- Fix: fix download file name of ImagePreview

fix: fix download name of image component

---

content/input/cascader/index-en-US.md
content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-ui/select/_story/select.stories.jsx

Fix a common typo across docs and demos

docs: fix a typo

---

packages/semi-ui/table/Body/BaseRow.tsx

Fixes 
🇨🇳 Chinese
- Fix: 修复 Table baseRow onMouseLeave 报错问题
---
🇺🇸 English
- Fix: Fix Table baseRow onMouseLeave error

fix: fixed Table onMouseLeave callback bug

---

cypress/e2e/table.spec.js
packages/semi-ui/table/ResizableTable.tsx
packages/semi-ui/table/_story/ResizableTable/index.jsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 resizable Table onHeaderCell 失效问题 #1796
---
🇺🇸 English
- Fix: fixed resizable table onHeaderCell bug #1796

fix: fixed resizable table onHeaderCell bug #1796

---

packages/semi-foundation/tree/foundation.ts
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/tree/interface.ts
packages/semi-ui/treeSelect/index.tsx

…/TreeSelect
Fixes #
🇨🇳 Chinese
- Chore: 修改 Tree/ TreeSelect 中的 onSelect 的参数名称，防止歧义
---
🇺🇸 English
- Chore: fix ...

Chore: [Tree][TreeSelect] Modify the parameter name of onSelect in Tree/ TreeSelect to prevent ambiguity

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md
packages/semi-ui/cascader/_story/cascader.stories.jsx

Fixes #
🇨🇳 Chinese
- docs: 修改 Cascader 的 filterRender 示例中错误的函数调用
---
🇺🇸 English
- Fix: fix ...

docs: Modify the wrong parameter call

---

content/show/carousel/index-en-US.md
content/show/carousel/index.md
packages/semi-ui/carousel/_story/carousel.stories.jsx

Fixes #1813 
🇨🇳 Chinese
- Chore: fix wrong spelling in Carousel #1813 
---
🇺🇸 English
- Fix: fix ...

chore: fix wrong spelling in Carousel

---

packages/semi-foundation/dropdown/constants.ts
packages/semi-foundation/popover/constants.ts

Fixes #1819 
🇨🇳 Chinese
- Fix: ![image](https://github.com/DouyinFE/semi-design/assets/33797740/b801ddcf-e52f-4897-8fa5-33031fb70413)
---
🇺🇸 English
- Fix: fix ...

fix: popover trigger set

---

packages/semi-foundation/popconfirm/popconfirm.scss
packages/semi-ui/popconfirm/index.tsx

- before
- after
🇨🇳 Chinese
- Style: Popconfirm 当 icon 为null时，body 元素不再保留 marginLeft样式
---
🇺🇸 English
- Style: Popconfirm body remove marginLeft when icon is null

style: popconfirm icon=null, remove marginLeft

---

packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss
packages/semi-ui/table/ColumnFilter.tsx

Fixes #
🇨🇳 Chinese
- Style: Table filter dropdown增加默认 maxHeight： 290px. #1647 
---
🇺🇸 English
- Style：Table filter dropdown add default maxHeight：300px. #1647

style: table dropdown add maxheight, close #1647

---

packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/tooltip/_story/tooltip.stories.jsx

对从原方向转为反向的规则进行调整
原策略 在以下条件下进行反向
1. 视口上下空间不足 且 容器上空间❌下空间✅
2. 视口上空间❌下空间✅ 且 容器上下空间不足
3. 视口上空间❌下空间✅ 且 容器上空间❌下空间✅
新策略 在以下条件下进行反向
1. 视口上下空间不足 且 容器上空间❌下空间✅
2. 视口上空间❌下空间✅
即更新后，在视口原方向空间不足，反向空间足够的情况下，无需考虑容器情况，统一转为反向。
🇨🇳 Chinese
- Fix: 更新 tooltip 自动调整位置策略，在视口原方向空间不足，反向空间足够的情况下，统一转为反向。
---
🇺🇸 English
- Fix: Update the tooltip to automatically adjust the position strategy. When the space in the original direction of the viewport is insufficient and the space in the reverse direction is sufficient, it will be uniformly converted to the reverse direction.

fix: modify the tooltip automatic adjustment position principle

---

packages/semi-foundation/steps/bacisSteps.scss
packages/semi-foundation/steps/fillSteps.scss
packages/semi-ui/steps/basicStep.tsx
packages/semi-ui/steps/fillStep.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Step 部分伪类样式不正确的问题
---
🇺🇸 English
- Fix: Fixed the issue of incorrect styles of some Step pseudo-classes

fix: fix steps some hover active style

---

packages/semi-foundation/datePicker/datePicker.scss
packages/semi-foundation/datePicker/variables.scss

Fixes #
🇨🇳 Chinese
- Token: Datepicker 新增 $color-datepicker_range_trigger-border-focus
---
🇺🇸 English
- Token: Datepicker Add $color-datepicker_range_trigger-border-focus

feat: datepicker add token

---

packages/semi-foundation/anchor/anchor.scss
packages/semi-foundation/anchor/variables.scss

Fixes #
🇨🇳 Chinese
- Token: Anchor 新增 $color-anchor_title_active-text-hover $color-anchor_title-bg $color-anchor_title_active-bg
---
🇺🇸 English
- Token: Anchor add $color-anchor_title_active-text-hover $color-anchor_title-bg $color-anchor_title_active-bg

feat: anchor add token

---

gatsby-node.js
src/components/layout.js
src/components/useIde.js
src/styles/ide.scss
src/templates/postTemplate.js

Fixes #
🇨🇳 Chinese
- Feature：增加ide插件相关功能
---
🇺🇸 English
-Feature: add ide related functions

feat: ide site

---

packages/semi-foundation/table/utils.ts
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/FixedResizableRowSelection/index.jsx
packages/semi-ui/table/_story/v2/index.js

Fixes #
修复一个低级错误，数组拓展写成了 {....}，应该写成 [...]。
🇨🇳 Chinese
- Fix: 修复 resizable Table 宽度在行选择时错误设置为初始值问题（影响 v2.32~v2.44）
---
🇺🇸 English
- Fix: resizable Table width reset to initial bug（Affected v2.32~v2.44）

fix: resizable Table width reset to initial bug

---

src/components/layout.js
src/components/useIde.js
src/templates/postTemplate.js

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: ide ssr dom wrong

---

cypress/e2e/inputNumber.spec.js
packages/semi-ui/inputNumber/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 InputNumber 在受控模式且聚焦时 formatter 错误问题 #1772
---
🇺🇸 English
- Fix: Fix formatter error issue when InputNumber is in controlled mode and focused #1772

fix: fixed InputNumber formatter bug related to #1772

---

packages/semi-ui/popconfirm/_story/ShowCloseIcon/index.jsx
packages/semi-ui/popconfirm/_story/popconfirm.stories.jsx
packages/semi-ui/popconfirm/index.tsx

Close #1898 
Fixes #
🇨🇳 Chinese
- Feature: Popconfirm增加api：showCloseIcon 控制关闭图标展示
---
🇺🇸 English
- Feature: add popconfirm api showCloseIcon

Feat: popconfirm showCloseIcon 

---

packages/semi-theme-default/scss/global.scss

Fixes #
🇨🇳 Chinese
- Design Token: 新增 `--semi-color-data-0` 系列 css variables
---
🇺🇸 English
- Design Token: Add `--semi-color-data-0` series css variables

feat: add extra token

---

packages/semi-foundation/typography/typography.scss
packages/semi-foundation/typography/variables.scss

Fixes #
🇨🇳 Chinese
- Design Token: Typography 新增 $font-typography_normalText-regular-fontWeight $font-typography_smallText-regular-fontWeight $font-typography_normalParagraph-regular-fontWeight $font-typography_smallParagraph-regular-fontWeight
---
🇺🇸 English
- Design Token: Typography add $font-typography_normalText-regular-fontWeight $font-typography_smallText-regular-fontWeight $font-typography_normalParagraph-regular-fontWeight $font-typography_smallParagraph-regular-fontWeight

feat: add smallText and paragraph fontWeight token

---

content/show/avatar/index-en-US.md
content/show/avatar/index.md
packages/semi-foundation/avatar/foundation.ts
packages/semi-ui/avatar/__test__/avatar.test.js
packages/semi-ui/avatar/_story/avatar.stories.jsx
packages/semi-ui/avatar/index.tsx
packages/semi-ui/avatar/interface.ts

相关 issue: https://github.com/DouyinFE/semi-design/issues/1917  
对于字符型的头像，当字符串较长时，字体大小可以根据头像宽度自动调整。
🇨🇳 Chinese
- Feat: 字符串类型头像，字符长度可根据头像宽度自动调整 #1917 
---
🇺🇸 English
- Feature: String type avatar, character length can be automatically adjusted according to avatar width #1917

feat: automatic adjustment width of character avatar

---

packages/semi-ui/form/baseForm.tsx

修改了错别字 showldAppendRow 应该为 shouldAppendRow
Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: fix error word: "showldAppendRow" -> "shouldAppendRow"

---

.github/workflows/performance.yaml

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: change performence

---

packages/semi-ui/index.ts

Fixes #
🇨🇳 Chinese
- Feat: 添加 FA 架构 BaseComponent 和 BaseFoundation 的导出
---
🇺🇸 English
- Feat：Added exports for FA BaseComponent and BaseFoundation

feat: add base foundation export

---

content/input/datepicker/index-en-US.md
content/input/datepicker/index.md

docs: improve datepicker format use

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
content/navigation/tree/index-en-US.md
content/navigation/tree/index.md
packages/semi-foundation/tree/foundation.ts
packages/semi-foundation/tree/rtl.scss
packages/semi-foundation/tree/tree.scss
packages/semi-foundation/tree/treeUtil.ts
packages/semi-foundation/tree/variables.scss
packages/semi-ui/tree/_story/tree.stories.jsx
packages/semi-ui/tree/indent.tsx
packages/semi-ui/tree/index.tsx
packages/semi-ui/tree/interface.ts
packages/semi-ui/tree/treeNode.tsx
packages/semi-ui/treeSelect/index.tsx
yarn.lock

[Tree] 增加showLine功能 #1801
🇨🇳 Chinese
- Feat: Tree, TreeSelect 新增 showLine api  #1801 
---
🇺🇸 English
-  Feat: Tree, TreeSelect add showLine api #1801

Feat/add tree showLine api

---

packages/semi-foundation/notification/notificationFoundation.ts
packages/semi-ui/notification/index.tsx
packages/semi-ui/notification/notice.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Notification 的 Id 类型不正确的问题
---
🇺🇸 English
- Fix: fix the problem that types of Id in Notification is not correct.

Fix notification types

---

packages/semi-ui/timePicker/TimePicker.tsx

- [] Code style update
Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: remove the require in timepicker stopPropagation props

---

packages/semi-foundation/modal/modalFoundation.ts
packages/semi-ui/modal/Modal.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复当 Modal 未收起时直接时直接卸载 Modal 导致页面可能滚动异常的问题
---
🇺🇸 English
- Fix: Unloading the Modal directly when the Modal is not collapsed may cause the page to scroll abnormally.

fix: fix enableBodyScroll when unmount

---

.eslintrc.js
packages/semi-ui/table/Body/BaseRow.tsx
packages/semi-ui/table/Body/SectionRow.tsx
packages/semi-ui/table/Body/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Table propTypes 被打包工具移除掉导致报错问题
---
🇺🇸 English
- Fix: Fixed Table propTypes is removed in prod mode

fix: fixed Table propTypes is removed in prod mode

---

packages/semi-ui/form/hoc/withField.tsx

部分用户在使用 pnpm + monorepo 时会遇到以下报错
根据 https://github.com/microsoft/TypeScript/issues/47663 的建议尝试将  import {xx} from xxx 改为 import type {xx} from xxx
more info：https://github.com/microsoft/TypeScript/issues/42873
🇨🇳 Chinese
- Chore: Form withField 引入 utility-types 的类型声明从import 改为 import type，对使用方无影响
---
🇺🇸 English
- Chore: Form withField introduces the type declaration of utility-types from import to import type (which has no impact)

chore: add type import utility-type

---

packages/semi-ui/_utils/index.tsx
packages/semi-ui/table/Table.tsx

之前的getCurrentPageData没有类型定义，原因：
* reduce后丢失了类型
* cloneDeep的类型错误，参考lodash的类型改了下
（cloneDeep的customizer看了下项目中并没用到？）
🇨🇳 Chinese
- Fix: 修复 Table getCurrentPageData 的类型 #2032 @marshcat0
---
🇺🇸 English
- Fix: fix Table getCurrentPageData type #2032 @marshcat0

fix: fix Table getCurrentPageData type

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/treeSelect/__test__/treeSelect.test.js
packages/semi-ui/treeSelect/index.tsx

Feat # 点击清除按钮时支持自定义事件（Support custom events when clear button is clicked）
🇨🇳 Chinese
- Feat: TreeSelect 组件支持 onClear API #1331 
---
🇺🇸 English
- Feat: TreeSelect component support onClear API #1331 
support this issue #1331

feat: TreeSelect component adds onClear event

---

cypress/e2e/table.spec.js
packages/semi-ui/table/ResizableTable.tsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/FixedRowSelectionHiddenResizable/index.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes #2036
🇨🇳 Chinese
- Fix: 修复 resizable Table 行选择隐藏时多出来一列 #2036
---
🇺🇸 English
- Fix: fixed rowSelection hidden bug in resizable Table #2036

fix: fixed rowSelection hidden bug in resizable Table #2036

---

packages/semi-ui/timePicker/TimePicker.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 timepicker value 传入 undefined 时类型错误的问题
---
🇺🇸 English
- Fix: fix timepicker value props give undefined cause type error.

fix: #2058

---

packages/semi-foundation/badge/constants.ts

Fix Badge component proptypes check error when type is success
🇨🇳 Chinese
- Fix: 修复badge组件在type为success时proptypes检查错误
---
🇺🇸 English
- Fix: fix Badge component proptypes check error when type is success

fix: Badge proptypes define

---

content/input/form/index-en-US.md
content/input/form/index.md

Fixes #
🇨🇳 Chinese
- Docs: 修改 NestArrayFieldDemo 中 allowEmpty 位置  (skip changlog)
---
🇺🇸 English
- Docs:

docs: add allowEmpty in Form for NestArrayFieldDemo

---

cypress/e2e/navigation.spec.js
packages/semi-foundation/navigation/foundation.ts
packages/semi-ui/navigation/_story/FixedOpenKeys/index.tsx
packages/semi-ui/navigation/_story/navigation.stories.jsx
packages/semi-ui/navigation/index.tsx

Fixes #2115
🇨🇳 Chinese
- Fix: 修复 Nav 在 selectedKeys 变化后 openKeys 未保存上一次状态问题（影响 v2.54.1）  #2115
---
🇺🇸 English
- Fix: Fixed the problem of openKeys not saving the last state after Nav changed selectedKeys (Affects v2.54.1) #2115

fix: fix Nav openKeys bug when selectedKeys change #2115

---

packages/semi-ui/tabs/__test__/tabs.test.js
packages/semi-ui/tabs/index.tsx

Fixes #2117
🇨🇳 Chinese
- Fix: 修复 TabBar 在 SSR 时渲染为空
---
🇺🇸 English
- Fix: fix TabBar rendering as empty in SSR

fix: fix TabBar rendering as empty in SSR (#2117)

---

packages/semi-ui/autoComplete/index.tsx
packages/semi-ui/calendar/monthCalendar.tsx
packages/semi-ui/cascader/index.tsx
packages/semi-ui/datePicker/datePicker.tsx
packages/semi-ui/select/index.tsx
packages/semi-ui/tagInput/index.tsx
packages/semi-ui/timePicker/TimePicker.tsx
packages/semi-ui/tooltip/index.tsx
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx

Fixes #  #1381 
🇨🇳 Chinese
- Feat: Semi 组件的 clickOutSide 增加对 WebComponent 场景的支持，涉及组件包括 AutoComplete、Calendar、Cascader、DatePicker、Select、TagInput、TimePicker、Tooltip、TreeSelect #1381 
---
🇺🇸 English
- Feat: The clickOutSide method of the Semi component adds support for WebComponent scenarios, involving components including AutoComplete, Calendar, Cascader, DatePicker, Select, TagInput, TimePicker, Tooltip, and TreeSelect #1381

fix: fix click outside handler in webcomponent

---

packages/semi-foundation/select/select.scss
scripts/version.js

Fixes #
🇨🇳 Chinese
- Fix: 修复 Select filter 在未选中任何项时，高度不正确的问题。(影响版本 v2.56.0-beta.0)
---
🇺🇸 English
- Fix: Fixed Select filter height not as expected when empty.  (Affected version v2.56.0-beta.0)

Fix 2151 select input height

---

packages/semi-ui/locale/source/ro.ts

Fixes #2156
🇨🇳 Chinese
- Fix: 修复 Locale ro 语言类型定义与其他语言不一致问题
---
🇺🇸 English
- Fix: fix the problem of inconsistency between Locale ro language type definition and other languages

fix: update locale ro type definition

---

packages/semi-foundation/checkbox/checkbox.scss
packages/semi-foundation/checkbox/variables.scss

Fixes #
🇨🇳 Chinese
- Design Token: checkbox 新增 $color-checkbox_cardType-border-default token
---
🇺🇸 English
- Design Token: checkbox add $color-checkbox_cardType-border-default token

Feat: Checkbox cardType add token

---

cypress/e2e/table.spec.js
packages/semi-ui/table/Body/BaseRow.tsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/FixedOnGroupedRowClassName/index.tsx
packages/semi-ui/table/_story/v2/index.js
packages/semi-ui/table/interface.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Table onGroupedRow className 不生效问题 #2185
---
🇺🇸 English
- Fix: fixed Table onGroupedRow className not work bug #2185

fix: fixed Table onGroupedRow return className not work bug #2185

---

packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/_story/FixedOpenKeys/index.tsx

Nav.Item 支持透传 data-* 参数到 DOM
🇨🇳 Chinese
- feat: Nav.Item 支持透传 data-* 参数到 DOM
---
🇺🇸 English
- feat: Nav.Item support add data-* props to DOM

feat: Nav.Item 支持透传 data-* 参数到 dom

---

content/basic/typography/index-en-US.md
content/basic/typography/index.md
packages/semi-foundation/typography/constants.ts
packages/semi-ui/typography/_story/typography.stories.jsx
packages/semi-ui/typography/base.tsx
packages/semi-ui/typography/context.tsx

Fixes #
🇨🇳 Chinese
- Feat: Typography 的 size API 支持 inherit 属性
---
🇺🇸 English
- Feat: Typography's size API supports inherit attribute

feat: size of Typography support inherit

---

packages/semi-ui/form/hoc/withField.tsx

Fixes #2210
🇨🇳 Chinese
- Fix: 修复 StrictMode 开启时，dev环境下，Form 校验结果无法正常返回的问题 #2210 #2251 (影响范围：v2.57.0 - v2.59.0-beta.0)
---
🇺🇸 English
- Fix: Fixed the problem that the Form verification result cannot be returned normally in the dev environment when StrictMode is turned on #2210 #2251(Affected version: v2.57.0 - v2.59.0-beta.0)

fix: fix isUnmounted of withField (#2210)

---

packages/semi-webpack/src/semi-webpack-plugin.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Semi webpack plugin 中的 webcomponentPath 参数类型错误
---
🇺🇸 English
- Fix: Fix webcomponentPath parameter type error in Semi webpack plugin

fix: fix webComponentPath type define error in semi webpack plugin

---

content/input/transfer/index-en-US.md
content/input/transfer/index.md

Fixes #
🇨🇳 Chinese
- Docs: 更新对 Transfer 的 filter API 说明
---
🇺🇸 English
- Docs: update filter API defination In Tranfer

docs: update filter API defination In Tranfer

---

content/start/overview/index.md
src/components/ComponentOverview/index.jsx

Fixes #
🇨🇳 Chinese
- Docs: 去除 overview 页面多余组件显示
---
🇺🇸 English
- Fix: fix ...

docs: remove extra item show in overview

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
content/navigation/tree/index-en-US.md
content/navigation/tree/index.md

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

Docs/autoMergeValue API info change

---

packages/semi-ui/table/Column.tsx
packages/semi-ui/table/_story/v2/JSXColumnRecordType.tsx

Fixes #
🇨🇳 Chinese
- Chore: Table Column jsx 写法支持传入 RecordType 泛型 #2314
---
🇺🇸 English
- Chore: Table Column support RecordType #2314

feat: Table Column support RecordType #2314

---

packages/semi-foundation/slider/foundation.ts
packages/semi-ui/slider/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Slider handleDot 类型提示报错的问题
---
🇺🇸 English
- Fix: fix slider handleDot props type error

fix: fix slider types

---

packages/semi-ui/tooltip/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: fix tooltip placement undefined

---

packages/semi-foundation/upload/upload.scss
packages/semi-ui/upload/fileCard.tsx

🇨🇳 Chinese
- Fix: 修复 Upload 使用 renderThumbnail 搭配 Image 组件使用时，宽高度恒定的问题 #2343 
---
🇺🇸 English
- Fix: Fix the problem that the width and height are constant when using renderThumbnail with the Image component in Upload #2343

style: fix upload renderThumbnail img width & height

---

content/input/upload/index-en-US.md
content/input/upload/index.md
packages/semi-foundation/upload/foundation.ts

Fixes #
🇨🇳 Chinese
- Feat: Upload 支持 afterUpload 中 return url 修改预览链接
---
🇺🇸 English
- Feat: Upload support afterUpload return url modification preview link

feat: upload afterUpload support return url

---

content/basic/typography/index-en-US.md

Fixes #2352 
🇨🇳 Chinese
- Docs: 
---
🇺🇸 English
- Docs:

docs: fix error param in typography example

---

packages/semi-foundation/chat/foundation.ts
packages/semi-ui/chat/index.tsx

Fixes # Changes made to accommodate other frameworks, such as vue
🇨🇳 Chinese
- Fix: 为适配其他框架做的修改，比如vue
---
🇺🇸 English
- Fix: Changes made to accommodate other frameworks, such as vue

fix: [Chat] Changes made to accommodate other frameworks

---

packages/semi-ui/modal/Modal.tsx
packages/semi-ui/modal/ModalContent.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Modal 在 SSR 时 document 不存在的问题 （影响范围 2.62.0~2.63.0）
---
🇺🇸 English
- Fix: fix modal 'document not defined' in ssr. (Bug version 2.62.0~2.63.0)

fix: fix modal document in ssr

---

cypress/e2e/table.spec.js
packages/semi-ui/table/Body/BaseRow.tsx
packages/semi-ui/table/Body/ExpandedRow.tsx
packages/semi-ui/table/Body/SectionRow.tsx
packages/semi-ui/table/Body/index.tsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/FixedAriaLevel/index.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes #2359
🇨🇳 Chinese
- Fix: 修复 Table aria-level 在树形数据为空时错误 #2359
---
🇺🇸 English
- Fix: fix Table aria-level bug when children data is empty

fix: fixed Table aria-level bug #2359

---

content/show/image/index-en-US.md
content/show/image/index.md
packages/semi-ui/image/_story/image.stories.tsx
packages/semi-ui/image/interface.tsx

- [] Bugfix
Fixes #
🇨🇳 Chinese
- Chore: Image 组件的参数支持原生 img 元素属性
---
🇺🇸 English
- Chore: Image component props support native img element attributes

fix: Image component props support native img element attributes

---

packages/semi-foundation/input/foundation.ts
packages/semi-foundation/input/textareaFoundation.ts
packages/semi-foundation/input/util/truncateValue.ts
packages/semi-ui/input/__test__/textArea.test.js

使用二分法降低输入框截断的判断次数，原来判断 maxCount 次，现在判断 log(str.length) 次
🇨🇳 Chinese
- Perf: 优化 Input、TextArea getValueLength 判断次数
---
🇺🇸 English
- Perf: optimize Input, TextArea getValueLength judgment times

perf: optimize Input, TextArea getValueLength judgment times

---

content/plus/markdownrender/index-en-US.md
content/plus/markdownrender/index.md
packages/semi-foundation/markdownRender/foundation.ts
packages/semi-ui/markdownRender/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: MarkdownRender 支持 RemarkPlugin 和 RehypePlugins 插件
---
🇺🇸 English
- Feat: MarkdownRender supports RemarkPlugin and RehypePlugins plugins

Feat: Markdown render plugin

---

packages/semi-foundation/slider/foundation.ts
packages/semi-ui/slider/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Slider 在 range 受控模式下，拖动一个 handle 可能导致另一个 handle 抖动的问题
- Fix: 修复 Slider，在 range 模式下，min handler 可以拖动到 max handler 右侧，意外交换两个 handler 的问题
---
🇺🇸 English
- Fix: Fixed the problem that when Slider is in range controlled mode, dragging one handle may cause another handle to shake
- Fix: Fixed the problem that when Slider is in range mode, the min handler can be dragged to the right of the max handler, accidentally swapping the two handlers

fix: fix slider handle flash in control mode

---

packages/semi-ui/dropdown/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Dropdown onVisibleChange 在一些场景未定义时报错的问题
---
🇺🇸 English
- Fix: Fixed the issue that Dropdown onVisibleChange reported an error when it was not defined in some scenarios

fix: fix dropdown onVisibleChange not defined some timesz

---

packages/semi-foundation/upload/upload.scss
packages/semi-ui/upload/_story/upload.stories.jsx

Fixes #2448 
🇨🇳 Chinese
- Fix: 修复 Form.Upload 图片墙模式下 error 样式被遮挡问题
---
🇺🇸 English
- Fix: Fixed the issue that the error style was blocked in Form.Upload image wall mode

fix: Form.Upload's unexpected error outline Occlusion

---

jest.config.js
package.json
packages/semi-ui/hotKeys/__test__/hotkeys.test.js
packages/semi-ui/package.json
test/setup.js
yarn.lock

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: test without enzyme

---

packages/semi-foundation/checkbox/checkbox.scss
packages/semi-ui/checkbox/checkbox.tsx

Fixes #
🇨🇳 Chinese
- Style: 修改 Cascader 中样式名称不合理的命名， undisabled -> enable
---
🇺🇸 English
- Style: Modify the unreasonable naming of style names in Cascader, undisabled -> enable

style: [Checkbox] Modify unreasonable naming, undisabled -> enable

---

packages/semi-foundation/chat/foundation.ts
packages/semi-ui/chat/index.tsx

Fixes # Compatible with other framework. `event.persist()` only works in react. rashagu/semi-design-vue#18
🇨🇳 Chinese
- Fix: [Chat] Compatible with other framework
---
🇺🇸 English
- Fix: [Chat] 兼容其他框架，比如vue

fix: [Chat] Compatible with other framework

---

.github/workflows/chromatic.yml
.github/workflows/cypress.yml
.github/workflows/lighthouse.yml
.github/workflows/performance.yaml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test-coverage.yml
.github/workflows/test.yml

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: migrate upload/download actions form v3 to v4

---

packages/semi-ui/locale/source/ja_JP.ts

Fixes #2572
🇨🇳 Chinese
- Fix: 修复日语场景下 Table pageText 翻译不正确问题
---
🇺🇸 English
- Fix: fixed incorrect translation of Table pageText in Japanese scenarios

fix: update ja_JP table pageText

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md
cypress/e2e/cascader.spec.js
packages/semi-foundation/cascader/constants.ts
packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/_story/cascader.stories.jsx
packages/semi-ui/cascader/index.tsx

Fixes #2582 
🇨🇳 Chinese
- Feat: Cascader 支持 checkRelation API 用于设置选项关联性 #2582 
---
🇺🇸 English
- Feat: Cascader supports checkRelation API for setting option relevancy #2582

feat: [Cascader] support CheckRelation API

---

packages/semi-foundation/lottie/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Lottie props 类型不正确的问题
---
🇺🇸 English
- Fix： Lottie props incorrect type issue

Fix: fix type on lottie props

---

packages/semi-ui/tree/_story/tree.stories.jsx
packages/semi-ui/tree/treeNode.tsx

Reverts DouyinFE/semi-design#2571
原来的修改会导致

Revert "style: For Tree/TreeSelect with showLine set to true, when the top no…"

---

packages/semi-ui/jsonViewer/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复搜索框中文输入法输入问题
---
🇺🇸 English
- Fix: fixed the Chinese input problem in the search box

Fix: resolve ime error in search

---

packages/semi-ui/audioPlayer/index.tsx

Fixes #2674 
🇨🇳 Chinese
- Fix: 修复 AudioPlayer倍速弹出层样式白边问题
---
🇺🇸 English
- Fix: Fixed the white edge issue of the AudioPlayer speed pop-up box style

fix: resolve style issues in audio player

---

content/show/list/index-en-US.md
content/show/list/index.md
packages/semi-ui/list/_story/DndKitDrag/index.tsx
packages/semi-ui/list/_story/list.stories.jsx

Fixes #
🇨🇳 Chinese
- Docs: List 组件拖拽 Demo 更新为用 dnd-kit 实现
---
🇺🇸 English
- Docs: List component drag demo updated to use dnd-kit

docs: update list drag demo use dnd-kit

---

README.md

Improve readability of English doc.
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

docs: improve readability of English README doc

---

CONTRIBUTING-en-US.md
CONTRIBUTING.md
yarn.lock

更新了贡献文档，lerna v7 已经不支持 bootstrap 命令，改为指定 v6 版本号安装。
🇨🇳 Chinese
- Fix: 更新贡献指南
---
🇺🇸 English
- Fix: Update the contribution documentation.

docs: update contributing doc

---

README.md

Extend install scripts with yarn, pnpm
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

docs: extend install scripts with yarn, pnpm

---

content/plus/jsonviewer/index-en-US.md
content/plus/jsonviewer/index.md

更新JsonViewer API文档
🇨🇳 Chinese
- Docs：更新JsonViewer API文档
---
🇺🇸 English
- Docs: Modify JsonViewer API document

Docs: 更新JsonViewer API 文档

---

packages/semi-foundation/navigation/foundation.ts
packages/semi-foundation/navigation/itemFoundation.ts
packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/SubNav.tsx

Fixes #2710
🇨🇳 Chinese
- Fix: 修复 Nav.item 传入非建议属性 children 不提示 ts 报错问题
---
🇺🇸 English
- Fix: fix the problem that Nav.item does not prompt ts error when passing non-recommended attribute Children

fix: remove NavItem.children props

---

packages/semi-icons-lab/package.json
packages/semi-icons/package.json
packages/semi-illustrations/package.json

Fixes #2734 
🇨🇳 Chinese
- Fix: 保持各包的 react 版本设置一致
---
🇺🇸 English
- Fix: Keep react/react-dom settings consistent across packages

fix: Keep react/react-dom settings consistent across packages

---

content/plus/jsonviewer/index-en-US.md
content/plus/jsonviewer/index.md
packages/semi-foundation/jsonViewer/jsonViewer.scss
packages/semi-ui/jsonViewer/index.tsx

修复JsonViewer搜索框弹出位置
🇨🇳 Chinese
- Fix: 修复JsonViewer搜索框弹出位置
---
🇺🇸 English
- Fix: adjust jsonviewer search box popup positioning

Fix: adjust jsonviewer search box popup positioning

---

packages/semi-foundation/navigation/navigation.scss
packages/semi-ui/navigation/_story/navigation.stories.jsx

Fixes #2690 
🇨🇳 Chinese
- Fix: Nav 新增选择器样式为 renderWrapper 场景提供 hover 样式
---
🇺🇸 English
- Fix: Nav adds a new selector style to provide hover style for renderWrapper scenes

fix: add a new selector type for the hover style fallback in the renderWrapper scenario

---

packages/semi-foundation/navigation/variables.scss

Fixes #2675 
🇨🇳 Chinese
- Fix: 修复 Navigation 的 header 的图标在收起模式下没有居中问题 #2675 
---
🇺🇸 English
- Fix: Fixed the issue that the icon of Navigation header is not centered in collapsed mode #2675

style: Fix incorrect paddingLeft of navigation

---

cypress/e2e/jsonViewer.spec.js

更新JsonViewer测试用例
🇨🇳 Chinese
- Test: 更新JsonViewer测试用例
---
🇺🇸 English
- Test: update jsonviewer test case)

test: update jsonviewer test case

---

packages/semi-ui/jsonViewer/index.tsx
packages/semi-ui/locale/_story/locale.stories.jsx
packages/semi-ui/locale/interface.ts
packages/semi-ui/locale/source/ar.ts
packages/semi-ui/locale/source/de.ts
packages/semi-ui/locale/source/en_GB.ts
packages/semi-ui/locale/source/en_US.ts
packages/semi-ui/locale/source/es.ts
packages/semi-ui/locale/source/fr.ts
packages/semi-ui/locale/source/id_ID.ts
packages/semi-ui/locale/source/it.ts
packages/semi-ui/locale/source/ja_JP.ts
packages/semi-ui/locale/source/ko_KR.ts
packages/semi-ui/locale/source/ms_MY.ts
packages/semi-ui/locale/source/nl_NL.ts
packages/semi-ui/locale/source/pl_PL.ts
packages/semi-ui/locale/source/pt_BR.ts
packages/semi-ui/locale/source/ro.ts
packages/semi-ui/locale/source/ru_RU.ts
packages/semi-ui/locale/source/sv_SE.ts
packages/semi-ui/locale/source/th_TH.ts
packages/semi-ui/locale/source/tr_TR.ts
packages/semi-ui/locale/source/vi_VN.ts
packages/semi-ui/locale/source/zh_CN.ts
packages/semi-ui/locale/source/zh_TW.ts

🇨🇳 Chinese
- Feat: JsonViewer 支持 i18N
---
🇺🇸 English
- Feat: JsonViewer suupot i18N

feat: JsonViewer add i18n support

---

packages/semi-foundation/jsonViewer/jsonViewer.scss
packages/semi-json-viewer-core/src/view/view.ts

修复JsonViewer不开启自动换行时长文本折叠问题
修复JsonViewer行号展示问题
🇨🇳 Chinese
- Fix: 修复JsonViewer不开启自动换行时长文本折叠问题
- Fix: 修复JsonViewer行号展示问题
---
🇺🇸 English
- Fix: Fixed the problem of long text folding when JsonViewer does not enable automatic line wrap
- Fix: Fixed the problem of JsonViewer line number display

Fix: Resolve JsonViewer Display Issue

---

content/input/transfer/index-en-US.md
content/input/transfer/index.md

Fixes #
可拖拽的 Transfer，不支持 key 为 数字 0 的情况，修改官网用例中的 key
🇨🇳 Chinese
- Docs: Transfer 官网示例修改
---
🇺🇸 English
- Fix: fix ...

docs: Transfer official website example modification

---

packages/semi-foundation/scrollList/scrollList.scss
packages/semi-foundation/scrollList/variables.scss
packages/semi-ui/timePicker/_story/timepicker.stories.jsx

Support #2788 
🇨🇳 Chinese
- Design Token:  ScrollList 新增 $color-scrollList_header-bg 用于控制 header 颜色
---
🇺🇸 English
- Design Token:  ScrollList adds $color-scrollList_header-bg to control header color

style: add color-scrollList_header-bg support

---

packages/semi-foundation/button/button.scss
packages/semi-foundation/button/variables.scss
packages/semi-foundation/cascader/cascader.scss
packages/semi-foundation/cascader/variables.scss
packages/semi-foundation/inputNumber/inputNumber.scss
packages/semi-foundation/inputNumber/variables.scss

Fixes #
内部业务平台需求，分步骤支持。 本 RP 支持
1. Button 不同大小能够支持不同的字体设置
2. Cascader 希望支持在不同尺寸下的边距设置
3. inputNumber 的 innerButton 模式时候，希望步进器不要遮挡边框
🇨🇳 Chinese
- Style: 增加 Button 在小尺寸/大尺寸上的字体设置 token，包括$font-button_small-fontSize， $font-button_small-lineHeight，$font-button_small-fontWeight 等 token
- Style: 增加 Cascader 在大尺寸/小尺寸下的内边距 token 设置，包括$spacing-cascader_small_selection-paddingLeft，$spacing-cascader_small_selection-paddingRight 等 token
-Style: 增加 inputNumber 在 innerButton 模式下步进器的圆角 token $radius-inputNumber_inner
---
🇺🇸 English
- Style: Added font setting tokens for Button in small/large sizes, including $font-button_small-fontSize, $font-button_small-lineHeight, …

style: add more token support for Button/Casader/inputnumber

---

.github/workflows/cypress.yml
packages/semi-ui/userGuide/index.tsx

通过增加环境变量，简化 cypress 执行的输出
🇨🇳 Chinese
---
🇺🇸 English

test: add coverage false to cypress yml to hide coverage output

---

content/feedback/notification/index-en-US.md

This PR fix an incorrect component attribute in the documentation site.
🇨🇳 Chinese
- Docs: 修正 notification 英文文档组件属性不准确问题
---
🇺🇸 English
- Docs: inaccurate component attribute in notification en doc

Fix: inaccurate component attribute

---

packages/semi-foundation/breadcrumb/breadcrumb.scss
packages/semi-ui/breadcrumb/_story/breadcrumb.stories.jsx

Fixes #2883
🇨🇳 Chinese
- Style: 修复 BreadCrumb 的 item 在 noLink 模式下的样式问题 #2883 
---
🇺🇸 English
- Style: Fix the style problem of BreadCrumb's item in noLink mode #2883

style: Fix the style problem of BreadCrumb in noLink mode

---

packages/semi-json-viewer-core/src/model/jsonModel.ts
packages/semi-json-viewer-core/src/model/selectionModel.ts
packages/semi-json-viewer-core/src/service/completion.ts
packages/semi-json-viewer-core/src/view/complete/completeWidget.ts
packages/semi-json-viewer-core/src/view/edit/editWidget.ts
packages/semi-json-viewer-core/src/view/view.ts
yarn.lock

Fixes #2767 #2910 #2907 #2905 #2906 
🇨🇳 Chinese
- Fix: 修复JsonViewer 全选删除后继续删除报错问题
- Fix: 修复JsonViewer 始光标删除行为报错问题
- Fix: 修复JsonViewer 选区边界问题
- Fix: 修复JsonViewer 代码补全无法点击问题
- Fix: 修复JsonViewer 代码补全布尔类型提示问题
- Fix: 修复JsonViewer 拖动选择复制删除不完全问题
---
🇺🇸 English
- Fix: Fixed the error problem of JsonViewer continuing to delete after selecting all
- Fix: Fixed the error problem of JsonViewer initial cursor deletion behavior
- Fix: Fixed the JsonViewer selection boundary problem
- Fix: Fixed the JsonViewer code completion cannot be clicked
- Fix: Fixed the JsonViewer code completion Boolean type prompt problem
- Fix: Fixed the JsonViewer drag selection copy deletion incomplete problem

Fix: resolve JsonViewer editing issues

---

packages/semi-foundation/badge/badge.scss

Fixes #
fix error badge count font weight
🇨🇳 Chinese
- Fix: 修复Badge count css错误的字重值
---
🇺🇸 English
- Fix: Fix the incorrect font weight value of the Badge count css

fix: badge count error font weight

---

packages/semi-foundation/badge/badge.scss
packages/semi-ui/badge/_story/badge.stories.jsx

Fixes # 2929
🇨🇳 Chinese
- Fix: 修复 light 主题 Badge 单独使用时样式不符合预期问题
---
🇺🇸 English
- Fix: fix the issue that the style of the light theme badge does not meet expectations when used alone

fix: the light theme badge does not look as expected when used alone

---

packages/semi-json-viewer-core/src/model/foldingModel.ts

Fixes #2971
🇨🇳 Chinese
- Fix: 修复Folding Model 初始化问题
---
🇺🇸 English
- Fix: fixed folding model initialization issue

fix: resolve folding model error

---

packages/semi-json-viewer-core/src/view/edit/editWidget.ts

Fixes #2978
🇨🇳 Chinese
- Fix: JsonViewer 键盘事件兼容window
---
🇺🇸 English
- Fix: JsonViewer keyboard events are compatible with window

Fix JsonViewer 键盘事件兼容window
