packages/semi-foundation/slider/foundation.ts

Fixes #
🇨🇳 Chinese
- 修复value受控改变时触发onAfterChange的问题
---
🇺🇸 English
- Fix onAfterChange triggered unexpectedly when value changed in control mode

fix(slider): onAfterChange triggered unexpectedly when value changed

---

packages/semi-foundation/datePicker/foundation.ts
packages/semi-ui/datePicker/__test__/datePicker.test.js
packages/semi-ui/datePicker/_story/datePicker.stories.tsx

Fixed DatePicker component type=month can not select some date in US timeZone
🇨🇳 Chinese
- 修复 DatePicker `type=month` 时，计算机设置为美东时区，无法选中日期问题
---
🇺🇸 English
- Fixed DatePicker component type=month can not select some date in US timeZone

fix(datepicker): type=month can not select some date in US timeZone

---

packages/semi-foundation/form/foundation.ts
packages/semi-ui/form/_story/DynamicField/arrayFieldDemo.jsx

Fix #211 
🇨🇳 Chinese
- 修复 Form 通过 setValues 重置 ArrayField时，formState已生效，UI渲染未同步更新的问题
---
🇺🇸 English
- Fix the issue that when Form resets ArrayField through setValues, formState has taken effect and UI rendering is not updated synchronously

[form] using formApi.setValues to reset ArrayField not work when pass empty object

---

packages/semi-foundation/tagInput/utils/getSplitedArray.ts
packages/semi-ui/tagInput/__test__/tagInput.test.js
packages/semi-ui/tagInput/_story/tagInput.stories.js
packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 TagInput 在 separator 不为 string 或 array 时输入值会被清空的问题
---
🇺🇸 English
- Fix the problem that the input value of TagInput will be cleared when separator is not string or array.

fix: [TagInput] Input value will be cleared when separator is not array or string #182

---

packages/semi-foundation/tree/tree.scss
packages/semi-foundation/tree/variables.scss

Fixes #
🇨🇳 Chinese
- 修复 Tree / TreeSelect 在异步加载 loading 时，选项高度会变高的问题
---
🇺🇸 English
- Fix the problem that the height of the option will become higher when the Tree / TreeSelect is loaded asynchronously

fix: [Tree/TreeSelect] remove the padding and margin of loading Spin #181

---

packages/semi-ui/cascader/__test__/cascader.test.js
packages/semi-ui/cascader/_story/cascader.stories.js
packages/semi-ui/cascader/index.tsx

Fixes #
🇨🇳 Chinese
- 修复.Cascader 多选且开启 onChangeWithObject，defaultValue 为 object[] 没有生效的问题 
---
🇺🇸 English
- When multiple and onChangeWithObject, fix the defaultValue passed into object[] does not take effect

fix: [Cascader] When multiple and onChangeWithObject, the defaultValue passed into object[] does not take effect#184

---

packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/__test__/cascader.test.js
packages/semi-ui/cascader/_story/cascader.stories.js

Fixes #
🇨🇳 Chinese
- 修复 Cascader 单选时，defaultValue 为 disabled 节点时选中会被过滤的问题
---
🇺🇸 English
- Fix Cascader single selection, the problem that the defaultValue is disabled when the node is selected will be filtered

fix: [Cascader] Fix the option will be filtered when the single-select defaultValue is disabled option #183

---

packages/semi-foundation/input/input.scss

Fixes #
🇨🇳 Chinese
- 修复 ...
修复 Input 组件中 $color-input_default-border-hover 没有被实际引用的问题
---
🇺🇸 English
- Fix ...

fixed $color-input_default-border-hover not reference

---

packages/semi-foundation/slider/foundation.ts
packages/semi-ui/slider/index.tsx

修复 Slider `value` 受控时点击轨道未触发 `onAfterChange` 的问题
🇨🇳 Chinese
- 修复 Slider `value` 受控时点击轨道未触发 `onAfterChange` 的问题
---
🇺🇸 English
- Fix Slider when `value` is controlled, click on track not trigger `onAfterChange`

fix(slider): when `value` is controlled, click on track not trigger `onAfterChange`

---

packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 TreeSelect renderSelectedItem ts 类型定义不准确的问题
---
🇺🇸 English
- Fix the inaccurate definition of TreeSelect renderSelectedItem ts type

chore: [TreeSelect] modify renderSelectedItem type #265

---

content/input/form/index-en-US.md
content/input/form/index.md
packages/semi-foundation/form/interface.ts
packages/semi-foundation/form/utils.ts
packages/semi-ui/form/hoc/withField.tsx
packages/semi-ui/form/interface.ts
packages/semi-ui/notification/index.tsx
packages/semi-ui/toast/index.tsx
packages/semi-ui/upload/index.tsx

🇨🇳 Chinese
- ts interface修改
- Form增加 WithFieldOption 的导出
- Notification增加 ConfigProps的导出
- Toast增加 ConfigProps的导出
- Upload增加 BeforeUploadObjectResult、AfterUploadResult的导出
- 文档修改
- Form文档中WithFieldOption描述去掉s，保持与interface命名一致
---
🇺🇸 English

fix: export some interface that has been exported in semi 1.x

---

packages/semi-foundation/tabs/foundation.ts

Fixes #208 
🇨🇳 Chinese
- 修复 Tabs 点击激活状态的 `tab` 仍触发 `onChange` 的问题
---
🇺🇸 English
- Fix Tabs `onChange` triggers unexpectly when click active `tab`

fix(tabs): onChange triggers unexpectly when click active tab

---

content/input/cascader/index-en-US.md
content/input/cascader/index.md
packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/__test__/cascader.test.js
packages/semi-ui/cascader/_story/CustomTrigger/index.jsx
packages/semi-ui/cascader/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 Cascader 多选时，triggerRender 入参中 value 为空的问题
---
🇺🇸 English
- Fix that the value of triggerRender in the parameter is empty when Cascader is multi-selected

fix: [Cascader] add value of triggerRender when multiple selection #259

---

packages/semi-ui/select/option.tsx

fix Select.Option children render
if children is string, then should wrap a option-text div
if children is ReactElement, then render children direct
🇨🇳 Chinese
- 修复 Select.Option children渲染逻辑
---
🇺🇸 English
- Fix Select.Option children rendering logic

fix: [Select] render when children is not full string character

---

packages/semi-ui/collapsible/index.tsx

由于collapsible的children节点 margin 超出父元素而未被父元素包含的现象，现将子元素的直接父元素设置为 overflow：hidden 解决 children margin 穿透问题
🇨🇳 Chinese
- 修复 collapsible 组件展开动画闪烁问题
---
🇺🇸 English
- Fix collapsible component opening animation delay problem

fix: 修复collapsible组件展开样式

---

content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-ui/select/_story/select.stories.js
packages/semi-ui/select/index.tsx

Fixes #
🇨🇳 Chinese
- 修复 Select renderSelectedItem 返回的 isRenderInTag 为 false 时会报 key 的 warning 的问题
---
🇺🇸 English
- Fix the key warning will be reported when the isRenderInTag returned by Select renderSelectedItem is false

fix: [Select] Add key to the content returned by renderSelectedItem #320

---

packages/semi-foundation/rating/rating.scss
packages/semi-ui/rating/item.tsx

Fixes #346 
🇨🇳 Chinese
- 修复 Rating 组件半星展示错误，当父级设置 line-height 时
---
🇺🇸 English
- Fix Rating component half star ui error, when parent element set line-height
demo
```
<Rating allowHalf defaultValue={3.5} style={{lineHeight: 2}} />
```

fix(rating): allowhalf ui error when parent element set line-height

---

packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss
packages/semi-theme-default/scss/variables.scss

Fixed Table fixed cell `z-index` is not higher than show type components(like Avatar etc)
🇨🇳 Chinese
- Table fixed 单元格的 z-index 调整为 101，之前为 1
---
🇺🇸 English
- Update Table fixed cell z-index from 1 to 101

fix(table): fixed cell z-index is not higher than show type components

---

content/input/switch/index-en-US.md
content/input/switch/index.md
packages/semi-ui/spin/icon.tsx
packages/semi-ui/switch/_story/switch.stories.js
packages/semi-ui/switch/_story/switch.stories.tsx
packages/semi-ui/switch/index.tsx

Switch组件的 a11y 支持，改动点如下
- Switch 具有 switch role，当 checked 为 true 时，aria-checked 将被自动设置为 true，反之亦然.
- 增加 aria-label、aria-labelledby API
- 其他组件：
- Spin所消费的svg，由于含有id，当存在多个spin元素或者多个 Switch loading时，不符合 HTML 要求 id必须为唯一的规范，将其移除（已测试无副作用）
- 文档：增加 Accessibility 相关说明
🇨🇳 Chinese
- Switch 组件 a11y 增强
---
🇺🇸 English
- Switch Component support a11y

feat(a11y): switch aria #205

---

content/feedback/progress/index-en-US.md
content/feedback/progress/index.md
packages/semi-ui/progress/_story/progress.stories.js
packages/semi-ui/progress/index.tsx

- Progress 组件添加 a11y aria-*支持，新增`aria-valuetext`、`aria-label`、`aria-labelledby`、`id` API
-   Progress 添加 `progressbar` role 来表示它是一个进度条组件。
-   Progress 会自动将 `aria-valuenow` 设置为传递给组件的进度百分比（`percent`），以确保屏幕阅读器可以获取正确的百分比数值。另外，Progress 支持传入 `aria-valuetext`，当传入时，根据 W3C 规范，`aria-valuetext` 将优先被屏幕阅读器使用消费，而不是 `aria-valuenow`
-   Progress 支持传入 `aria-label`、`aria-labelledby`
-   当 Progress 外部存在关于 Progress 作用的描述元素时，可以通过 aria-labelledby 显式指定某些元素的 id 是 Progress 的标签
-   否则应当通过 aria-label 说明 Progress 所代表的具体数值含义
```js
// good case
<p id="progressbar-label">Disk Usage</p>
<Progress aria-labelledby="progressbar-label" percent={80} />
// good case
<Progress aria-label='Percent of disk usage' …
```

feat(a11y): progress aria #205

---

content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-ui/_utils/index.ts
packages/semi-ui/select/_story/select.stories.js
packages/semi-ui/select/index.tsx

- select renderInput增加 inputProps的消费
- select api table移除一些较早的版本说明（v0.x的版本说明对开源用户基本无意义，可以移除掉）
🇨🇳 Chinese
- Select 新增 inputProps ，便于用户可实现一些特殊功能。例如传入 onCompositionEnd，onKeyDown事件监听等
---
🇺🇸 English
- Select newly added inputProps, which is convenient for users to realize some special functions. For example, incoming onCompositionEnd, onKeyDown event monitoring, etc.

feat: [select] support inputProps

---

packages/semi-ui/rating/item.tsx

Fixes #356 
🇨🇳 Chinese
- 修复 Rating 组件设置 size 为 number 后 UI 错误
---
🇺🇸 English
- Fix Rating UI error when set size number
demo
```
<Rating defaultValue={5} size={50}/>
```

fix(rating): size props working error when set number #356

---

packages/semi-ui/_utils/index.ts

Fixes #
🇨🇳 Chinese
- 修复mediaQueryList在saafri <=13时，EventTarget上不存在addEventListener方法
---
🇺🇸 English
- Fix When mediaQueryList is saafri <=13, the addEventListener method does not exist on EventTarget

fix: mediaQuery addEventListener not effect in safari<=13

---

packages/semi-foundation/select/foundation.ts

Fixes #444 
_removeInternalKey 增加一层浅复制，原有的逻辑中，对object的key进行delete操作，会导致意外修改 state 中的 options 的属性。  
如果当前defaultValue有值，然后使用键盘backspace键删除已选项后，上述行为会导致对应的option在下拉列表中不可见（直接原因：将原有的 _show：true 整个key移除掉了）  
调用链：_handleBackspaceKeyDown -> removeTag -> _notifyDeselect -> _removeInternalKey （这一步中意外修改了入参）
🇨🇳 Chinese
- 修复Select filter为true时，使用backspace移除已选项时，导致对应option在下拉列表中不可见的问题
---
🇺🇸 English
- Fix Select using backspace to delete will cause the option to be invisible

fix: [select] using backspace to delete will cause the option to be invisible, close #444

---

content/show/popover/index-en-US.md
content/show/popover/index.md
content/show/tooltip/index-en-US.md
content/show/tooltip/index.md
packages/semi-ui/popover/index.tsx
packages/semi-ui/tooltip/TriangleArrow.tsx
packages/semi-ui/tooltip/TriangleArrowVertical.tsx
packages/semi-ui/tooltip/_story/tooltip.stories.js
packages/semi-ui/tooltip/index.tsx
packages/semi-webpack/tsconfig.json

- props增加 role传入，便于Popover、Dropdown等使用时，可以二次定义 role，default值为 tooltip
- tooltip箭头相关的svg，增加 aria-hidden属性
- 为 Tooltip 的content wrapper 自动追加 id，用于与 children 的 aria-descriptionby 匹配，关联 content 与 children
- children添加  aria-descriptionby，值为上面生成的id
- 向底层Tooltip 传入的props 增加 role，当trigger为custom、click时，role传dialog（W3C规范），当trigger为hover时，role传tooltip（参考chakra-ui，这个设定更合理一些）
- 当 Popover 向 Tooltip 传入的role为dialog时，trigger（即children）需要追加 Popover（dialog）特有的aria属性，如下：
- aria-expanded：根据visible切换true or false
- aria-haspopup，恒定为 dialog，标识当前 trigger是一个有弹出层的控件
- aria-controls：与content wrapper的id相同，将 children 与 content 关联起来，表明 children具体控制的 content
- tooltip.stories.js：format了一次 tooltip …

feat: a11y - improve tooltip、popover aria #205

---

cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/datePicker.scss
packages/semi-foundation/datePicker/foundation.ts
packages/semi-foundation/datePicker/inputFoundation.ts
packages/semi-foundation/datePicker/rtl.scss
packages/semi-foundation/datePicker/variables.scss
packages/semi-ui/datePicker/__test__/datePicker.test.js
packages/semi-ui/datePicker/_story/datePicker.stories.js
packages/semi-ui/datePicker/datePicker.tsx

- 修复确认选择关闭面板时，输入框显示日期不正确问题
- 更细一处交互，click outside 不再关闭面板，需通过点击取消关闭面板（与设计师DC、HZ确认）
- 修复确认选择模式 footer 按钮间距不正确问题（这个是因为 Button 组件自带的margin改为0引起的，老bug，之前没发现）
before
after
- 修复 DatePicker RTL 模式下，年切换按钮方向错误问题
🇨🇳 Chinese
- 修复 DatePicker 在 needConfirm 模式时，点击取消按钮输入框日期未返回到已选中日期问题 #457
- 优化 DatePicker 交互细节，确认选择模式 click outside 不再关闭面板，需通过点击取消关闭面板
- 修复 DatePicker 确认选择模式 footer 按钮间距不正确问题
- 修复 DatePicker RTL 模式下，年切换按钮方向错误问题
---
🇺🇸 English
- Fixed  DatePicker input value is back to confirmed value bug when needConfirm is true #457
- Optimize DatePicker interaction details,`needConfirm` mode, click outside will no longer close the panel, you need to click cancel to close the panel
- …

fix(datepicker): input value is back to confirmed value bug #457

---

packages/semi-ui/transfer/index.tsx

当使用transfer组件时候，选择分组结构，并且因为个性化场景，需要修改定制title的时候，如果传入reactElement 会引起 key重复的warning
When using the transfer component, select the grouping structure, and because of the personalized scenario, when you need to modify the custom title, if you pass in the reactElement, it will cause the key to repeat the warning
🇨🇳 Chinese
- fix:  修复 transfer在groupList场景下,title属性传入reactElement节点导致key-warning
---
🇺🇸 English
- fix:  Fix Transfer In the groupList scenario, the title attribute is passed into the reactElement node, resulting in key-warning

Fix transfer title key warning

---

packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/tooltip/_story/tooltip.stories.js
packages/semi-ui/tooltip/index.tsx

🇨🇳 Chinese
- Fix: 修复Tooltip 计算 adjustOverflow时未将 spacing纳入，导致内容超出（但未超过8px）后仍未自动切换方向的问题
- Fix: 修复 Tooltip 展现浮层默认方向空间不足，触发 adjustOverflow 自动切换方向时会闪烁的问题
---
🇺🇸 English
- Fix: Fix the problem that Tooltip did not include spacing when calculating adjustOverflow, which caused the content to exceed (but not exceed 8px) and still not automatically switch the direction.
- Fix: Fix Tooltip showing that the default direction of the floating layer is insufficient, and it will flicker when adjustOverflow is triggered to automatically switch the direction.

fix: (tooltip) adjustOverflow not include spacing & auto just cause splash screen

---

content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/__test__/select.test.js
packages/semi-ui/select/_story/select.stories.js
packages/semi-ui/select/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: Select 支持autoClearSearchValue，允许选中后保留当前搜索关键字
---
🇺🇸 English
- Feat: Select supports autoClearSearchValue, allowing the current search keywords to be retained after selection

feat: select supports autoClearSearchValue when multiple is true

---

packages/semi-ui/list/index.tsx

Fixes [#393](https://github.com/DouyinFE/semi-design/issues/393)
🇨🇳 Chinese
- 修复 List 组件传递 datasource 属性时, renderItem 类型丢失
---
🇺🇸 English
- Fix  List component pass the datasource props, the renderItem function params of item missing the type defined

refactor: change list component datasource type

---

packages/semi-foundation/input/textarea.scss
packages/semi-ui/input/textarea.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 TextArea readonly 模式下光标显示为禁用问题 [@chenc041](https://github.com/chenc041)  [#535](https://github.com/DouyinFE/semi-design/issues/535)
---
🇺🇸 English
- Fix: Fixed TextArea readonly hover cursor style bug [@chenc041](https://github.com/chenc041)  [#535](https://github.com/DouyinFE/semi-design/issues/535)

fix(textarea): set cursor attribute to text when textarea is readonly

---

content/input/timepicker/index-en-US.md
content/input/timepicker/index.md
packages/semi-foundation/timePicker/foundation.ts
packages/semi-ui/timePicker/TimePicker.tsx
packages/semi-ui/timePicker/__test__/timePicker.test.js
packages/semi-ui/timePicker/_story/timepicker.stories.js

close #555 
🇨🇳 Chinese
- feat: TimePicker 支持 `onChangeWithDateFirst` API #555 
---
🇺🇸 English
- Fix: TimePicker add support for `onChangeWithDateFirst` API #555

feat: add support for `onChangeWithDateFirst` API

---

packages/semi-ui/select/index.tsx

原有逻辑，每次render都会有不同的key。第一次点击后直接dom就刷新，已经是不一样的key了。所以绑定的事件也没有触发
🇨🇳 Chinese
- Fix: 修复Select 使用 renderCreateItem 自定义时，新建选项需要点击两次的问题 #574
---
🇺🇸 English
- Fix: Fix the problem that when Select is customized using renderCreateItem, the new option needs to be clicked twice #574

fix: [select] need click twice when using renderCreateItem, close #574

---

packages/semi-ui/typography/_story/typography.stories.js
packages/semi-ui/typography/util.tsx

when set whiteSpace pre
Fixes #595 
🇨🇳 Chinese
- Fix: 修复 Typograph 组件截断错误，当设置 whiteSpace 为 'pre-line' 且 expandable
---
🇺🇸 English
- Fix: fix Typograph ellipsis error when set whiteSpace 'pre-line' and expandable

fix(typo): paragraph ellipsis error

---

content/navigation/navigation/index-en-US.md
content/navigation/navigation/index.md
packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/SubNav.tsx

before：
after：
🇨🇳 Chinese
- Fix: 修复 Nav limitIndent 在折叠态后，子菜单通过 dropdown 形式展示时，也被消费，从而导致了多余的空白间隔的问题
---
🇺🇸 English
- Fix: Fix Nav limitIndent in the collapsed state, when the submenu is displayed in the form of dropdown, it is also consumed, which leads to the problem of redundant blank space

fix: (nav) limitIndent should not work when collapsed

---

packages/semi-ui/tabs/interface.ts

Fixes TabPane 'icon' props from `string` to `ReactNode`
🇨🇳 Chinese
- Fix: 修复 TabPane 的 'icon' props DTS 问题，可以传入一个 `ReactNode`，但 DTS 只有 `string`
---
🇺🇸 English
- Fix: TabPane interface define, 'icon' props from `string` to `ReactNode`

fix: 🐛 tabpane 'icon' props dts error

---

packages/semi-ui/select/index.tsx
packages/semi-ui/select/virtualRow.tsx

…ption
Fixes #
🇨🇳 Chinese
- Fix: 修正 @douyinfe/semi-ui  select组件 `visibleOption` 单词拼写错误（内部传参，对使用侧无影响）
---
🇺🇸 English
- Fix: Fix the misspelling of the word `visibleOption` in the @douyinfe/semi-ui select component (internal parameter transfer, no effect on the user side)

fix(typo): change select spelling mistake, visibileOption to visibleOption

---

packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/index.tsx

Fixes #
🇨🇳 Chinese
- feat: Select 组件当用键盘上下键操作时，自动滚动，调整聚焦 option 的相对位置 #607 
---
🇺🇸 English
- feat: Select component automatically scrolls when the keyboard up and down keys are used to adjust the relative position of the focused option, #607

feat(select): update scrollTop after key down

---

cypress/integration/form.spec.js
packages/semi-foundation/form/foundation.ts
packages/semi-foundation/form/interface.ts
packages/semi-ui/form/__test__/formApi.test.js
packages/semi-ui/form/_story/FormApi/arrayDemo.jsx
packages/semi-ui/form/_story/Layout/slotDemo.jsx
packages/semi-ui/form/_story/form.stories.js
packages/semi-ui/form/baseForm.tsx

… not working as expected
- form的 forceUpdate增加callback回调 （关联修改 updateStateValue / updateStateTouched/ updateStateError ）
使用formApi.setValue 时，对 nested field的修改，移入callback中，确保 nested field不会多取
🇨🇳 Chinese
- Fix: Form 组件使用formApi setValue/setError/setTouched 针对数组型 fieldPath 删除某项后，赋值后不符合预期, #604 
---
🇺🇸 English
- Fix: fix ...
已增加  Jest Unit Test & Cypress E2E Test

fix: [form] setValue remove middle line in field of array type, close #604

---

packages/semi-ui/table/Body/index.tsx
packages/semi-ui/table/__test__/table.test.js
packages/semi-ui/table/_story/v2/FixedExpandedRow/index.jsx
packages/semi-ui/table/_story/v2/index.js

Fixes #686
🇨🇳 Chinese
- Fix: 修复 Table 展开任意行时其他展开行会重复渲染问题 #686
---
🇺🇸 English
- Fix: Fixed the problem that when Table expands any row, other expanded rows will be rendered repeatedly #686

fix(table): expanded row re-render #686

---

packages/semi-ui/tree/nodeList.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 TreeSelect 展开节点后若垂直方向剩余空间不足，未自动调整展开方向的问题
---
🇺🇸 English
- Fix: Fixed the problem that if the remaining space in the vertical direction is insufficient after TreeSelect expands the node, the expansion direction is not automatically adjusted

fix: [treeSelect] popover direction adjust problem

---

packages/semi-ui/radio/__test__/radioGroup.test.jsx
packages/semi-ui/radio/radioGroup.tsx

Fixes #712
🇨🇳 Chinese
- Fix: RadioGroup value 为 NaN 时，触发 Maximum update depth exceeded
---
🇺🇸 English
- Fix: when radio-group's value is NaN, "Maimum update depth exceeded" is triggered

Fix: when radio-group's value is NaN, "Maimum update depth exceeded" is triggered

---

packages/semi-foundation/button/button.scss

使用 `focus-visible` 解决按钮点击后有聚焦样式问题，[storybook](https://semi-storybook.web.bytedance.net/?path=/story/button--combination-show)
- 2.6.0 ~ 目前，Button focus 在点击后会显示出来
- 修改后，点击不聚焦，切换 Tab 聚焦，但 Safari 15.3 和之前的版本没有效果（点击后不聚焦，切换 Tab 也不聚焦）。
🇨🇳 Chinese
- Fix: 修复 Button 点击后聚焦样式问题
---
🇺🇸 English
- Fix: Fixed focus style issue after Button is clicked

fix(button): fixed button focus style when clicked

---

.github/workflows/cypress.yml
content/show/popover/index-en-US.md
content/show/popover/index.md
cypress/integration/popover.spec.js
cypress/integration/tooltip.spec.js
package.json
packages/semi-foundation/tooltip/foundation.ts
packages/semi-foundation/utils/isEscPress.ts
packages/semi-foundation/utils/keyCode.ts
packages/semi-ui/_utils/index.ts
packages/semi-ui/popover/_story/popover.stories.js
packages/semi-ui/popover/index.tsx
packages/semi-ui/tooltip/index.tsx
yarn.lock

Popover 依赖了 Tooltip，有些功能需要加到 Tooltip 上，通过 API 的方式打开。
**更新：**
- Tooltip content 支持传入函数
- trigger 为 hover 时，新增聚焦时打开弹出层
**新增：**
- Tooltip 新增 guardFocus API，设置为 true 时，在弹出层内切换 tab 时，焦点会在弹出层内循环
- 新增 onEscKeydown 回调函数，在 trigger 或弹出层内按下 ESC 键会触发此回调函数
- 新增 returnFocusOnClose props，控制关闭弹出层后焦点是否回到 trigger 上。只有在 trigger=click 时生效
- 新增 onEscKeydown
- 新增 returnFocusOnClose
- 新增 initFocusRef 入参，content 可以将此 ref 传入你想聚焦的 DOM 上，打开面板时会自动聚焦
🇨🇳 Chinese
- Feat: Popover 新增 A11y 键盘和焦点适配 #205
---
🇺🇸 English
- Feat: Popover adds A11y keyboard and focus adaptation #205

feat(a11y): popover keyboard

---

packages/semi-foundation/inputNumber/foundation.ts
packages/semi-ui/inputNumber/_story/inputNumber.stories.js

InputNumber value be formated when precision is set and defaultvalue is empty
like this:
🇨🇳 Chinese
- Fix: 修复当inputnumber初始值为空时，如果设置了precision，内容会被初始化为0且进行精度格式化的问题
---
🇺🇸 English
- Fix: fix  InputNumber value be formated when precision is set and defaultvalue is empty

fix: (InputNumber) value be formated when precision is set and defaultvalue is empty

---

packages/semi-foundation/transfer/transfer.scss
packages/semi-ui/transfer/index.tsx

Fixes #780 
🇨🇳 Chinese
- Fix: 修复transfer，type为treelst，动态加载spin的css问题
---
🇺🇸 English
- Fix: fix the transfer component of type treeList, the css problem of spin when dynamically loaded

fix: issue #780

---

packages/semi-foundation/timePicker/foundation.ts
packages/semi-ui/scrollList/scrollItem.tsx
packages/semi-ui/timePicker/_story/timepicker.stories.js

[TimePicker - use12Hours 设置initValue 受控情况下无法正常设置am/pm](https://bytedance.feishu.cn/docx/doxcnnvpJPJuu6R1UNDx2VMYrqh)
[TimePicker - use12Hours传入 defaultValue无法设为下午](https://bytedance.feishu.cn/docx/doxcnrkZ1ceW2L1XVD1Ff8gTUBg)
[TimePicker - 向上滑动选择时间，清除时间，时间不会回到00:00:00，而是回到03:03:03](https://bytedance.feishu.cn/docx/doxcnPQKcahhg8lymRUFKh18EXb)
🇨🇳 Chinese
- Fix:   修复TimePicker组件use12Hours下，pm/am无法正确设置问题 https://github.com/DouyinFE/semi-design/issues/776 ；修复TimePicker组件向上选择选项后点击清除无法回到预期位置问题
---
🇺🇸 English
- Fix: fix the problem that pm/am could not be set correctly under the TimePicker component use12Hours https://github.com/DouyinFE/semi-design/issues/776, fix the problem that …

fix: fix timePicker defaultValue and clear after select up

---

packages/semi-foundation/inputNumber/foundation.ts
packages/semi-ui/form/hoc/withField.tsx
packages/semi-ui/inputNumber/__test__/inputNumber.test.js
packages/semi-ui/inputNumber/_story/inputNumber.stories.js
packages/semi-ui/inputNumber/index.tsx

Fixes #812
- 问题： 修复 InputNumber 受控传入值不在 min 和 max 范围内，InputNumber 内部会自动格式化到指定范围，这时如果不 notifyChange，InputNumber 显示的值与受控的值会不一致问题
- 修复后：componentDidMount 和 componentDidUpdate 会对格式化后的 value 进行校验，如果和传入的 props.value 或 props.defaultValue 不符，会调用 notifyChange 一次。
- 涉及 Form 的修改：field register 时，field value 可能已经更新，注册时 formState 需要使用更新后的值。原来使用的是 state.value，修改后使用的是 useStateWithGetter 传出来的 getVal，它获取的是 ref.value，是实时更新的值。
**reviewer 需要留意此处变更是否会带来渲染问题**
🇨🇳 Chinese
- Fix: 修复 InputNumber 受控使用且设置最小值，格式化传入的值到范围内时未 notifyChange 问题 #812
---
🇺🇸 English
- Fix: Fix InputNumber controlled use and set the min prop, the issue of not notifyChange when formatting the controlled value #812

fix: InputNumber min value notifyChange bug #812

---

cypress/integration/popover.spec.js
packages/semi-ui/popover/_story/popover.stories.js
packages/semi-ui/tooltip/index.tsx

Fixes #818
问题：
- react16 事件委托在 document，我们的 Tooltip 同时在 document 监听原生事件 mousedown 以处理 clickoutside。#818 属于嵌套弹出层场景，预期是点击内部 Select 不关闭外部 Popover。
代码实现上我们想在弹出层的 react 处理函数中取消冒泡以不触发外层 document 上的处理函数。但是这依赖于 document 上监听事件的时机晚于 react 绑定事件的时机。
- react17 以后，react 事件委托在 root 节点，其实不会有这个问题~
更新：
- 这里我们为了兼容 16 将 document 监听 clickoutside 修改为 window 监听。
- 同时取消了在 capture 阶段监听。capture 阶段监听无法处理嵌套场景。
处理办法参考 react issue ： https://github.com/facebook/react/issues/4335#issuecomment-421705171
🇨🇳 Chinese
- Fix: 修复 Popover 中嵌套 Select，点击 Select Option 会关闭 Popover 问题 #818
---
🇺🇸 English
- Fix: Fix the nested Select in Popover, click Select Option will close the Popover problem #818

fix(popover): select in popover close bug #818

---

lerna.json
packages/semi-animation-react/package.json
packages/semi-animation-react/src/Animation.tsx
packages/semi-ui/form/baseForm.tsx
packages/semi-ui/package.json
packages/semi-ui/table/Body/BaseRow.tsx

由于 React 18 createRoot的严格模式下，会触发 componentDidMount、componentWillUnmount两次（详见：https://github.com/reactwg/react-18/discussions/19）
如果我们在willUnmount时执行了某些清除操作（例如将this对象上的某个键值对清空），而在 didMount中未初始化或还原（在Form、semi-animation-react中这类操作是在constructor阶段完成的），在第二次render时，就会导致读取不到对应的状态，从而触发 error
- Form
- Tabs、Nav、SideSheet（用到了 @douyinfe/semi-animation-react的组件）
- semi-animation-react
- 在didMount中进行判断，当前是否已执行过清空操作（即是否第二次触发 mounted）。如果是，则对this对象进行相应还原
- form
- 直接去除 willUnmount 里对 foundation 的置null操作 （之前只是为了保险，这里去除理论无影响）
- Table 
- didMount里判断如果 cacheRowProps是undefined，就执行一次onRow + 写cache的操作
🇨🇳 Chinese
- Fix: 修复 React 18 createRoot + strictMode 严格模式下，使用 Form、Tabs、Nav 、SideSheet 、Table 组件时提示 …

Fix react18 strict mode error

---

packages/semi-ui/navigation/Item.tsx

Fixes #856
🇨🇳 Chinese
- Fix: 修复 Nav.Item['linkOptions'] 类型不正确
---
🇺🇸 English
- Fix: fix wrongly typed Nav.Item['linkOptions']

fix: wrong type of nav.item['linkOptions']

---

packages/semi-foundation/inputNumber/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 `InputNumber` 在 `readonly` 模式下可以用过步进器修改 `value`
---
🇺🇸 English
- Fix: Fix `InputNumber` `value` can be changed via stepper in `readonly` mode

fix(inputnumber): readonly value changed via stepper

---

packages/semi-foundation/tagInput/foundation.ts
packages/semi-ui/tagInput/index.tsx

- ref: https://github.com/DouyinFE/semi-design/issues/874#issue-1252633173
- 参照Input补充了insetLabel的逻辑，另外也添加了点击prefix和suffix的focus操作。
另外看代码的时候有一些疑问:
1. tagInput的`-icon`class的判断是只要传入的是Element且不是String即生效，这与semi-ui其它组件的判断不一致。比如在传入`<div>123</div>`的时候就会导致不一样的效果
https://github.com/DouyinFE/semi-design/blob/289182375457aa7baabf5ad20c532e33e10e87f7/packages/semi-ui/tagInput/index.tsx#L274
https://github.com/DouyinFE/semi-design/blob/289182375457aa7baabf5ad20c532e33e10e87f7/packages/semi-ui/input/index.tsx#L274
2. Input的prefixRef和suffixRef似乎没有用处，可以删掉
https://github.com/DouyinFE/semi-design/blob/289182375457aa7baabf5ad20c532e33e10e87f7/packages/semi-ui/input/index.tsx#L148-L149 …

feat: tagInput prefix insetLabel

---

packages/semi-foundation/inputNumber/foundation.ts
packages/semi-ui/inputNumber/__test__/inputNumber.test.js
packages/semi-ui/inputNumber/_story/inputNumber.stories.js

Fixes #
🇨🇳 Chinese
- Fix: 修复InputNumber如果设置了必填验证在表单中初始化时会触发验证，这与其他表单不一致
---
🇺🇸 English
- Fix: fix inputnumber will be validate when form init if it required

fix: (InputNumber) inputnumber will be validate when form init

---

content/input/inputnumber/index-en-US.md
content/input/inputnumber/index.md
cypress/integration/inputNumber.spec.js
packages/semi-foundation/inputNumber/constants.ts
packages/semi-foundation/inputNumber/foundation.ts
packages/semi-ui/inputNumber/_story/inputNumber.stories.js
packages/semi-ui/inputNumber/index.tsx

Feat related to #205
🇨🇳 Chinese
- Feat: InputNumber 新增 A11y 键盘适配，支持在输入框同时按住 shift 和上下箭头调整较大的数字范围
- Breaking Change：调整 shiftStep 默认值，由 1 调整为 10
---
🇺🇸 English
- Feat: Added A11y keyboard adaptation for InputNumber, which supports holding shift and up and down arrows at the same time in the input box to adjust a larger number range
- Breaking Change: Adjust the default value of shiftStep from 1 to 10

feat: inputNumber a11y keyboard #205

---

cypress/integration/select.spec.js
packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.js

Fixes #
🇨🇳 Chinese
- Fix: 修复 Select filter 、showClear 为 true 时，点击 clear icon时，只触发 onClear，未触发 onSearch 的问题及通过 clear icon 清除搜索项后，未重置候选Option列表的问题 #867
- Fix: 修复 Select filter 为true，失去焦点，input 输入被自动重置时，未触发 onSearch 的问题 #867
---
🇺🇸 English
- Fix: Fixed the problem that when Select filter and showClear are true, when clicking the clear icon, only onClear is triggered, but onSearch is not triggered, and after clearing the search item through the clear icon, the candidate Option list is not reset #867

fix: select onSearch, close #867

---

packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- Style: disabled的TagInput可以显示+N部分popover的内容
---
🇺🇸 English
- Style: the disabled TagInput can display the content of the +N part of the popover

style: the disabled taginput can display the content of the +N part

---

packages/semi-ui/cascader/index.tsx

…WithObject and multiple
Fixes #905
🇨🇳 Chinese
- Fix: 修复当设置onChangeWithObject，mutiple后，value传入的值为undefined时时，Cascader 崩溃的问题。（影响范围 v2.0.4 - v 2.12.0） #905
---
🇺🇸 English
- Fix:  Fixed the problem that Cascader crashes when the value passed in is undefined after setting onChange WithObject, multiple, #905

fix: [Cascader] fix typeError when value is undefined while onChangeWithObject and mutiple #905

---

packages/semi-foundation/tagInput/variables.scss

TagInput 与 Input 等其他输入类组件对齐，保持 suffix 与 prefix 相同颜色，都是 --semi-color-text-2
- 修改前
- 修改后
🇨🇳 Chinese
- Style: 修复 TagInput suffix 文本颜色，从 --semi-color-text-1 修改为 --semi-color-text-2
---
🇺🇸 English
- Style: Fix TagInput suffix text color, changed from --semi-color-text-1 to --semi-color-text-2

style: fix TagInput suffix color

---

packages/semi-foundation/list/list.scss
packages/semi-foundation/list/variables.scss

List 和Card一起使用时候 空状态padding超出容器了
🇨🇳 Chinese
- Fix: 修复 List 空状态 Padding 问题
---
🇺🇸 English
- Fix: fix list empty padding

fix(list): list empty padding

---

cypress/integration/cascader.spec.js
packages/semi-foundation/cascader/cascader.scss
packages/semi-foundation/cascader/foundation.ts
packages/semi-foundation/cascader/variables.scss
packages/semi-ui/cascader/__test__/cascader.test.js
packages/semi-ui/cascader/_story/cascader.stories.js
packages/semi-ui/cascader/index.tsx

…g filterTreeNode & displayRender at the same time
Fixes #
🇨🇳 Chinese
- Fix: 修复单选状态下同时设置filterTreeNode & displayRender，选项显示错误问题
---
🇺🇸 English
- Fix: fix the display error of single selection when setting filterTreeNode & displayRender at the same time
修复前
修复后

fix: [cascader] Fix the display error of single selection

---

packages/semi-ui/tree/index.tsx
packages/semi-ui/tree/treeNode.tsx
packages/semi-ui/treeSelect/_story/treeSelect.stories.js
packages/semi-ui/treeSelect/index.tsx

Fixes #750 
🇨🇳 Chinese
- Fix: 修复多选状态下的TreeSelect/Tree被CheckboxGroup包裹后，点击任何选项将所有选项显示为被选中的问题。
---
🇺🇸 English
- Fix: fixed the problem that when TreeSelect/Tree in multi-select state is wrapped by CheckboxGroup, clicking any option will cause all options to be displayed as selected.

fix: [treeSelect] fix TreeSelect/Tree is wrapped by CheckboxGroup, multiple selections and clicks on any item will be displayed as all selections #750

---

packages/semi-foundation/input/input.scss
packages/semi-foundation/input/textarea.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复Input 按下态颜色错误问题，修复Input和TextArea在validateStatus下按下态颜色不统一问题 #662 
---
🇺🇸 English
- Fix: fix the problem of wrong color in the pressed state of Input, and fix the problem that the colors of Input and TextArea are not uniform in the pressed state under validateStatus #662

fix: fix input's active background color and validate status's border color

---

packages/semi-ui/avatar/interface.ts

Fixes no 'default' in AvatarGroupSize TS value
🇨🇳 Chinese
- Fix: 修复 `AvatarGroup` 组件中 `size` 属性在 TS 定义中没有值 `default` 
---
🇺🇸 English
- Fix: fix `AvatarGroup` component `size` attribute has no `default` in TS define

fix: No 'default' in AvatarGroupSize TS value

---

packages/semi-foundation/switch/switch.scss

Fixes #992 
🇨🇳 Chinese
- Fix: 修复点击 switch 边缘无法触发 change 的问题
---
🇺🇸 English
- Fix: fix click on the edge of the switch can not trigger the change problem
造成这个问题的原因是因为，用来触发 change 事件的 input 的高度采用的 height 100%，而父元素有设置 1px 的 border，导致用户了 input 的高度会比 父元素少 2px，用户点击到时边缘时，会点击到父元素因此会有动画，但是并没有点击到 input，所以没有触发 change 事件，采用 inherit 就可以避免这个 border 造成的高度问题，可以看下面的前后高度对比

fix(switch): 解决点击 switch 边缘无法触发 change 的问题, resolve #992

---

packages/semi-foundation/input/input.scss

Fixes #1004 
🇨🇳 Chinese
- Fix: 修复 windows edge 浏览器 password input 默认 icon 的问题
---
🇺🇸 English
- Fix: fix ...
按照 issue 的解法实现，已经验证了 windows edge 浏览器可修复

fix(input): 修复 windows edge 浏览器 password input 默认 icon 的问题

---

content/input/form/index-en-US.md
content/input/form/index.md
content/input/taginput/index-en-US.md
content/input/taginput/index.md
packages/semi-foundation/tagInput/foundation.ts
packages/semi-foundation/tagInput/tagInput.scss
packages/semi-foundation/tagInput/variables.scss
packages/semi-foundation/transfer/foundation.ts
packages/semi-foundation/utils/arrayMove.ts
packages/semi-ui/tagInput/_story/tagInput.stories.js
packages/semi-ui/tagInput/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: TagInput 支持拖拽排序。
---
🇺🇸 English
- Feat: TagInput supports drag and drop sorting.
新增两个API，draggable 和 expandRestTagsOnClick。
draggable用于设置是否可拖拽， 默认false；
expandRestTagsOnClick用于在不可拖拽的情况下，在 TagInput 被点击后是否展开多余的 Tag， 默认为true。

feat: [TagInput] Support drag and drop sorting

---

packages/semi-ui/empty/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Empty 组件在 body theme-mode attribute 为非预期值时意外判定为暗色模式的问题
---
🇺🇸 English
- Fix: Fix the problem that the Empty component is unexpectedly judged as dark mode when the body theme-mode attribute is unexpected

fix: Empty component darkmode judge, fix #1023

---

packages/semi-ui/empty/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Empty 组件在 body theme-mode attribute 为非预期值时意外判定为暗色模式的问题
---
🇺🇸 English
- Fix: Fix the problem that the Empty component is unexpectedly judged as dark mode when the body theme-mode attribute is unexpected

fix: Empty component darkmode judge

---

packages/semi-ui/checkbox/checkbox.tsx

Fixes # 
🇨🇳 Chinese
- Fix: 修复Tree的renderFullLabel使用checkbox出现的问题
---
🇺🇸 English
- Fix: fix the problem that Tree's renderFullLabel uses checkbox
问题：在修复 #750 时候给tree/treeSelect的多选状态下加了一层checkboxGroup，当用户使用renderFullLabel时候传入的checkbox中没有value，会导致无法选中。
修改方法： 对于checkbox，判断是否在group中的条件增加一项 'value' in this.props，如果checkbox中没有value参数，则认为checkbox不属于checkbox，是否选中的状态不受checkboxGroup的影响。

fix: [Tree] solve the problem of using checkbox in renderFullLabel

---

packages/semi-foundation/select/option.scss

Fixes #1003 
🇨🇳 Chinese
- Fix: 修复 select 勾选 icon 会闪烁的问题
---
🇺🇸 English
- Fix: fix ...
https://user-images.githubusercontent.com/78683712/183086030-7343162b-7c12-4c91-95cb-04f514685b65.mp4
https://user-images.githubusercontent.com/78683712/183086184-5403dca8-3189-4a14-978c-b13e1ff292c4.mp4
这个问题是因为 icon 的隐藏使用的是 visibility 来控制，导致了这个问题出现，采用 display 可以解决这个问题

fix: 修复 select 勾选 icon 会闪烁的问题

---

packages/semi-ui/form/baseForm.tsx

由于 React 18 createRoot的严格模式下，会触发 componentDidMount、componentWillUnmount两次（详见：https://github.com/reactwg/react-18/discussions/19%EF%BC%89
如果我们在willUnmount时执行了某些清除操作（例如将this对象上的某个键值对清空），而在 didMount中未初始化或还原（在Form、semi-animation-react中这类操作是在constructor阶段完成的），在第二次render时，就会导致读取不到对应的状态，从而触发 error
🇨🇳 Chinese
- Fix: 修复 React 18 createRoot + strictMode 严格模式下， 使用 useFormApi 得到空值问题 #1063 
---
🇺🇸 English
- Fix: fix  use useFormApi to get null value problem under React 18 createRoot + strictMode #1063

fix: fix the problem when react 18 and strict mode useFormApi get null

---

cypress/integration/tabs.spec.js
packages/semi-ui/tabs/TabBar.tsx

Fixes #1039 
详细修复过程看这里～https://bytedance.feishu.cn/docx/doxcndFl24VU3Gl7Kthxxtc2Cjf
bug表现可见视频：https://lf3-static.bytednsdoc.com/obj/eden-cn/slepweh7nupqpognuhbo/41209.mp4
可折叠tabs底层依赖的是Semi的`OverflowList`，`OverflowList`在滚动（scroll）模式下依赖于`IntersectionObserver`。`IntersectionObserver`对象在其监听到目标元素的可见部分穿过了一个或多个`thresholds`时，会执行指定的回调函数，默认的`threshold`为0.75。
在`OverflowList`内每当有目标元素的可见部分超过或者低于`threshold`时，就会触发对元素数组`visibleState`的重新评估。我们根据该数组第一个和最后一个可见元素的位置，将元素数组分为两个部分，分别代表左侧不可见元素和右侧不可见元素。
在tabBar侧，我们会根据左右不可见元素数组的长度判断是否渲染箭头按钮。
所以**反复横跳**的横跳过程大概如下图所示
只要可折叠tabs的箭头是动态渲染的，这个“反复横跳”的问题就必然存在。题解真正的奥义就是让icon按钮常驻，无遮挡元素时禁用按钮。
Solution: Make the icon button permanent, and disable the button when …

fix: make collapse icon fixed to avoid the collapse tabs flush in some width

---

packages/semi-foundation/button/button.scss
packages/semi-foundation/button/variables.scss
packages/semi-ui/button/buttonGroup.tsx
packages/semi-ui/button/index.tsx

ButtonGroup 中的分割线使用 span 标签代替 border-right
🇨🇳 Chinese
- Refactor: ButtonGroup 中的分割线使用 span 标签代替 border-right
---
🇺🇸 English
- Refactor: Use span tag instead of border-right as divider in ButtonGroup

refactor: button group line

---

packages/semi-ui/tag/interface.ts

类型声明重复
Type `TagGroupProps` has been defined in `packages/semi-ui/tag/group.tsx`.So the type in "interface.ts" with Todoes is useless and duplicate.
🇨🇳 Chinese
- chore:删除了一个重复类型
---
🇺🇸 English
- chore:remove a duplicate type.

chore: remove a duplicate type

---

packages/semi-foundation/datePicker/monthsGridFoundation.ts

Fixes #1078
🇨🇳 Chinese
- Fix: 修复 当 datepicker 的type为dateTime时，切换年月会导致时间部分被重置为8点 
---
🇺🇸 English
- Fix: fix DatePicker time will be set 8:00 when switch month and type is dateTime

fix: (DatePicker) time will be set 8:00 when switch month and type is dateTime

---

packages/semi-foundation/dropdown/foundation.ts
packages/semi-foundation/dropdown/menuFoundation.ts
packages/semi-ui/dropdown/index.tsx
packages/semi-ui/tooltip/index.tsx

Fixes #1102 
🇨🇳 Chinese
- Fix: 修复在 DropDown 中使用 Input，Input onEnterPress 事件不生效问题
---
🇺🇸 English
- Fix:  fix the problem that Input onEnterPress event does not take effect when using Input in DropDown

fix: fix the trigger in dropdown do not response the enter press problem

---

packages/semi-foundation/calendar/eventUtil.ts
packages/semi-foundation/calendar/foundation.ts
packages/semi-ui/calendar/_story/calendar.stories.js

Fixes #1101
🇨🇳 Chinese
- Fix: 修复 Calendar weekStartsOn 改变后，事件渲染的位置没有跟着改变问题
---
🇺🇸 English
- Fix: fix the problem that the location of event rendering did not change after Calendar weekStartsOn was changed

fix: fix event render didn't change with weekStartsOn

---

packages/semi-foundation/anchor/anchor.scss
packages/semi-foundation/anchor/rtl.scss
packages/semi-ui/anchor/index.tsx
packages/semi-ui/anchor/link.tsx

Fixes #512  Anchor spacing in front of anchor text cannot trigger selection
🇨🇳 Chinese
- Fix: 修复锚点组件的子节点单行文本前面的空白处，点击不能选中的问题
---
🇺🇸 English
- Fix: fix Anchor spacing in front of anchor text cannot trigger selection

fix: Anchor spacing in front of anchor text cannot trigger selection

---

packages/semi-foundation/anchor/anchor.scss
packages/semi-foundation/anchor/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 Anchor 间距可触发选中后，键盘聚焦样式被遮挡问题
---
🇺🇸 English
- Fix: fix the issue that the keyboard focus style is blocked after the Anchor spacing can trigger the selection

fix: after update the anchor click area, a11y offset should be internal

---

content/show/dropdown/index-en-US.md
content/show/image/index-en-US.md
content/show/image/index.md
packages/semi-foundation/image/image.scss
packages/semi-foundation/image/previewImageFoundation.ts
packages/semi-foundation/image/previewInnerFoundation.ts
packages/semi-foundation/image/utils.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Image 预览放大后拖拽问题
---
🇺🇸 English
- Fix: fix the drag and drop problem after the Image preview is enlarged
本次提交的PR修改包含的内容：
1. 之前使用 pageX 计算拖拽后偏移的处理方式不太合理，pageX = clientX + 滚动条的距离，因此该用ClientX进行计算
2. Image 的 API 没有顺序没有根据字母顺序排列

Fix: [Image] fix the drag and drop problem after the Image component is enlarged

---

packages/semi-foundation/form/form.scss
packages/semi-ui/form/_story/Layout/layoutDemo.jsx
packages/semi-ui/form/group.tsx

🇨🇳 Chinese
- Fix: 修复 Form.InputGroup 不支持 FormProps.wrapperCol 、 labelCol 布局的问题
---
🇺🇸 English
- Fix: fix the issue that Form.InputGroup not supported FormProps's wrapperCol、labelCol

fix: form inputGroup not response with formProps.wrapperCol & labelCol

---

content/input/autocomplete/index-en-US.md
content/input/autocomplete/index.md
packages/semi-foundation/autoComplete/foundation.ts
packages/semi-ui/autoComplete/_story/autoComplete.stories.js
packages/semi-ui/autoComplete/index.tsx

🇨🇳 Chinese
- Feat: AutoComplete 新增 onKeyDown API
---
🇺🇸 English
- Feat: AutoComplete add new API onKeyDown

add onkeydown to AutoComplete

---

packages/semi-ui/dropdown/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Drodown 下 children onKeydown 拿不到事件问题
---
🇺🇸 English
- Fix: fix the problem that children onKeydown cannot get events under Drodown

fix: dropdown onkeydown get null event

---

packages/semi-foundation/autoComplete/foundation.ts

Fixes #1172 
🇨🇳 Chinese
- Fix: 修复 AutoComplete 在 onBlur 回调中 e.target 是 null 的问题 #1172 
---
🇺🇸 English
- Fix: fix AutoComplete e.target is null in onBlur callback #1172 
修复后

fix: [AutoComplete] Fix AutoComplete e.target is null in onBlur callback

---

packages/semi-foundation/autoComplete/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 AutoComplete 在 onBlur 回调中 e.target 是 null 的问题
---
🇺🇸 English
- Fix: fix AutoComplete e.target is null in onBlur callback
该修改的 commit 已经合入 main 分支，但是提 issue 的用户同时使用了2.21.0-beta版本上的一个 feature，因此再合入 release， 发个patch

fix: [AutoComplete] Fix AutoComplete e.target is null in onBlur callback 

---

content/input/select/index-en-US.md
content/input/select/index.md
content/start/changelog/index-en-US.md
content/start/changelog/index.md
packages/semi-foundation/select/constants.ts
packages/semi-foundation/select/option.scss
packages/semi-foundation/select/select.scss
packages/semi-foundation/select/variables.scss
packages/semi-ui/form/interface.ts
packages/semi-ui/select/index.tsx
yarn.lock

Before：
After：
原有方案，将边距放置于 first option、last option的 margin。在虚拟化列表中，会导致第一个 option 移位。
改进方案，将边距由margin改为 padding，位置由option改为 optionList 的父级 wrapper
🇨🇳 Chinese
- Fix: 修复 Select 虚拟化时，第一个 Option 选项位置偏移的问题
- Style: 
- Select Option 浮层最小高度由 300px  -> 270px;  
- 废弃 $spacing-select_option_first-marginTop、$spacing-select_option_last-marginBottom 两个 Token ；
- 修改 以下 Token 默认值：$spacing-select_option_list-paddingTop 、$spacing-select_option_list-paddingBottom ， 0 -> $spacing-extra-tight (4px)
---
🇺🇸 English
- Fix: fix ...

Style:  Update select option list padding

---

packages/semi-foundation/modal/modalContentFoundation.ts
packages/semi-ui/modal/ModalContent.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Modal 在 关闭后 esc 触发事件回调的问题。
---
🇺🇸 English
- Fix: fix Modal esc key trigger event callback after closed.

fix: fix modal esc trigger close callback after close

---

content/input/datepicker/index-en-US.md
content/input/datepicker/index.md
cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/foundation.ts
packages/semi-ui/datePicker/_story/v2/DisabledRange.tsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/month.tsx

DatePicker disabledDate API 第二个参数新增 rangeInputFocus 参数，用于根据当前选择状态动态禁用日期
🇨🇳 Chinese
- Feat: DatePicker disabledDate API 第二个参数新增 rangeInputFocus 参数，用于根据当前选择状态动态禁用日期
---
🇺🇸 English
- Feat：The second parameter of DatePicker disabledDate API adds the rangeInputFocus parameter to dynamically disable the date based on the current selection state
代码示例
```js
function App() {
const today = new Date('2021-10-20');
const disabledDate: DisabledDateType = (date, options) => {
const { rangeInputFocus } = options;
const baseDate = dateFns.set(today, { hours: 0, minutes: 0, seconds: 0, milliseconds: 0 });
if (rangeInputFocus === 'rangeStart') {
const disabledStart = dateFns.subDays(baseDate, …
```

feat: disabledDate add rangeInputFocus to second params

---

packages/semi-foundation/cascader/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复cascader中搜索后弹窗关闭闪烁问题
---
🇺🇸 English
- Fix: fix the flickering problem when the pop-up window closes after searching in Cascader
Tooltip / Popover 中的 afterClose 中在弹窗关闭后的更新 isSearch 为false，可以实现关闭面板时候不闪烁同时在再次打开面板时候，数据正确

Fixed the flickering problem when the pop-up window closes after searching in Cascader

---

content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.jsx
packages/semi-ui/select/index.tsx
packages/semi-ui/tag/group.tsx
packages/semi-ui/tag/index.tsx
packages/semi-ui/tag/interface.ts

Fixes #
🇨🇳 Chinese
- Feat:  在 Select 中增加 showRestTagsPopover 和 restTagsPopoverProps，支持通过 popover 展示多余 tag
---
🇺🇸 English
- Feat: Added showRestTagsPopover and restTagsPopoverProps to support displaying redundant tags through popover

Feat: [Select] Added showRestTagsPopover and restTagsPopoverProps to support displaying redundant tags through popover

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/cascader/index.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- Feat: TreeSelect 增加 showRestTagsPopover 和 restTagsPopoverProps 参数，支持通过popover展示多余tag
---
🇺🇸 English
- Feat: TreeSelect adds showRestTagsPopover and restTagsPopoverProps parameters to support displaying redundant tags through popover

Feat: [TreeSelect] adds showRestTagsPopover and restTagsPopoverProps parameters

---

packages/semi-ui/modal/Modal.tsx
packages/semi-ui/modal/useModal/HookModal.tsx

Fixes #
修复 modal afterClose 在 js2css 改造时 在有动画时执行时机提前的问题，因 js2css 尚未发包，无需 changelog
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: fix modal afterClose exec time

---

packages/semi-foundation/datePicker/datePicker.scss
packages/semi-foundation/datePicker/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 DatePicker type="month" 下 年月选择模式为 normal 和 wheel 时， 宽度不一致问题
---
🇺🇸 English
- Fix: fix the issue of inconsistent width when the year-month selection mode is normal and wheel under DatePicker type="month"

fix: datepicker make the same width under wheel and normal mode

---

packages/semi-ui/locale/source/tr_TR.ts

weeks: { Mon: 'Pzt', Tue: 'Salı', Wed: 'Çar', Thu: 'Perş', Fri: 'Cum', Sat: 'Cmt', Sun: 'Paz' }
for extample : https://translate.google.com.tr/?sl=en&tl=tr&text=Saturday%20and%20Sunday&op=translate
Fixes #
🇨🇳 Chinese
- Fix: 更正 DatePicker 在土耳其语（tr_TR）展示时周六、周日翻译的文本
---
🇺🇸 English
- Fix: Corrected Saturday, Sunday translated text of DatePicker when displayed in Turkish (tr_TR)

Day name an incorrect use

---

cypress/integration/carousel.spec.js
packages/semi-foundation/navigation/navigation.scss
packages/semi-ui/navigation/Item.tsx
src/components/side-nav.js
src/styles/doc.scss

Fixes #1234
🇨🇳 Chinese
- Fix: 修复 Navigation item 在有参数 link 情况下跳转链接热区与 onSelect 热区不一致问题
---
🇺🇸 English
- Fix: fix the inconsistency between the jump link hotspot and the onSelect hotspot when the Navigation item has a parameter link

fix: fix the wrong padding in navigation link

---

packages/semi-ui/locale/source/vi_VN.ts

I see this string template has the wrong format.
Fixes #
🇨🇳 Chinese
- Fix: 修复Table 分页器越南语文本翻译错误问题
---
🇺🇸 English
- Fix: Fix table pager text translation error in vi_VN locale

[Localize] Update format string template for pagination

---

packages/semi-foundation/form/form.scss
packages/semi-foundation/form/rtl.scss
packages/semi-foundation/form/variables.scss

1. 更正 form  component token的中文描述; 
2. `$spacing-form_label_small-paddingTop` 命名不规范，实际并非作用于label，而是 swithc、rating上，用于实现与其他 field component高度对齐，修改为 `$spacing-form_switch_rating_marginY`
3. 去掉无实际作用的 token `$spacing-form_label-paddingRight`
🇨🇳 Chinese
- docs: Form  component token 给予更准确的描述
---
🇺🇸 English
- Fix: fix ...

style: fix incorrect token name of form; update token comment

---

packages/semi-foundation/dropdown/foundation.ts
packages/semi-foundation/dropdown/menuFoundation.ts
packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/datePicker/yearAndMonth.tsx
packages/semi-ui/dropdown/dropdownMenu.tsx
packages/semi-ui/dropdown/index.tsx
packages/semi-ui/tooltip/index.tsx

Fixes # 1254
🇨🇳 Chinese
- Fix: 修复 Dropdown 在 trigger 为 click 时，会触发屏幕滚动到顶部问题
---
🇺🇸 English
- Fix: fixed the issue that Dropdown would trigger the screen to scroll to the top when the trigger is click
- [x Test or no need

fix: fix click dropdown make screen scroll after tooltip add off screen render

---

packages/semi-foundation/input/foundation.ts
packages/semi-ui/input/index.tsx

- React 17/18 在 nextjs ssr场景下使用 input会有不同表现；报错中的 padingLefft属于 input state，但经过查阅调用链，现在已经没有代码调用该 adapter，应该是可以移除的代码。移除后预期即可解决报错问题。
🇨🇳 Chinese
- Fix: 修复 Next Js项目 在 React 18 下使用 Input 组件关于 style props 报错的问题, #1262 
---
🇺🇸 English
- Fix: fix ...

fix: remove useless setPaddingLeft call in input, close #1262, 1181

---

.vscode/launch.json
packages/semi-foundation/select/foundation.ts
packages/semi-foundation/utils/Event.ts
packages/semi-ui/select/_story/select.stories.jsx
packages/semi-ui/select/index.tsx

修复 Select 单选模式下，filter 为true，当前如果进行了搜索筛选，点击选择后，收起Options列表的同时，由于Options列表重置内容更新，导致看起来会闪烁一次的问题
单选点击后存在以下调用链
- foundation.handleSingleSelection  -> this.close -> clearInput ->  updateOptions (因为input变化了，所以需要重置下拉列表中的筛选结果) 
由于存在收起动画，close 与 updateOptions 并不是严格的先后顺序，所以 close的动画未执行完， updateOptions已经更新了，导致的闪烁。
- 将 close中 的 clearInput 操作延迟，在动画结束回调后再执行
- 受控模式下，原有逻辑：close调用后立即执行  notifyChange -> close调用后，动画结束再执行 notifyChange
- 非受控模式，将 uptionOptions 放在close动画结束回调中执行，而 notifyChange、updateSelection 等逻辑不变
🇨🇳 Chinese
- Fix: 修复 Select 单选模式下，filter 开启情况下，点击选择收起列表时，会闪烁一次的问题 #1207
---
🇺🇸 English
- Fix: Fix the issue that in the Select radio mode, when the filter is enabled, when you click to …

fix: single select will flush when filter is true, close #1207

---

packages/semi-foundation/image/previewInnerFoundation.ts
packages/semi-ui/image/__test__/imagePreview.test.js
packages/semi-ui/image/previewInner.tsx
packages/semi-ui/modal/Modal.tsx

Fixes #1273 
🇨🇳 Chinese
- Feat: 新增 Image组件在预览图片的时候，鼠标滚轮事件会穿透弹层，但是弹层之下的内容不能被滚动的特性。
---
🇺🇸 English
- Feat: add the feature that when previewing images, the mouse wheel event penetrates the pop-up layer, and the content below the pop-up layer cannot be scrolled

fix: [Image] prevent sliding pages when previewing pictures

---

packages/semi-ui/tabs/TabBar.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Tabs 折叠滚动情况下，因为 scrollIntoView 参数带来的过多页面滚动干扰
---
🇺🇸 English
- Fix: fix the excessive page scrolling interference caused by the scrollIntoView parameter when Tabs is collapsed and scrolled

fix: change the scrollIntoView inline parameter to align the behavior in arrow and item click

---

packages/semi-foundation/switch/switch.scss

- React本身对于 disabled input/ button 只会触发 onMouseEnter、不会触发 onMouseLeave [4251](https://github.com/facebook/react/issues/4251)，在 disabled switch 被 Tooltip包裹的情况下，虽然tooltip已经自动 wrap了一个span元素 在外层，并且 onMouseEnter、onMouseLeave等事件监听器也是加在 span上的。但由于 disabled input 的宽高 与 span 完全相等。此时 span 依然无法触发 onMouseLeave事件
- 仅在chrome和 safari下无法触发，在火狐下一切正常（即火狐下不存在该bug）
- 如果我们将span的padding从0 -> 任意正数，此时onMouseLeave 是可以触发的
- 对 disabled input增加 point-event: none 与 cursor: not-allowed。让span的事件监听能正常工作
🇨🇳 Chinese
- Fix: 修复 disabled switch 被 Tooltip或 Popover等组件包裹，且trigger为hover时，在chrome浏览器下，鼠标移开后未能正确隐藏的问题
---
🇺🇸 English
- Fix: Fix the problem that when the disabled switch is wrapped by components such as …

fix: disabled  switch can't trigger mouseLeave, tooltip can't hide

---

packages/semi-foundation/grid/grid.scss

Fixes #1314 
🇨🇳 Chinese
- Fix: 修复Grid组件span设置为0，在响应式模式下异常显示的问题
---
🇺🇸 English
- Fix: fix the problem that the Grid component span is set to 0 and displays abnormally in response mode

fix: Grid span = 0 not work when responsive

---

packages/semi-ui/typography/util.tsx

Fixes #621 
🇨🇳 Chinese
- Fix: 修复空字符串但没有达到最大宽度时，却展示了"展开/折叠"按钮及省略号
---
🇺🇸 English
- Fix: An empty string that has not reached its maximum width shows an "expand/collapse" button and an ellipsis

fix: [Typography] ellipsis is hidden for empty strings

---

packages/semi-foundation/tagInput/foundation.ts
packages/semi-ui/tagInput/_story/tagInput.stories.jsx
packages/semi-ui/tagInput/index.tsx

Fixes #1347 
🇨🇳 Chinese
- Fix: 修复 TagInput 在中文输入时，会将拼音的长度用于判断是否超出 maxLength 的问题 #1347 
---
🇺🇸 English
- Fix: fix the problem that when TagInput is input in Chinese, the length of pinyin will be used to judge whether it exceeds maxLength #1347

fix: [TagInput] Fix max Length judgment is wrong in composition input

---

packages/semi-ui/tabs/TabBar.tsx

Fixes #1351 
🇨🇳 Chinese
- Fix: 修复 SSR 场景下 TabBar 中的 uuid 不匹配警告 #1351 
---
🇺🇸 English
- Fix: fix uuid mismatch warning in TabBar in SSR scenario #1351

fix: [Tabs] fix TabBar does not match string warning in SSR

---

packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/index.tsx

修复 Select 在配置了 outerBottomSlot、outTopSlot、innerBottomSlot、innerTopSlot 时，hover到slot中，Option仍保持 focus 样式的问题
🇨🇳 Chinese
- Fix: 修复 Select 在配置了 outerBottomSlot、outTopSlot、innerBottomSlot、innerTopSlot 后，hover到slot中，Option 仍保持 focus 样式，易使用户产生疑惑的问题
---
🇺🇸 English
- Fix: Fix the problem that after Select is configured with outerBottomSlot, outTopSlot, innerBottomSlot, and innerTopSlot, when hovering to the slot, the Option still maintains the focus style, which easily confuses users

fix: [select] remove option focus style when hover slot

---

content/show/modal/index.md
packages/semi-foundation/base/foundation.ts
packages/semi-foundation/modal/modalFoundation.ts
packages/semi-ui/modal/Modal.tsx

Fixes #
🇨🇳 Chinese
- Feat: 声明式使用 Modal 时，可通过 onOK onCancel 返回 promise 来自动控制对应按钮的 loading 态
---
🇺🇸 English
- Fix: When using Modal declaratively, you can automatically control the loading state of the corresponding button by returning a promise through onOK and onCancel

feat: modal declarative promise

---

packages/semi-webpack/README.md
packages/semi-webpack/src/semi-webpack-plugin.ts

Fixes #
🇨🇳 Chinese
- Feat: webpack 插件新增 overrideLoaderList 选项，支持更细粒度自定义 semi 相关样式所用 loaders
---
🇺🇸 English
- Feat: The webpack plugin adds an overrideLoaderList option to support finer-grained customization of the loaders used in semi-related styles

[Plugin] feat: add overrideLoaderList to webpack plugin

---

packages/semi-foundation/base/foundation.ts
packages/semi-ui/layout/Sider.tsx
packages/semi-ui/layout/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Layout 挂载 has-sider className 慢一个任务周期的问题, #1361 
---
🇺🇸 English
- Fix: Fix the problem that Layout mount has-sider className is slow by one task cycle

[layout] Fix layout mount sider class delay

---

packages/semi-ui/overflowList/_story/overflowList.stories.jsx
packages/semi-ui/overflowList/index.tsx

Fixes #1362 
visibleState 用来标识每个item当前的可见状态。修改前仅在 foundation 中的 `handleIntersect` 有调用函数 `updateVisibleState` 更新 visibleState 的值。
如若一开始 props.items 传入两个 item ，key 为 'item1' 与  'item2'，visibleState 则为 { 'item1' => true, 'item2' => true }，而后修改items为 'newItem1'与 'newItem2'，**当纵向滚动使得 OverflowList 内的item上半部分被一半以上时，会调用 `handleIntersect` 函数**，此时 visibleState 变为{ 'item1' => true, 'item2' => true, 'newItem1' => false, 'newItem2' => false  }。造成 OverflowList 靠近顶部后，溢出部分 items 数量不符合预期问题
🇨🇳 Chinese
- Fix: 修复  OverflowList items 改变后靠近顶部溢出部分 items 数量不符合预期问题 #1362 
---
🇺🇸 English
- Fix: fix the problem that the number of items in the overflow part near the top after the OverflowList items are …

fix: OverflowList change items props and scroll vertically to be cover bring the wrong overflow item

---

packages/semi-foundation/timePicker/timePicker.scss
packages/semi-foundation/timePicker/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 TimePicker 选择模式为 normal 和 wheel 时， 滚动条表现不一致问题
---
🇺🇸 English
- Fix: fix the problem that the scroll bar behaves inconsistently when the TimePicker selection mode is normal and wheel

fix: timepicker make the same width under wheel and normal mode

---

packages/semi-foundation/input/input.scss

Fixes #1395 
Input Group 包裹的 not last child select 右侧会有一个分割线，在 overflow-y auto 的属性的影响下导致 select 中出现滚动条。一般情况下，Input Group 的用法不会出现使用多行 select 的情况，所以做了一个内部的样式覆盖解决问题。
🇨🇳 Chinese
- Fix: 修复 Input grou下 Select出现 不符合预期的滚动条
---
🇺🇸 English
- Fix: fix the scroll bar that does not meet expectations when Select appears under the Input group

fix: The non-last child select under the input group has an unexpected scroll bar

---

packages/semi-ui/datePicker/__test__/datePicker.test.js
packages/semi-ui/slider/__test__/__snapshots__/slider.test.js.snap
packages/semi-ui/slider/__test__/slider.test.js
packages/semi-ui/tooltip/index.tsx

mouseEnterDelay和mouseLeaveDelay应仅对trigger为hover和focus的trigger生效。在visible变化时，老代码没有检测trigger，直接调用了delayShow/delayHide（使用到了mouseEnterDelay和mouseLeaveDelay）
🇨🇳 Chinese
- Fix: 修复 visible 属性变化时，trigger 不为 hover 和 focus 的 tooltip 也延迟了展示/隐藏
---
🇺🇸 English
- Fix: fix when the visible prop changes, tooltips whose trigger is not hover/focus also delay showing/hiding

fix: [Tooltip] modify delay visible logic in componentDidUpdate

---

packages/semi-foundation/datePicker/monthsGridFoundation.ts

Fixes #1398 引入的 bug，面板更新没考虑年份 => 年月都不匹配时，更新面板日期
🇨🇳 Chinese
- Fix: 修复 DatePicker 输入日期后面板未更新问题 #1398
---
🇺🇸 English
- Fix: Fix the problem that the DatePicker panel is not updated after entering the date #1398

fix: [DatePicker] fixed input date not show panel bug #1398

---

content/other/locale/index-en-US.md
content/other/locale/index.md
packages/semi-ui/locale/_story/locale.stories.jsx
packages/semi-ui/locale/interface.ts
packages/semi-ui/locale/source/ar.ts
packages/semi-ui/locale/source/de.ts
packages/semi-ui/locale/source/en_GB.ts
packages/semi-ui/locale/source/en_US.ts
packages/semi-ui/locale/source/es.ts
packages/semi-ui/locale/source/fr.ts
packages/semi-ui/locale/source/id_ID.ts
packages/semi-ui/locale/source/it.ts
packages/semi-ui/locale/source/ja_JP.ts
packages/semi-ui/locale/source/ko_KR.ts
packages/semi-ui/locale/source/ms_MY.ts
packages/semi-ui/locale/source/nl_NL.ts
packages/semi-ui/locale/source/pl_PL.ts
packages/semi-ui/locale/source/pt_BR.ts
packages/semi-ui/locale/source/ro.ts
packages/semi-ui/locale/source/ru_RU.ts
packages/semi-ui/locale/source/sv_SE.ts
packages/semi-ui/locale/source/th_TH.ts
packages/semi-ui/locale/source/tr_TR.ts
packages/semi-ui/locale/source/vi_VN.ts
packages/semi-ui/locale/source/zh_CN.ts
packages/semi-ui/locale/source/zh_TW.ts
packages/semi-ui/pagination/index.tsx
src/templates/scope.js

1、增加三类语种的支持 （其中波兰语的单复数也较特殊）
2、需要优化已有的三种语言对于单复数形式的翻译， 详情见文档https://bytedance.feishu.cn/docx/DZXKdLqbioCrrcxJGSAcjyz6n2d
- 1. 俄语  ru_RU
- 2. 阿拉伯语 ar
- 3. 罗马尼亚语 ro 
- 复数文本涉及组件包括：
- Pagination.pageSize （需要将原来的展示语序变动，因此对部分组件的 locale.token 结构需要做变更）
- pagination.total （需要将原来的展示语序变动，因此对部分组件的 locale.token 结构需要做变更）
- Calendar.ramining （对上述三个语种的翻译文本调整即可，token结构不变）
- Transfer.total、Transfer.selected （对上述三个语种的翻译文本调整即可，token结构不变）
🇨🇳 Chinese
- Feat:   Locale 增加瑞典语: sv_SE、波兰语: pl_PL 、荷兰语: nl_NL支持 #1410 
- Fix：优化 俄语、阿拉伯语、罗马尼亚语种单复数文本显示问题
---
🇺🇸 English
- Feat:  Locale add Swedish: sv_SE、 Polish: pl_PL、Dutch: nl_NL #1410

feat: add i18n locale source, #1410

---

packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss

通过以下 token 色值的修改统一 Table 在亮暗色模式下的颜色表现
1. 将 token $color-table_body-bg-default 和 $color-table-bg-default 值从 var(--semi-color-bg-2) 改为 var(--semi-color-bg-1)
2. 将 token $color-table_th-bg-default 值从 transparent 改为 var(--semi-color-bg-1)
Unify the color performance of Table in light and dark mode by modifying the following token color values
1. Change token $color-table_body-bg-default and $color-table-bg-default value from var(--semi-color-bg-2) to var(--semi-color-bg-1)
2. Change token $color-table_th-bg-default value from transparent to var(--semi-color-bg-1)
修改前（before）
修改后（after）
🇨🇳 Chinese
- Design Token: Table Design Token 变更，修改以下 Token 默认值：$color-table_body-bg-default …

fix: change table bg color to fit dark mode

---

content/input/button/index-en-US.md
content/show/popover/index-en-US.md

- Fix English documentation of semi-design
🇨🇳 Chinese
- Fix: [Popover] position 的 optional value 是错的
- Fix: [Button] type 的 value 里有一个无效的 optional value
---
🇺🇸 English
- Fix: [Popover] position properties optional value is incorrect
- Fix: [Button] type properties has an invalid value (changed from `late` to `tertiary`)

Docs: Corrected english documentation

---

packages/semi-foundation/tag/tag.scss

Fixes # 
🇨🇳 Chinese
- Style: solid Tag 关闭按钮增加 hover 态颜色 var(--semi-color-white）和 active 态颜色 var(--semi-color-white)(opacity 0.9)，default 颜色从 var(--semi-color-white）改为 var(--semi-color-white)(opacity 0.8)。
---
🇺🇸 English
- Style: Solid Tag close button adds hover state color var(--semi-color-white) and active state color var(--semi-color-white)(opacity 0.9), default color from var(--semi-color-white) Change to var(--semi-color-white)(opacity 0.8).

fix: add solid tag hover and active color

---

cypress/integration/treeSelect.spec.js
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 TreeSelect 中 onBlur/onFocus 调用时机错误问题
- Fix: 修复 TreeSelect 中 preventScroll 未声明及未透传问题
---
🇺🇸 English
- Fix: fix the wrong timing of onBlur/onFocus calls in TreeSelect
- Fix: fix the problem that preventScroll is not declared and not transparently transmitted in TreeSelect

Fix/onblur: fix the wrong timing of onBlur/onFocus calls in TreeSelect

---

packages/semi-ui/modal/confirm.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Modal 在命令式调用时，danger type 底部按钮颜色不正确的问题，影响范围 v2.0.0 - v2.30.1
---
🇺🇸 English
- Fix: Fix the problem that the color of the button at the bottom of the danger type is incorrect when Modal is called imperatively

fix: modal danger type button color

---

.storybook/base/base.js
content/other/configprovider/index-en-US.md
content/other/configprovider/index.md
content/show/table/index-en-US.md
content/show/table/index.md
packages/semi-foundation/table/rtl.scss
packages/semi-foundation/table/table.scss
packages/semi-foundation/table/utils.ts
packages/semi-ui/configProvider/_story/RTLDirection/RTLWrapper.tsx
packages/semi-ui/table/Body/index.tsx
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/TableCell.tsx
packages/semi-ui/table/TableContextProvider.tsx
packages/semi-ui/table/TableHeaderRow.tsx
packages/semi-ui/table/_story/RTL/ColumnAlign.tsx
packages/semi-ui/table/_story/RTL/Direction.jsx
packages/semi-ui/table/_story/RTL/index.jsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/columnAlign.tsx
packages/semi-ui/table/index.tsx
packages/semi-ui/table/interface.ts
packages/semi-ui/table/table-context.ts

fix：fixed  #1471，参考了 MUI align 自动切换行为，https://mui.com/material-ui/guides/right-to-left/
feat：新增了 direction prop，用于控制 Table 的 RTL 表现，默认 direction 值从 configProvider 读取，Table direction 设置后优先级更高
🇨🇳 Chinese
- Fix: 修复 Table column align 在 RTL 时未自动切换问题 #1471
- Feat：Table 固定列支持 RTL，Table 支持 direction prop #1471
---
🇺🇸 English
- Fix: fixed the problem that Table column align does not automatically switch when RTL #1471
- Feat: Table fixed columns support RTL and Table support direction prop #1471

feat: Table fixed column support RTL and fixed align bug in RTL #1471

---

content/input/select/index-en-US.md
content/input/select/index.md
packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/index.tsx

Select onSearch 提供第二个入参，用于区分 onSearch 触发类型
can be use like this:
```
<Select
onSearch={(v, e) => {
console.log(e.nativeEvent)
}}
filter 
multiple 
style={{ width: 300 }}
>
<Select.Option value="semi-0">Semi-0</Select.Option>
<Select.Option value="semi-1">Semi-1</Select.Option>
<Select.Option value="semi-2">Semi-2</Select.Option>
<Select.Option value="semi-3">Semi-3</Select.Option>
<Select.Option value="semi-4">Semi-4</Select.Option>
</Select>
```
沿着 notifySearch 开始加入参，往上的调用链路
- A) 回车、esc、tab、shift tab
-> close -> clearInput
-> notifySearch
- B) 多选 
-> clearInput
-> notifySearch
- C) clear 图标  click
-> clearInput
-> notifySearch
- D)  Input 的 onChange
-> notifySearch
🇨🇳 …

fix: select onSearch add event param to detech operation origin

---

cypress/integration/table.spec.js
packages/semi-foundation/table/foundation.ts
packages/semi-ui/table/ColumnSelection.tsx
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/Demos/rowSelection.jsx
packages/semi-ui/table/_story/table.stories.jsx

Fixes #325
问题原因：翻页后 disabledRowKeysSet 是翻页后的数据，由于第二页没有禁用的行，导致已选行与所有行对比时认为有一行未选择，不是全选。
解决问题的方式：缓存所有禁用的行，在 dataSource、columns（里面可能有筛选受控）、rowSelection（里面可能有） 变化后更新它的值
🇨🇳 Chinese
- Fix: 修复 Table 全选后翻页表头选择框状态错误问题 #325
---
🇺🇸 English
- Fix: Fix the wrong state of the selection box in the header of the second page after selecting all the Table #325

fix: Table rowSelection header checkbox status bug #325

---

packages/semi-foundation/carousel/foundation.ts
packages/semi-ui/carousel/_story/carousel.stories.jsx
packages/semi-ui/carousel/index.tsx

Fixes #1482 
🇨🇳 Chinese
- Fix: 修复 Carousel props.children 更新后组件未重新更新问题
- Fix: 修复 Carousel ref method play 与 autoPlay.hoverToPause 的mouseEnter事件冲突，未拥有最高优先级问题
---
🇺🇸 English
- Fix: fix the problem that the component is not re-updated after Carousel props.children is updated
- Fix: fix the conflict between the Carousel ref method play and the mouseEnter event of autoPlay.hoverToPause, which does not have the highest priority

fix: props children update carousel did no rerender and ref.play should have the highest priority

---

package.json
packages/semi-webpack/src/semi-webpack-plugin.ts
yarn.lock

There is no need to pass NormalModule constructor thought `options.webpackContext` manually. The plugin can get it from compiler instance. 
Feat: try to get NormalModule from compiler instance

feat: get NormalModule from compiler instance

---

packages/semi-foundation/autoComplete/autoComplete.scss
packages/semi-foundation/spin/spin.scss
packages/semi-foundation/tree/tree.scss
packages/semi-foundation/upload/upload.scss

Fixes #1507 
div 包裹着 svg， svg 的 display 属性虽然为 inline，但是却具有 inline-block 的特性，导致 .semi-spin-wrapper 层级 div 高度比内容高。通过 vertical-align 将对齐方式从 baseline 改为 top 解决问题
回归用到<Spin / >的其他组件，主要可以分为三类，一类是修改前后没有影响的，一类是修改后纠正了原来不符合预期位置偏移的，还有一类是修改后没有解决问题，甚至还让表现变得更加离谱的。
- 无影响
- Switch 
- Cascader(之前通过给外层div加line-height 0 的方案修过 [PR #1244](https://github.com/DouyinFE/semi-design/pull/1244))
- 纠正后符合预期
- Transfer
- Image
- List
- Table
- Select
- 未解决问题，甚至表现地更加糟糕
- [AutoComplete](https://bytedance.feishu.cn/docx/UpP8dVotkoqkcExX2IVcxxCLnOg#FwMUdM0QEoYUEQx2joJchYI9nlc)（参考 Select 改法已修正）
- Upload（参考 Cascaader 改法已修正）
- Tree （参考 Cascaader 改法已修正）
详细修改说明参考飞书文档 [Spin …

fix: add vertical-align top to fix wrong height

---

packages/semi-ui/tabs/TabPane.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: tabpane use classnames

---

cypress/integration/popconfirm.spec.js
packages/semi-foundation/popconfirm/popconfirm.scss
packages/semi-foundation/popconfirm/rtl.scss
packages/semi-foundation/popconfirm/variables.scss
packages/semi-ui/popconfirm/index.tsx

Fixes #
🇨🇳 Chinese
- Style: 优化 Popconfirm 中的关闭按钮的css 布局
---
🇺🇸 English
- Style: Optimize the css layout of the close button in Popconfirm
原来的 close button css 设置较为复杂，同时 C2D 中转出来的结果不太符合预期， 该 PR 为优化布局，同时能实现更好的 C2D 效果

style: [Popconfirm] style optimize for close button in Popconfirm

---

packages/semi-foundation/typography/typography.scss

根据设计师要求，将 Typography 中的 copy/copied icon 垂直对齐方式从 text-bottom 改为 middle（行内居中对齐）
🇨🇳 Chinese
- Fix: 将 Typography 中的 copy/copied icon 垂直对齐方式从 text-bottom 改为 middle
---
🇺🇸 English
- Fix: change the vertical-align of copy/copied icon in Typography from text-bottom to middle

style: change typography copy icon from vertical-align text-bottom to middle

---

cypress/integration/datePicker.spec.js
packages/semi-foundation/datePicker/foundation.ts
packages/semi-ui/datePicker/__test__/datePicker.test.js
packages/semi-ui/datePicker/_story/v2/dynamicDisabledDate.tsx
packages/semi-ui/datePicker/_story/v2/index.js

1x patch 版本 fix 过此问题
Fixes #777
🇨🇳 Chinese
- Fix: 修复 DatePicker disabledDate 回调中的 rangeStart 和 rangeEnd 使用缓存值问题 #777
---
🇺🇸 English
- Fix: Fixed the problem that rangeStart and rangeEnd in DatePicker disabledDate callback use cached values #777

fix: fixed disabledDate rangeStart and rangeEnd cached bug #777

---

packages/semi-foundation/sideSheet/sideSheet.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 Sidesheet 在 mask=false 时，mask 背景内容无法点击的问题，影响范围 2.32.0-beta.0 ~ 2.33.0-beta.0
---
🇺🇸 English
- Fix: Fix the problem that the background content of the mask cannot be clicked when the Sidesheet is set to mask=false, the impact range is 2.32.0-beta.0 ~ 2.33.0-beta.0

fix: fix sidesheet mask=false mask width not correct

---

packages/semi-ui/button/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Button 使用 ComponentPropsWithRef 获取不到Props 类型的问题
---
🇺🇸 English
- Fix: Fix the problem that Button cannot get the Props type using ComponentPropsWithRef

fix: fix ComponentPropsWithRef type function failed with Button

---

cypress/integration/typography.spec.js
packages/semi-foundation/typography/typography.scss
packages/semi-ui/breadcrumb/item.tsx
packages/semi-ui/typography/_story/typography.stories.jsx
packages/semi-ui/typography/base.tsx
packages/semi-ui/typography/util.tsx

bug的可复现链接（chrome打开，firefox因为有时不溢出时，scrollHeight > offsetHeight，bug可能不会复现）https://codesandbox.io/s/semi-design-simple-story-forked-5tdpeo?file=/src/App.jsx
Fixes 
1. 有省略的文本，resize到省略消失，再resize回原来的尺寸，没有省略状态
2. 可展开的文本，在折叠状态下，resize到展开消失，再resize回原来的尺寸，变成了展开状态
3. js计算溢出时，由于把展开按钮的宽度也计算在内（实际展开按钮不一定展示），会导致展开前后的行数其实是一样的（即没有溢出的情况下展示了展开按钮）
解决方法
1. cssEllipsis时，resize后通过scollHeight和clientHeight判断是否溢出不准确，因为css加省略的样式仅在isOverflow时生效，而在resize后溢出指定行数的情况下，isOverflow是false，css省略的样式没有生效
2. 因为在getEllipsisState时，若js计算的值和chidren不同，则会将expanded置为true（即使用户没有点击展开按钮）。这还引入了其他比较脏的逻辑，如first相关的逻辑
3. 在最开始js计算溢出时，先不计算展开的按钮，而是先计算一定会包含在最终内容的节点。当判断到文本会溢出的时候，再将展开按钮参与计算。
🇨🇳 Chinese
- Fix: Typography …

fix: typography multiple issues

---

packages/semi-ui/_utils/index.tsx
packages/semi-ui/tooltip/_story/tooltip.stories.jsx
packages/semi-ui/tooltip/index.tsx

Fixes #1557
semi 弹层类组件都依赖于 Tooltip，trigger 为 hover 的弹层类组件在**弹层上**会有 onFocus 打开面板 和 onBlur 关闭面板 的事件。
在 **2.29.0** 版本中，点击 PopConfirm 内部任意处都会导致面板关闭。响应路径如下
1. 点击 button，打开 PopConfirm 面板，Dropdown 弹层触发 onFocus。
2. 点击 PopConfirm 面板，button 失焦，Dropdown 弹层触发 onBlur，Dropdown 弹层关闭。
此时应给 Dropdown 设置 disabledFocusListener，屏蔽弹层 onFocus 和 onBlur 事件即可。
在 **2.30.0 - 2.33.0** 版本中，增加了 Popconfirm 的 A11y 支持，给 Tooltip portal 内层 div 增加了 tabindex=-1 设置，此时内层 
div 可以响应聚焦事件。因为未对弹层内 onFocus 和 onBlur 事件进行拦截，所以响应路径如下
1. 点击 button，打开 PopConfirm 面板，Dropdown 弹层触发 onFocus。
2. 点击 PopConfirm 面板，button 失焦，Dropdown 弹层触发 onBlur。同时内层 div 响应聚焦事件，冒泡到 Dropdown，Dropdown 弹层触发 onFocus。所以此时 Dropdown 不设置 …

fix: add stopPropagation to focus and blur event in tooltip portal

---

packages/semi-foundation/radio/radio.scss

- RadioGroup 为 inline-flex 布局
- 方案A：inline-flex 改 flex
- 方案B：vertical-align 设为 bottom或top，非baseline 值
选择方案B，维持RadioGroup的 inline 属性。修改前后 height 均为20px。选择 bottom而非top，因为radio目前已有类似属性设置，在Parent Group级别维持一致 (且top、bottom实测表现一致)
🇨🇳 Chinese
- Fix: 修复 RadioGroup 父级容器高度会跟随 RadioGroup 选项不同而变化的问题 #1573 
---
🇺🇸 English
- Fix: Fix the problem that the height of the RadioGroup parent container will change with the RadioGroup option #1573

fix: radioGroup add vertical-align, close #1573

---

packages/semi-foundation/utils/date-fns-extra.ts
packages/semi-ui/datePicker/_story/v2/FeatEtcGMT.tsx
packages/semi-ui/datePicker/_story/v2/index.js

Fixes #1585
Etc/GMT 在做时区转换时，不考虑夏令时，使用它会比具体某个地区的时区好，因为某个地区的时区可能随着时间变化而调整是否应用夏令时。（例如 +2 时区，埃及/开罗，在2023.4.28，时隔七年后又重新决定启用夏令时）
🇨🇳 Chinese
- Fix: 修复 DatePicker timeZone 为整数值时的判断逻辑，使用 IANA Etc/GMT 替换 IANA 地区标识 #1585
---
🇺🇸 English
- Fix: Fix the judgment logic when DatePicker timeZone is an integer value, and replace the IANA region identifier with IANA Etc/GMT #1585

fix: fixed DatePicker timeZone map logic and use Etc/GMT* id #1585

---

packages/semi-foundation/input/input.scss
packages/semi-ui/input/_story/input.stories.jsx

🇨🇳 Chinese
- Fix: 修复 Input type=search 且 showClear 为true时，原生清除按钮与 Semi 清除按钮同时显示的问题
---
🇺🇸 English
- Fix: When Input type=search and showClear is true, the original clear button and the Semi clear button are displayed at the same time

Fix search input icon

---

packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.jsx

Fixes # 1584
🇨🇳 Chinese
- Fix: 修复 select 单选和 renderSelectedItem 情况下，defaultValue 为 null 时不显示 placeholder 问题
---
🇺🇸 English
- Fix: fix select is single select and renderSelectedItem, the placeholder is not displayed when the value is null

fix: select is single select and renderSelectedItem, the placeholder is not displayed when the value is null #1584

---

cypress/integration/tabs.spec.js
packages/semi-ui/overflowList/index.tsx
packages/semi-ui/tabs/_story/tabs.stories.jsx
yarn.lock

Fixes #1456  #1502
之前通过直接比较 items 更新前后的值，来解决 tabs 的 tabpanel 值改变后的 visibleState 问题。具体见 #1363 
点击 tab 跳转后会导致 items 的 active 值变化，造成不预期的 setState  visibleState，所以为了达到 fix #1363 的效果，仅比较 key 值即可。
Previously, the visibleState problem after the tabpanel value of tabs changed was solved by directly comparing the values before and after the items were updated. See #1363 for details
Clicking the tab to jump will cause the active value of items to change, resulting in unexpected setState visibleState, so in order to achieve the effect of fix #1363, only compare the key value.
🇨🇳 Chinese
- Fix: 修复 collapsible Tabs 切换 tab 后，Dropdown item 异常问题
---
🇺🇸 English
- Fix: fix the problem that …

fix: only compare key to determine whether to update the item #1456 #1502

---

packages/semi-foundation/timePicker/foundation.ts
packages/semi-ui/timePicker/_story/timepicker.stories.jsx

Fixes #1604
造成 bug 的主要原因是 date-fns-tz 1.3.7 ➡️ 1.3.8 的[变更](https://github.com/marnusw/date-fns-tz/commit/3bd32eef5dcdcbfd82709529ccc88ffa10fe50ff#diff-4c06f3ee39f66c80220e59b7d2c1f7d21d5406d5870dd737bd692538467deb69)。
该变更直接影响了 zonedTimeToUtc 函数 timezone 传 undefined 后的结果
before ：返回原时间
after：返回+8后的时间，相当于timezone 0
semi 侧主要影响的相关代码是 `refreshProps` 中的  `isValidTimeZone` 。
原来 this.isValidTimeZone(__prevTimeZone) 为 true，__prevTimeZone 为 undefined，zonedTimeToUtc 后仍为原时间，是我们想要的结果。
date-fns-tz 1.3.8后，zonedTimeToUtc 的结果为 + 8后的时间，是非预期的结果。
所以正确的修改策略应该是避免给 zonedTimeToUtc 的timezone传 undefined ，使其始终有合法的 timezone。
🇨🇳 Chinese
- Fix: 修复 TimePicker 在 date-fns-tz 版本 >= 1.3.8 时 timeZone 转换问题
--- …

fix: timepicker under timezone and controll get the wrong time after select in panel in 1.3.8 date-fns-tz

---

packages/semi-foundation/calendar/foundation.ts
packages/semi-ui/calendar/__test__/calendar.test.js

当mode=range时，semi用于计算rangeData的时候，会使用`range[0]`作为开始值；当range包含时间的时候，生成的rangeData如图：
但解析event时，semi默认会使用当日0时的日期作为key：
因此导致range模式且`range[0]`包含时间时，非全天日程会无法显示：
修复后，生成rangeData正常：
Fixes #
🇨🇳 Chinese
- Fix: 修复日历多日模式中，range包括时间时不显示非全天日程
---
🇺🇸 English
- Fix: in Calendar's range mode, the non-full-day events is not displayed when the `range` includes time

fix: calendar range mode

---

cypress/e2e/table.spec.js
packages/semi-foundation/table/foundation.ts
packages/semi-ui/table/_story/v2/FixOnChange/index.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes #1572
- before：onChange 通知时收集 columns 的 filters，根据 column.onFilter 是否存在为依据，往 filters 中添加当前列排序数据
- after：filteredValue 传了即可，适用于不传 onFilter 情况（例如服务端排序）
🇨🇳 Chinese
- Fix: 修复未传 onFilter 函数时 Table onChange 中 filters 为空问题 #1572
---
🇺🇸 English
- Fix: Fix the problem that the filters in Table onChange are empty when the onFilter function is not passed #1572

fix: Table onChange filters is empty when onFilter is not passing #1572

---

packages/semi-ui/image/image.tsx
packages/semi-ui/image/preview.tsx

…iew unmount phase
Fixes #1595 
🇨🇳 Chinese
- Fix:  将 ImagePreview 中的 IntersectionObserver 对象的声明放在 componentDidMount 而不是 constructor 中，防止 SSR 场景下出错 #1595 
---
🇺🇸 English
- Fix: Put the declaration of the IntersectionObserver object in ImagePreview in componentDidMount instead of constructor to prevent errors in SSR scenarios #1595 
IntersectionObserver 的对象放在 constructor 中，是为了让 ImagePreview 下的 children 的 Image 能够拿到该 observer，在 Image 的 componentDidMount/ componentDidUpdata 中 props的src 变化时候能够被 observer 观察到。
由于IntersectionObserver 是浏览器 API， 放在 constructor 中会导致 SSR 场景下报错， 因此修改到 ImagePreview 的 componentDidMount 中，同时将在 componentDidUpdate 中对 children 进行监视，如果children 发生修改修改，则重新监听 img …

fix: [Image] Put the declaration of the IntersectionObserver object in ImagePreview in componentdidMount to prevent errors in SSR scenarios

---

packages/semi-foundation/dropdown/foundation.ts
packages/semi-ui/dropdown/_story/dropdown.stories.jsx

Fixes #1606 
🇨🇳 Chinese
- Fix: 仅当 Dropdown panel 可见时，才触发上下箭头按下事件的 stopPropagation 和 preventDefault
---
🇺🇸 English
- Fix: the stopPropagation and preventDefault of the up and down arrow press events are triggered only when the Dropdown panel is visible

fix: only when dropdown panel visible trigger handlePrevent function

---

packages/semi-foundation/datePicker/datePicker.scss
packages/semi-foundation/datePicker/foundation.ts
packages/semi-foundation/datePicker/inputFoundation.ts
packages/semi-foundation/input/foundation.ts
packages/semi-ui/datePicker/_story/datePicker.stories.jsx
packages/semi-ui/datePicker/_story/v2/FeatInsetInputShowClear.tsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/dateInput.tsx
packages/semi-ui/datePicker/datePicker.tsx
packages/semi-ui/input/index.tsx

- Feat
内嵌输入框在 trigger 上增加 clear 按钮
- Fix
placeholder 多了字符，原因是 switch break 漏了（v2.32.0-beta.0 DatePicker 新增 type monthRange API 引入）
未 hover icon 时不应该是蓝色
🇨🇳 Chinese
- Feat：DatePicker 内嵌输入框在 trigger 上增加 clear 按钮  #1638
- Fix: 修复 DatePicker insetInput 内嵌输入框 placeholder 占位文本错误问题
- Fix: 修复 DatePicker 范围输入框 clear 按钮默认颜色不对问题
---
🇺🇸 English
- Feat: DatePicker insetInput input box supports clearing input box content through trigger #1638
- Fix: Fix DatePicker insetInput input box placeholder placeholder text error
- Fix：Fix DatePicker range input clear icon color bug

feat: DatePicker insetInput support clear icon #1638

---

packages/semi-ui/datePicker/datePicker.tsx
packages/semi-ui/datePicker/quickControl.tsx
packages/semi-ui/locale/_story/locale.stories.jsx
packages/semi-ui/locale/interface.ts
packages/semi-ui/locale/source/ar.ts
packages/semi-ui/locale/source/de.ts
packages/semi-ui/locale/source/en_GB.ts
packages/semi-ui/locale/source/en_US.ts
packages/semi-ui/locale/source/es.ts
packages/semi-ui/locale/source/fr.ts
packages/semi-ui/locale/source/id_ID.ts
packages/semi-ui/locale/source/it.ts
packages/semi-ui/locale/source/ja_JP.ts
packages/semi-ui/locale/source/ko_KR.ts
packages/semi-ui/locale/source/ms_MY.ts
packages/semi-ui/locale/source/nl_NL.ts
packages/semi-ui/locale/source/pl_PL.ts
packages/semi-ui/locale/source/pt_BR.ts
packages/semi-ui/locale/source/ro.ts
packages/semi-ui/locale/source/ru_RU.ts
packages/semi-ui/locale/source/sv_SE.ts
packages/semi-ui/locale/source/th_TH.ts
packages/semi-ui/locale/source/tr_TR.ts
packages/semi-ui/locale/source/vi_VN.ts
packages/semi-ui/locale/source/zh_CN.ts
packages/semi-ui/locale/source/zh_TW.ts

Fixes #
🇨🇳 Chinese
- Fix: DatePicker preset 面板标题支持 i18n 
---
🇺🇸 English
- Fix: DatePicker preset panel title supports i18n

fix: add presets i18n in DatePicker

---

content/input/upload/index.md
packages/semi-foundation/upload/foundation.ts

用户以类似的方式使用，借助 beforeUpload 对图片做裁剪
🇨🇳 Chinese
- Fix: 修复 Upload 在 beforeUpload中更新 fileInstance后，未更新缩略图渲染的问题
---
🇺🇸 English
- Fix: Fix the problem that the thumbnail rendering is not updated after Upload updates the fileInstance in beforeUpload

fix: refresh thumb pic when beforeUpload update fileInstance

---

packages/semi-ui/input/index.tsx
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx

Fixes preventScroll 未透传给 Input 问题，导致 Input autofocus 时 preventScroll 未生效
修改 Input 的 autoFocus 生效方式，从借助原生的 autofocus 到通过调用元素的 focus 方法实现，区别在于调用 focus 方法 preventScroll 设置可以生效，而前者 preventScroll 无法生效
🇨🇳 Chinese
- Fix: 修复 TreeSelect searchAutoFocus 的 preventScroll 未生效问题
- Fix: 修复 Input 在 autofocus 为 true 时 preventScroll 未生效问题
---
🇺🇸 English
- Fix: Fix the problem that preventScroll of TreeSelect searchAutoFocus does not take effect
- Fix: Fix the problem that preventScroll does not take effect when autofocus is true in Input

fix: TreeSelect searchAutoFocous preventScroll bug

---

packages/semi-ui/select/index.tsx
packages/semi-ui/select/option.tsx

Fixes #1678 
🇨🇳 Chinese
- Fix: 修复在 changeWithObject 时的 Select 中，treeData 中的 id 项无法出现的 onChange 回调的 value 值中问题
---
🇺🇸 English
- Fix: Fix the problem in the value value of the onChange callback that the id item in the treeData data cannot appear in the Select when changeWithObject

fix: Fix the problem that the id in the Option of Select is overwritten

---

packages/semi-foundation/tooltip/tooltip.scss

…lose #1680
🇨🇳 Chinese
- Fix: 修复 min-Width 属性大小写拼写错误导致的 warning，影响范围 (2.37.0-beta.0 - 2.38.0-beta.0) #1680
---
🇺🇸 English
- Fix: Fix the warning caused by the misspelling of the min-Width attribute, the scope of influence (2.37.0-beta.0 - 2.38.0-beta.0) #1680

fix: min-Width -> min-width, avoid compile warning of tooltip.scss

---

packages/semi-foundation/cascader/cascader.scss
packages/semi-foundation/cascader/variables.scss

修复 Cascader 禁用态 Tag 背景色与其他输入类组件不一致问题
🇨🇳 Chinese
- Fix: 修复 Cascader 禁用态 Tag 背景色与其他输入类组件不一致问题
---
🇺🇸 English
- Fix: fixed Cascader disabled tag bg color

fix: fixed Cascader disabled tag bg color

---

packages/semi-foundation/toast/toast.scss
packages/semi-foundation/toast/variables.scss

Fixes #
🇨🇳 Chinese
- design token: Toast padding token 拆分细化，$spacing-toast_content-paddingY 拆分为 $spacing-toast_content-paddingTop、$spacing-toast_content-paddingBottom，$spacing-toast_content-paddingX 拆分为 $spacing-toast_content-paddingLeft、$spacing-toast_content-paddingRight
---
🇺🇸 English
- design token: Toast padding token is split into 4. $spacing-toast_content-paddingY is split into $spacing-toast_content-paddingTop, $spacing-toast_content-paddingBottom, and $spacing-toast_content-paddingX is split into $spacing-toast_content-paddingLeft, $spacing-toast_content-paddingRight

refactor: split Toast padding token

---

packages/semi-foundation/anchor/foundation.ts

如果滚动 actions 存在多个，且第一个纵向不能滚动时，点击时没有反应问题。
我们应该找出来有纵向滚动的元素，忽略掉仅横向滚动元素
🇨🇳 Chinese
- Fix: 修复 Anchor 在部分场景下，点击无法跳转问题
---
🇺🇸 English
- Fix: Fix the problem that Anchor cannot jump when clicked in some scenarios

fix: fixed Anchor scroll bug

---

packages/semi-foundation/checkbox/checkbox.scss

Checkbox 图标与文本之间不能换行，不然会出现如下错误
🇨🇳 Chinese
- Fix: 移除 Checkbox 最外层侧 flex-wrap
---
🇺🇸 English
- Fix: Remove the flex-wrap on the outermost side of the Checkbox

fix: remove flex-wrap from Checkbox

---

packages/semi-foundation/form/foundation.ts

```
formApi.validate.then( (values) => {
})
```
入参中的 values 未做作用域隔离，用户若直接读取了 values，Field 对应的 DOM 若卸载了，这里的values的值也会被卸载。应该为一个不变的快照才对。
所以增加输出前的 deepClone环节
🇨🇳 Chinese
- Fix: 修复 Form validate.then() 中的 values 入参未做作用域隔离，会受到 Field DOM 挂载、卸载影响的问题
---
🇺🇸 English
- Fix: Fix the problem that the values input parameter in Form validate.then() is not scope isolated and will be affected by Field DOM mount and unmount

fix: form validate resolve value not satisfy scope isolation

---

packages/semi-foundation/form/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复导入类型ScrollIntoViewOptions首字母大小写。 引入时是首字母小写，但是有个地方用了大写，某些新版本的ts会报错
---
🇺🇸 English
- Fix: Fixed import type ScrollIntoViewOptions uppercase and lowercase. It is introduced with the first letter in lower case, but it is capitalized in one place, and some newer versions of ts will report an error

chore: [form] Fixed import type ScrollIntoViewOptions name

---

packages/semi-foundation/radio/radio.scss
packages/semi-foundation/radio/variables.scss

Radio addon 与 extra 的间距由 0 调整为 4px，与 Checkbox 保持一致。
🇨🇳 Chinese
- Style: Radio addon 与 extra 的间距由 0 调整为 4px，新增Token： $spacing-radio_content-rowGap 
---
🇺🇸 English
- Style: Adjust the spacing between Radio addon and extra from 0 to 4px，add design token：$spacing-radio_content-rowGap

feat: update Radio content row-gap from 0 to 4px

---

package.json
yarn.lock

Fixes #
🇨🇳 Chinese
- Chore: package.json中增加engines选项，避免新的contributor本地启动时环境不一致的问题
---
🇺🇸 English
- Chore: add engines option to package.json to pre-check the required node environment for new contributors
Thanks for the project first, when I download this project for the first time, I took a long time waiting of installing dependences but finally failed because of using node@14.x.x.
I think it is necessary to declare the basic node version requirement explicitly for pre-checking, so that new contributors will get more good experience to contribute.

chore: add engines declaration to package.json

---

packages/semi-foundation/button/button.scss

Fixes #1723 
🇨🇳 Chinese
- Style: 删除 Button 组件中的不必要的 margin
---
🇺🇸 English
- Fix: Remove unnecessary margin in button component
semi-button 类中的 margin 设置为 0， 没有产生任何实际效果，但是可能会影响用户的使用体验（#1723 ）。
删除影响面： 无。1. 没有以token的方式支持用户设置，因此删除无影响
2. chrome，safari，firfox浏览器下并没有设置margin 为非 0 值，不存在为覆盖默认 margin 情况

style: remove unnessary margin for Button

---

packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/FixedSticky/index.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes #1760 
表头是 fixed header 时，需要开启 fixed table-layout 以保证对齐。
🇨🇳 Chinese
- Fix: 修复 Table 表头与表体单元格在 sticky 开启时未对齐问题 #1760
---
🇺🇸 English
- Fix: fixed Table column not aligned when header is sticky #1760

fix: fixed Table column not aligned when header is sticky #1760

---

packages/semi-foundation/upload/fileCardFoundation.ts
packages/semi-foundation/upload/upload.scss
packages/semi-ui/upload/_story/upload.stories.jsx
packages/semi-ui/upload/fileCard.tsx

- 问题
Upload preivew 设为true时，默认会以 img 元素消费 url，如果用户文件类型不明确，且无法从 name 或 url 后缀判断时。若默认情况不做处理，预览 pdf文件时会显示 x。需要用户自行通过 previewFile  API 创建 img 元素并监听 onError 决定返回 reactNode 类型，较为繁琐。
- 处理方案
增加默认兜底逻辑，如果 img 加载 error，则自动切换成fallback 图标
🇨🇳 Chinese
- Fix: Upload preview 为true时，增加对其他类型文件的预览兜底，防止 pdf 等其他类型文件加载失败时显示 x 裂图
---
🇺🇸 English
- Fix: When Upload preview is true, add previews for other types of files to prevent pdf and other types of files from displaying x-cracked images when loading fails

Fix upload preview fallback

---

content/input/form/index-en-US.md
content/input/form/index.md
packages/semi-foundation/form/constants.ts
packages/semi-foundation/form/utils.ts
packages/semi-ui/form/_story/Validate/TriggerAndStopValidateWithError.jsx
packages/semi-ui/form/_story/form.stories.jsx
packages/semi-ui/form/baseForm.tsx
packages/semi-ui/form/hoc/withField.tsx
packages/semi-ui/form/interface.ts

🇨🇳 Chinese
- Feat: Form 增加 stopValidateWithError 、trigger API，允许统一配置所有 Field的 stopValidateWithError、trigger属性 #640 
---
🇺🇸 English
- Feat: Form add API: stopValidateWithError 、trigger，allow unified configuration of stopValidateWithError and trigger properties of all Fields #640

feat: form add stopValidateWithError, trigger, close #640

---

packages/semi-ui/tree/index.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 去掉 TreeSelect/Tree 的 getDerivedState 中对 TreeData 是否变化的多余比较
---
🇺🇸 English
- Fix: Remove the redundant comparison of whether TreeData has changed in getDerivedState of TreeSelect/Tree

fix: Remove repeated comparisons of the same variable

---

packages/semi-ui/select/index.tsx

Fixes #1560
🇨🇳 Chinese
- Fix:  issues #1560  
下拉框折叠更多数量显示错误的问题
修复原因：是因为需要正确的数量更新的那一次update，没有调用update，没有调用update的原因是因为if判断的问题
bug截图
---
🇺🇸 English
- Fix:  issues #1560  Wrong number of tags after selection under ellipsisTrigger
The drop-down box collapses with more numbers and displays the wrong problem
Reason for repair: The update was not called when the correct number of updates was needed. The reason why update was not called was because of the if judgment problem.
bug screenshot
---

fix: issues 1560 Wrong number of tags after selection under ellipsisTrigger

---

packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.jsx
packages/semi-ui/select/index.tsx
packages/semi-ui/select/utils.tsx

1. Select 使用 JSX 传入 Option时，Option的 key 未被收集，从而导致在 renderOption 列表时，总是走到兜底逻辑中去，在少数场景下，会导致react 抛出列表项 key 重复 的 warning
2. 仅影响 JSX 传入 option 写法，若使用 props.optionList 传入后选项无该问题
3. 需要区分 props.optionList 中带key，与  JSX 传入 option时带key两种情况。前者的key 在 onSelect、onChange回调入参里需要保留，后者不需要
🇨🇳 Chinese
- Fix: 修复 Select 使用 JSX 传入 Option时，Option传入的 key 未在渲染时生效的问题
---
🇺🇸 English
- Fix: Fix the problem that when Select uses JSX to pass in Option, the key passed in Option does not take effect during rendering.

fix: select option never use key in jsx declare usage

---

content/start/changelog/index-en-US.md
content/start/changelog/index.md
packages/semi-ui/pagination/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Pagination popoverZIndex 在 SizeChanger 上不生效的问题
---
🇺🇸 English
- Fix: Fixed the problem that Pagination popoverZIndex does not take effect on SizeChanger

fix: pagination popoverZIndex don't take effect on sizeChanger

---

cypress/e2e/datePicker.spec.js
packages/semi-foundation/datePicker/inputFoundation.ts
packages/semi-ui/datePicker/_story/datePicker.stories.jsx
packages/semi-ui/datePicker/_story/v2/AutoSplitInput.jsx
packages/semi-ui/datePicker/_story/v2/index.js

see #1787
🇨🇳 Chinese
- Feat: DatePicker 内嵌输入类型，支持粘贴合法日期字符串到第一个输入框后自动拆分日期与时间并选择对应日期 #1787
---
🇺🇸 English
- Feat: The DatePicker `insetInput` type supports pasting a legal date string into the first input box and automatically splitting the date and time and selecting the corresponding date #1787

feat: DatePicker support split first inset input 

---

packages/semi-ui/dropdown/dropdownItem.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Dropdown Item 右键和中键也会触发 onClick 的问题
---
🇺🇸 English
- Fix: Fix the problem that the right and middle click of Dropdown Item will also trigger onClick

fix: fix right click trigger the onClick func

---

cypress/e2e/table.spec.js
packages/semi-foundation/table/table.scss
packages/semi-ui/table/HeadTable.tsx
packages/semi-ui/table/__test__/table.test.js
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/ShowHeader/index.tsx
packages/semi-ui/table/_story/v2/index.js

Fixes virtualized Table showHeader bug #726
🇨🇳 Chinese
- Fix: 修复虚拟化表格 showHeader 为 false 时表格体渲染空问题 #726
---
🇺🇸 English
- Fix: fixed virtualized Table showHeader bug #726

fix: fixed virtualized Table showHeader bug #726

---

cypress/e2e/select.spec.js
packages/semi-ui/select/_story/select.stories.jsx
packages/semi-ui/select/utils.tsx

- 由于 v2.46.0 为了修复 https://github.com/DouyinFE/semi-design/pull/1889 在 Select 父级收集 子级Option的处理过程中，增加了 key的赋值逻辑
在 Group 场景下，如果option未声明key，按照当前逻辑，最终key如下
```
.group1
.1
.2
.group2
.1
.2
```
存在重合的 key，所以导致筛选后列表显示出错
🇨🇳 Chinese
- Fix: 修复 Select Group 分组场景使用 Option，未显式声明 key属性时，filter 后列表筛选错误的问题，影响范围 (v2.46.0-v2.47.0)
---
🇺🇸 English
- Fix: Fixed the problem of incorrect list filtering after filter when Option is used in Select Group grouping scenario and the key attribute is not explicitly declared. The scope of impact is (v2.46.0-v2.47.0)

fix: select group option without key, filter error after v2.46

---

content/show/sidesheet/index-en-US.md
content/show/sidesheet/index.md
packages/semi-foundation/sideSheet/sideSheetFoundation.ts
packages/semi-ui/sideSheet/SideSheetContent.tsx
packages/semi-ui/sideSheet/__test__/sideSheet.test.js

相关issue：https://github.com/DouyinFE/semi-design/issues/1948
SideSheet组件支持自定义closeIcon
🇨🇳 Chinese
- Feat: SideSheet 组件支持自定义 closeIcon
---
🇺🇸 English
- Feature: SideSheet component supports custom closeIcon

feat: sidesheet support for customized closeIcon

---

cypress/e2e/typography.spec.js
packages/semi-ui/typography/_story/typography.stories.jsx
packages/semi-ui/typography/util.tsx

在JS截断rows=1时，对于溢出但没有换行的文本，无法使用高度>=2行高度来判断是否溢出，应判断宽度是否溢出。
此前的fix是判断是否有white-space: nowrap来判断是否没有换行，但默认的换行策略对于一些文本也不会换行。
复现链接：https://codesandbox.io/s/semi-design-simple-story-forked-gmwst7?file=/src/App.jsx
🇨🇳 Chinese
- Fix: 修复typography JS截断对于不换行文本的计算错误
---
🇺🇸 English
- Fix: fix typography JS truncate cannot work with text doesn't wrap

fix: (Typography)JS truncate cannot work with text doesn't wrap

---

content/show/calendar/index-en-US.md
content/show/calendar/index.md
packages/semi-ui/calendar/_story/calendar.stories.jsx
packages/semi-ui/calendar/dayCalendar.tsx
packages/semi-ui/calendar/dayCol.tsx
packages/semi-ui/calendar/index.tsx
packages/semi-ui/calendar/interface.ts
packages/semi-ui/calendar/rangeCalendar.tsx
packages/semi-ui/calendar/weekCalendar.tsx

support #702 
🇨🇳 Chinese
- Feat: Calendar 新增 minEventHeight api 以支持在日、多日以及周视图下，当 event start 和 end 非常接近时，event dom 结构存在且有最小高度
---
🇺🇸 English
- Feat: Calendar adds minEventHeight API to support that in day, multi-day and week views, when event start and end are very close, the event dom structure exists and has a minimum height.

feat: add minEventHeight api to support min height in day level event render

---

packages/semi-foundation/slider/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 Slider 把手上的tooltip 在拖动时偶尔闪烁的问题
---
🇺🇸 English
- Fix: Fixed the issue where the tooltip on the Slider handle occasionally flickers when dragging

fix: fix slider tooltip blink when drag out of handle

---

cypress/e2e/select.spec.js
packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.jsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 select 单选选择选项后，点击外部不触发 onblur 事件问题
---
🇺🇸 English
- Fix: fixed the problem that after selecting a radio option, clicking outside does not trigger the onblur event

fix: fixed the problem that after selecting a radio option, clicking outside does not trigger the onblur event

---

content/show/table/index-en-US.md
content/show/table/index.md
packages/semi-foundation/table/table.scss
packages/semi-ui/table/ColumnSorter.tsx
packages/semi-ui/table/Table.tsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/SortIcon/index.tsx
packages/semi-ui/table/_story/v2/index.js
packages/semi-ui/table/interface.ts
yarn.lock

feat: Table column support sortIcon
decsription：返回一个 react ndoe 而不是 up icon 和 down icon 的原因，默认的 icon 整体实现和一般 icon 不同，up 和 down 实际上是重叠的。如果自定义返回两个 icon，大概率不会是这样的样式。因此采用返回一个 react node 控制 sort icon，包含升序和降序，icon 的高亮行为通过 props.sortOrder 参数控制。
使用示例： https://codesandbox.io/p/sandbox/table-sorticon-zvpn2n
🇨🇳 Chinese
- Feat: Table 列支持自定义排序 icon
---
🇺🇸 English
- Feat: Table column support sortIcon

feat: Table column support sortIcon

---

cypress/e2e/select.spec.js
packages/semi-foundation/select/foundation.ts
packages/semi-ui/select/_story/select.stories.jsx

Fixes #1992 
[PR #1977](https://github.com/DouyinFE/semi-design/pull/1977) 的修改会导致 issue #1992 的问题。复盘后总结认为 [PR #1977](https://github.com/DouyinFE/semi-design/pull/1977)  的修改不合理。
所以本 PR 主要做两件事情：
1. 放弃 [PR #1977](https://github.com/DouyinFE/semi-design/pull/1977)  的修改
2. 通过另一种方式解决 [PR #1977](https://github.com/DouyinFE/semi-design/pull/1977) 想要解决的问题（单选选择后点击外部区域不触发 onBlur 事件）
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix: the new version of pr #1977

---

packages/semi-foundation/image/previewInnerFoundation.ts
packages/semi-ui/image/interface.tsx
packages/semi-ui/image/previewInner.tsx

Fixes #
原来的代码中在 mask 的回调中有判断当前点击位置的是否为 icon /footer 部分，如果是，则不关闭预览。对于关闭按钮，点击边缘部分（即 section 中不属于 icon 的部分），则 关闭按钮和 mask 中的回调都会被触发，从而导致 onVisible 调用两次
🇨🇳 Chinese
- Fix: 修复 ImagePreview 组件在预览时点击关闭按钮边缘时触发 onClose/onPreview 两次问题
---
🇺🇸 English
- Fix: Fixed the problem of triggering onClose/onPreview twice when clicking the edge of the close button in the preview state in the ImagePreview component

fix: fix onclose/onPreivew call twice when click the edge of closeIcon

---

cypress/e2e/textarea.spec.js
packages/semi-foundation/input/textareaFoundation.ts
packages/semi-ui/input/_story/input.stories.jsx
packages/semi-ui/input/textarea.tsx

Fixes #2026
变更逻辑：resize 行为由监听 window resize 修改为 textarea resize
🇨🇳 Chinese
- Fix: 修复 TextArea autosize 未监听文本域宽度变化 #2026
---
🇺🇸 English
- Fix: fixed TextArea autoSize is not work when textarea resize #2026

fix: fixed TextArea autoSize is not work when textarea resize #2026

---

packages/semi-ui/select/option.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Select 的 renderOptionItem 入参中没有 Option 的 className 的问题
---
🇺🇸 English
- Fix: Fix the problem that there is no className of Option in the renderOptionItem input parameter of Select

fix: add className in select renderOptionItem

---

packages/semi-foundation/select/select.scss
packages/semi-foundation/select/variables.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 Select 部分 border width token 不正确的问题
---
🇺🇸 English
- Fix: Fix the issue of incorrect border width token in Select part

fix: fix select border token

---

.vscode/launch.json

As title, remove cn comment at launch.json and fix runtimeArgs field.
On my windows machine, old version config makes some error:
- Couldn't find nodejs path: 
- run `bin/jest` with nodejs emit err: 
- Couldn't find tests with path: `${workspaceRoot}/packages/xx`
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

chore: cleanup vscode launch.json

---

cypress/e2e/timePicker.spec.js
packages/semi-foundation/timePicker/foundation.ts
packages/semi-ui/timePicker/_story/timepicker.stories.jsx

Fixes #2082 
判断 hours 是否合法时，需要用当前 Timepicker 下 timezone 时区的选择值去判断。
如当前选择 7:14， 比较 hour 的值也应该为 7 。
🇨🇳 Chinese
- Fix: 修复 Timepicker 中同时使用 timeZone 和 disabledHours 时显示值不符合预期问题
---
🇺🇸 English
- Fix: the problem that when using timeZone and disabledHours at the same time in Timepicker, the displayed value does not meet the expectations

fix: when using timeZone and disabledHours at the same time in timepicker display value does not meet expectations

---

content/show/collapsible/index-en-US.md
content/show/collapsible/index.md
packages/semi-ui/collapsible/__test__/collapsible.test.js
packages/semi-ui/collapsible/_story/collapsible.stories.jsx
packages/semi-ui/collapsible/index.tsx

Feat #2100 
🇨🇳 Chinese
- Feat: Collapsible 组件新增 lazyRender 属性
---
🇺🇸 English
- Feat: add lazyRender prop for Collapsible

feat: add lazyRender prop for Collapsible

---

content/feedback/toast/index-en-US.md
content/feedback/toast/index.md
packages/semi-foundation/toast/toastFoundation.ts
packages/semi-ui/toast/__test__/toast-command-call.test.js
packages/semi-ui/toast/index.tsx

相关issue：https://github.com/DouyinFE/semi-design/issues/2099
Toast 组件支持 theme 全局配置
🇨🇳 Chinese
- Feat: Toast 组件支持 theme 全局配置
---
🇺🇸 English
- Feature: Toast component supports theme global configuration

feat: toast component add theme config

---

cypress/e2e/navigation.spec.js
package.json
packages/semi-foundation/navigation/foundation.ts
packages/semi-ui/navigation/_story/FixedSelectedKeys/index.tsx
packages/semi-ui/navigation/_story/navigation.stories.jsx
packages/semi-ui/navigation/index.tsx
yarn.lock

Fixes #
错误原因：setState 合并导致第一次 setState 失效
原来第二个 setState 是为了解决 selectedKeys 变化后，自动加上父级 selectedKeys 问题，但是在受控场景这个方式不对
修改为：更新为 updateSelectedKeys 时自动加上父级的 key
🇨🇳 Chinese
- Fix: 修复 Navigation 组件在 react 17 下 selectedKeys 未生效问题
- Fix: 修复 Navigation 组件 openKeys 在 selectedKeys 更新后未生效问题
---
🇺🇸 English
- Fix: fixed Navigation component selectedKeys bug in react 17
- Fix: fixed  Navigation component openKeys does not work after selectedKeys is updated

fix: fixed Nav selectedKeys bug in react 17

---

packages/semi-theme-default/scss/_palette.scss
packages/semi-theme-default/scss/animation.scss
packages/semi-theme-default/scss/global.scss

Fixes #2142 
🇨🇳 Chinese
- Style: 通过 :host, :host-context 伪类选择器将 css variable 注入 shadow dom，保障 shadow dom 下的 Semi 组件样式正确 #2142 
---
🇺🇸 English
- Fix: Inject the css variable into the shadow dom through the :host, :host-context pseudo-class selectors to ensure that the Semi component style under the shadow dom is correct. #2142

style: Add a selector for the theme’s basic css variables to adapt to shadow dom

---

packages/semi-foundation/cascader/foundation.ts
packages/semi-ui/cascader/index.tsx

Fixes #
用户反馈在单选时候，在同时更新 treeData，并将 value 给 undefined 的情况下，Cascader 显示还是有选中值。例子如下
```
const treeData1 = [
{
label: 'Node1',
value: '0-0',
children: [
{
label: 'Child Node1',
value: '0-0-1',
// disabled: true,
},
{
label: 'Child Node2',
value: '0-0-2',
},
],
},
{
label: 'Node2',
value: '0-1',
},
];
export const SingleValueTreeData = ()=> {
const [value, setValue] = useState(['0-0', '0-0-1']);
const [treeData, setTreeData] = useState(treeData1)
const onChange = useCallback((value) => {
console.log('onchange', value);
setValue(value);
}, []);
const onButtonClick = useCallback(() => {
setValue(undefined);
setTreeData([
{
label: 'Node1',
value: '0-0',
children: [
{
label: 'Child …
```

optimize code logic in Cascader

---

packages/semi-foundation/treeSelect/foundation.ts

Fixes #
内部业务方业务中，小屏模式下，搜索状态下，面板选项变化，弹出层未调整到合适位置。
分析代码，应该在搜索处理的逻辑中，增加位置调整逻辑
🇨🇳 Chinese
- Fix: 修复 TreeSelect 在搜索后选项变化，面板位置未自动调整问题
---
🇺🇸 English
- Fix: Fixed the problem that TreeSelect options changed after searching and the panel position was not automatically adjusted.

fix: TreeSelect adds position adjustment after search

---

packages/semi-foundation/upload/foundation.ts
packages/semi-ui/upload/_story/upload.stories.jsx

🇨🇳 Chinese
- Fix: 修复 Upload 将 addOnPasting 切换为 false 后，粘贴上传依然触发的问题
---
🇺🇸 English
- Fix: Fixed the problem that after Upload switches addOnPasting to false, paste upload is still triggered.

fix: upload addOnPasting switch to false should not trigger process

---

content/navigation/tabs/index.md
packages/semi-ui/tabs/TabPane.tsx
packages/semi-ui/tabs/index.tsx
packages/semi-ui/tabs/interface.ts

Tabs&TabPane允许通过className对内层div进行样式管理
🇨🇳 Chinese
- Feature: Tabs&TabPane允许通过className对内层div进行样式管理
---
https://github.com/DouyinFE/semi-design/issues/2152

feat: Tabs&TabPane增加 contentClassName

---

packages/semi-foundation/tooltip/foundation.ts
packages/semi-ui/tooltip/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Tooltip 在挂载时，如果 Cursor 已经在 trigger 的 dom 上，且 React 复用了 trigger dom 作为 tooltip 的 children，tooltip 不会展示的问题
---
🇺🇸 English
- Fix: Fix the problem that when the Tooltip is mounted, if the Cursor is already on the dom of the trigger, and React reuses the trigger dom as the children of the tooltip, the tooltip will not be displayed.

fix: fix tooltip not show when already hover on mount

---

packages/semi-foundation/banner/banner.scss

Fixes #
🇨🇳 Chinese
- Fix: 移除 Banner  .semi-banner-content 中无效的css规则
---
🇺🇸 English
- Fix: Remove banner dom : .semi-banner-content uselsss css rule

fix: update banner.scss, remove uselsss scss rules of align-items

---

packages/semi-foundation/table/rtl.scss
packages/semi-ui/table/_story/RTL/ColumnAlignWithSorter.tsx
packages/semi-ui/table/_story/RTL/index.jsx
packages/semi-ui/table/_story/table.stories.jsx
packages/semi-ui/table/_story/v2/columnAlignWithSorter.tsx

Fixes #2172，搭配 storybook 查看效果 http://localhost:6006/?path=/story/table--column-align-with-sorter
问题原因：带排序和筛选的区域，`justify-content` 需要根据 rtl 做调整
🇨🇳 Chinese
- Fix: 修复 Table 表头 text-align 在 RTL 模式下对齐不正确的问题 #2172
---
🇺🇸 English
- Fix: fixed Table header text-align bug in RTL mode #2172

fix: fixed Table text-align bug in RTL mode #2172

---

packages/semi-foundation/tagInput/tagInput.scss
packages/semi-foundation/tagInput/variables.scss
packages/semi-ui/tagInput/_story/tagInput.stories.jsx
packages/semi-ui/tagInput/index.tsx

其他组件如 input、select 等支持 insetLabel的组件，在 xx-inset-label 的 classname上均会带有 font-size的声明，不会受到 body fontsize继承的影响。而tagInput表现与其他组件不一致。需要对齐。
🇨🇳 Chinese
- Style: 修复 TagIput 在 Form 表单中使用 insetLabel时，样式与其他组件未对齐的问题
- Design Token：TagInput 增加 $color-tagInput_prefix-text-default、$spacing-tagInput_insetLabel-marginRight、$font-tagInput_insetLabel-fontWeight 三个 Token
---
🇺🇸 English
- Style: fixed TagInput insetLabel style not align with other component such as Input、Select
- Design Token：TagInput add Tokens：$color-tagInput_prefix-text-default、$spacing-tagInput_insetLabel-marginRight、$font-tagInput_insetLabel-fontWeight

style: fix tagInput insetLabel not align with other component

---

packages/semi-ui/input/_story/input.stories.jsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 ...
---
🇺🇸 English
- Fix: fix ...

fix input.stories.jsx autoFocus

---

packages/semi-theme-default/package.json

theme-default 并没有显式依赖 glob 和 path模块，不需要保留这个声明。
（在新项目中执行 yarn add @douyinfe/semi-ui时，会自动安装theme-default，会有以下提示）
🇨🇳 Chinese
- Chore: 移除@douyinfe/semi-theme-default  中不恰当的依赖声明
---
🇺🇸 English
- Chore: remove inappropriate dependency declarations in @douyinfe/semi-theme-default

chore: remove @douyinfe/semi-theme-default deps declare

---

content/input/autocomplete/index.md
packages/semi-foundation/form/interface.ts
packages/semi-foundation/tsconfig.json
packages/semi-icons/tsconfig.json
packages/semi-ui/form/_story/form.stories.tsx
packages/semi-ui/form/hooks/useFieldApi.tsx
packages/semi-ui/tsconfig.json

#1737
#2243
实现如下类型提示，setValue 入参若为嵌套路径，对合法性进行校验。对不合法的key进行错误提示
🇨🇳 Chinese
- Chore: Form组件，FormApi setValue 类型定义更新，优化嵌套路径的提示 #1737 
---
🇺🇸 English
- Chore: FormApi setValue update interface define, optimizing nested paths #1737

chore: setValue ts interface support recur path

---

packages/semi-foundation/toast/toast.scss

Fixes #
🇨🇳 Chinese
- Fix: 修复 Toast 在多条长度不同的 toast 弹出时，没有居中而是左对齐的问题
---
🇺🇸 English
- Fix: Fixed the issue where Toast is not centered but aligned to the left when multiple toasts with different lengths pop up.

fix: fix toast not center

---

packages/semi-ui/input/textarea.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 TextArea 的 onBlur/onFocus 类型定义错误
---
🇺🇸 English
- Fix: fix onBlur/onFocus type define error in TextArea

fix: fix onBlur/onFocus type define error in TextArea

---

packages/semi-foundation/tabs/tabs.scss
packages/semi-ui/tabs/TabBar.tsx

原来按钮和 tab 列表的间距是通过 div.semi-tabs-bar-arrow 上的 margin-left/right 来实现的，而在存在溢出元素时，div.semi-tabs-bar-arrow 显示，margin 出现，在没有溢出元素时，div.semi-tabs-bar-arrow 不显示，margin 也不会出现，最终导致 tab 列表的宽度发生变化，这也是导致 tab scrollIntoView 之后显示不完全的根本原因
https://github.com/DouyinFE/semi-design/blob/08c76a5b7baaf2e8af9a670b8af1bec9a7fc4871/packages/semi-ui/tabs/TabBar.tsx#L147-L155
https://github.com/DouyinFE/semi-design/blob/08c76a5b7baaf2e8af9a670b8af1bec9a7fc4871/packages/semi-ui/tabs/TabBar.tsx#L200-L207
/
🇨🇳 Chinese
- Fix: 修复 tab 在 scrollIntoView 后显示不完整的问题
---
🇺🇸 English
- Fix: Fixed the issue where the tab was not fully displayed when scrolled into view. …

fix(tabs): The tab was not fully displayed when scrollIntoView

---

packages/semi-foundation/spin/spin.scss

Fixes # 内部 oncall
反馈 table 的 loading icon 没有居中，排查发现是 Spin 组件的 svg 的 display 受到 tailwind 的默认设置有关系
svg 的默认 display 为 inline
tailwind 中默认设置的 svg display 为 block
🇨🇳 Chinese
- Style: 显式设置 Spin 下的 svg 的 display 属性为 inline，防止 tailwind 默认 svg 设置对 Spin 造成影响
---
🇺🇸 English
- Style: Explicitly set the display attribute of the svg under Spin to inline to prevent the tailwind default svg setting from affecting Spin.

style: Explicitly set the display of the svg in the spin to inline

---

packages/semi-foundation/input/input.scss

- 修复input组件在小尺寸状态下，文字没有很居中的问题，略微向下偏了一点点，改动涉及到input基础样式，看到大部分的衍生样式都把display设置成inline-flex，所以是否可以wrapper默认的display也设置成inline-flex？这样可以解决input没有在父容器居中给的问题
🇨🇳 Chinese
- Fix: 修复input在small size 状态下，文字略微向下偏移的问题
---
🇺🇸 English
- Fix: Fixed the problem that the text was slightly offset downwards when the input was in small size

fix: 修复小尺寸的input文字没有居中的问题

---

packages/semi-ui/autoComplete/index.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 AutoComplete 因为 autofocus 拼写导致的在开发环境下抛出 warning 的问题
---
🇺🇸 English
- Fix: fixed the issue where AutoComplete throws a warning in the development environment due to autofocus spelling errors

fix: change the innerProps from autofocus to autoFocus to avoid warning in the development env

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
content/navigation/tree/index-en-US.md
content/navigation/tree/index.md
packages/semi-foundation/tree/foundation.ts
packages/semi-foundation/tree/treeUtil.ts
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/tree/__test__/treeMultiple.test.js
packages/semi-ui/tree/_story/tree.stories.jsx
packages/semi-ui/tree/index.tsx
packages/semi-ui/tree/interface.ts
packages/semi-ui/treeSelect/__test__/treeMultiple.test.js
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx
yarn.lock

Fixes #
feature 在Tree组件中新增了 autoMerge 属性，用来在多选时，返回所有子节点时同时返回父节点
🇨🇳 Chinese
- Feat: Tree、TreeSelect 增加 autoMergeValue API
---
🇺🇸 English
- Feat: Tree、TreeSelect add autoMergeValue API

feat: 显示所有选中节点(包括父节点)

---

content/navigation/tabs/index-en-US.md
content/navigation/tabs/index.md
cypress/e2e/tabs.spec.js
packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tabs/_story/tabs.stories.jsx
packages/semi-ui/tabs/index.tsx
packages/semi-ui/tabs/interface.ts

support #2286
🇨🇳 Chinese
- Feat: Tabs 新增 api showRestInDropdown 用于控制可折叠 Tabs  Dropdown 面板的显隐
---
🇺🇸 English
- Feat: Tabs adds a new api showRestInDropdown to control the visibility of the foldable Tabs Dropdown panel

feat: support showRestInDropdown in tabs

---

packages/semi-foundation/table/constants.ts
packages/semi-foundation/table/utils.ts
packages/semi-ui/table/TableCell.tsx
packages/semi-ui/table/_story/virtualizedFixed/index.jsx

- Fixes https://github.com/DouyinFE/semi-design/issues/2267
因为虚拟化的使用的是 inline-flex，所以正常的align失效，在TableCell中添加了justifyContent属性。
🇨🇳 Chinese
- Fix: Table组件 virtualized后align失效的问题。
---
🇺🇸 English
- Fix: Table component virtualized align after failure problem

Fix(Table): Resolved alignment issues during virtualization (#2267)

---

cypress/e2e/cascader.spec.js
cypress/e2e/treeSelect.spec.js
packages/semi-foundation/cascader/constants.ts
packages/semi-foundation/cascader/foundation.ts
packages/semi-foundation/treeSelect/constants.ts
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/cascader/index.tsx
packages/semi-ui/treeSelect/index.tsx

Fixes # 内部需求。希望支持 esc 按键关闭 TreeSelect/Cascader 弹出层
🇨🇳 Chinese
- Feat: TreeSelect, Cascader 支持通过 esc 按键关闭弹出层
---
🇺🇸 English
- Feat: TreeSelect, Cascader supports closing the popup layer through the esc key

Feat/cascader, treeSelect support esc key to close panel

---

jest.config.js
package.json
test/__mocks__/devlop.js
test/__mocks__/mdx-3.0.1-cjs.js
test/__mocks__/remark-gfm-4.0.0-cjs.js
test/setup.js
yarn.lock

- [] Test Case
v2.62.0-beta.0后增加了 Lottie 、MarkdownRender 组件，他们的依赖
mdx-js、remakr-gfm只有 esm版本，无法直接被 jest消费
- mdx-js v3 、remark-gfm 无法简单地通过 jest.config.js 的  transformIgnorePatterns 参数指定走一遍  esm -> cjs 来解决（会遇到 devlop 这个包的问题，即使把它也指定上，也无法正确运行，同 https://stackoverflow.com/questions/77525472/how-to-test-mdx-js-mdx-with-jest-transformignorepatterns-not-working-on-devel
- 当前解决方案：直接把 mdx-js 、remark-gfm  build 一个 cjs 版本，通过 moduleNameMapper 映射
- lottie 在jest中运行报错是因为缺少 canvas mock
🇨🇳 Chinese
- Fix: 修复增加 MarkdownRender、Lottie 组件后，Jest 单测无法运行的问题
---
🇺🇸 English
- Fix: fix ...

Chore：fix jest error which cause by remark-gfm、mdx-js

---

packages/semi-foundation/table/table.scss
packages/semi-foundation/table/variables.scss

🇨🇳 Chinese
- Fix: 修复 Table 在 dataSource 为空时，存在非预期的 borderRadius 的问题
---
🇺🇸 English
- Fix: Fix Table has unexpected borderRadius when dataSource is empty

fix:  Style table radius

---

packages/semi-ui/modal/Modal.tsx
packages/semi-ui/modal/ModalContent.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Modal 在 getPopupContainer 中如果返回 document.body 异常的问题
---
🇺🇸 English
- Fix: Fixed the issue that Modal returns document.body exception in getPopupContainer

fix: fix modal popupContainer return body

---

cypress/e2e/image.spec.js
cypress/e2e/tooltip.spec.js
cypress/e2e/treeSelect.spec.js
packages/semi-foundation/treeSelect/foundation.ts
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx
yarn.lock

Fixes #
在 [2179](https://github.com/DouyinFE/semi-design/pull/2179/files) 中修复单选行为下展开异常问题时。增加了一个判断 inputValue 是否为空决定在弹出层关闭时是否需要调用 clearInput 的逻辑。预期是减少不必要的函数调用。
clearInput 中包含了重新计算面板需要显示的选项逻辑。
由于多选时候，在节点选中后，会做清除 inputValue 的操作，导致多选，可搜索，showFilteredOnly，以及 searchPosition 在trigger 中时，搜索状态下，选中节点后，再关闭弹出层，由于 inputValue 为空，导致 clearInput 未被调用。因此面板显示项目未重新计算。显示不符合预期。
修复操作：
- 删除通过 inputValue 是否存在决定是否调用 clearInput 的逻辑。
- 增加测试用例保证此情况下下组件表现稳定性
🇨🇳 Chinese
- Fix: 修复showFilteredOnly 并且搜索框在 trigger 中的 treeSelect 面板显示不正确问题
---
🇺🇸 English
- Fix: Fixed the problem of incorrect display of the treeSelect panel of showFilteredOnly, searchPosition in trigger

Fix/TreeSelect: showFilteredOnly, searchPosition in trigger, fix panel's options incorrectly display problem

---

packages/semi-ui/form/baseForm.tsx
packages/semi-ui/form/interface.ts

Fixes #
🇨🇳 Chinese
- Feat: Form 新增 stopProgation 可用于阻止嵌套Form场景下，submit 、reset事件同时在多级容器触发的问题 #2355 
---
🇺🇸 English
- Feat: Form adds stopProgation to prevent the issue of submit and reset events triggering in multiple levels of containers at the same time in nested Form scenarios #2355

feat: form support stopProgation for submit/reset event in nested usage

---

packages/semi-foundation/timePicker/utils/index.ts
packages/semi-ui/timePicker/_story/timepicker.stories.jsx

Fixes #2375
🇨🇳 Chinese
- Fix: 修复 TimePicker 在 onChangeWithDateFirst false 情况下为先选后一个时间导致 invalid time value 问题
---
🇺🇸 English
- Fix: fix the issue that when TimePicker selects a later time first, the invalid time value will be caused when onChangeWithDateFirst is false

fix: Fixed the issue that when TimePicker selects a later time first, the invalid time value will be caused when onChangeWithDateFirst is false

---

packages/semi-foundation/upload/foundation.ts
packages/semi-ui/upload/_story/upload.stories.jsx
packages/semi-ui/upload/index.tsx

🇨🇳 Chinese
- Fix: 修复 Upload 在组件卸载后，仍然可能因为上传异步请求触发 onChange、onError、onSuccess回调的问题 
---
🇺🇸 English
- Fix: Fixed the issue that onChange, onError, and onSuccess callbacks may still be triggered by asynchronous upload requests after the component is uninstalled

Fix upload callback after unmount

---

packages/semi-foundation/overflowList/foundation.ts
packages/semi-ui/overflowList/index.tsx
packages/semi-ui/tabs/_story/tabs.stories.jsx

Fixes #2415
出现 bug 的情况下，Overflowlist 拿到的 props.items 是[]，但是这个值没有被外部改动，而是在 getOverflowItem 时被内部改动了。通过 clonedeep props.items 避免该值被 Overflowlist 组件内部改动。
🇨🇳 Chinese
- Fix: 修复 Collapse Tabs 在快速点击左右箭头情况下造成的箭头禁用情况不正确问题
---
🇺🇸 English
- Fix: fixed the issue where the arrows in Collapse Tab are disabled incorrectly when clicking the left and right arrows quickly

fix: deepclone items when getOverflowItem to Prevent props.items from being changed internally due to rapid clicks

---

content/input/treeselect/index-en-US.md
content/input/treeselect/index.md
content/navigation/tree/index-en-US.md
content/navigation/tree/index.md
packages/semi-ui/tree/interface.ts
packages/semi-ui/tree/treeContext.tsx
packages/semi-ui/tree/treeNode.tsx

Fixes #
🇨🇳 Chinese
- Feat: Tree、TreeSelect 的 renderLabel API 增加 searchWord 参数，用于透出当前搜索框输入值
---
🇺🇸 English
- Fix: The renderLabel API of Tree and TreeSelect adds the searchWord parameter to reveal the current search box input value

feat: [Tree][TreeSelect] renderLabel add searchWord param

---

packages/semi-foundation/button/button.scss
packages/semi-foundation/button/iconButton.scss

Fixes #2402 
🇨🇳 Chinese
- Fix: 修复 Button 在 children 直接传入 icon 时，垂直方向不居中的问题 #2402 
---
🇺🇸 English
- Fix: Fixed the issue that Button is not vertically centered when icon is passed directly to children #2402

fix: fix button vertical align with icon

---

cypress/e2e/hotKeys.spec.js

Fixes #
🇨🇳 Chinese
- Fix: 修复快捷键更新后测试脚本未同步
---
🇺🇸 English
- Fix: sync for cypress test script of hotKeys

fix: sync for cypress test script of hotKeys

---

packages/semi-ui/cascader/_story/cascader.stories.jsx
packages/semi-ui/cascader/index.tsx
packages/semi-ui/select/index.tsx

Fixes #
修改后：依次为 Cascader，TreeSelect，Select
🇨🇳 Chinese
- Fix: 修复 Cascader 在有 suffix 并设置了 showClear 的情况下，清除图标位置和清除图标位置不同问题
- Style: 修改 Select 在设置 suffix 情况下，后缀和下拉图标的位置关系未与 TreeSelect/Cascader 保持一致问题（如有其他位置需求，可通过设置 flex 的 order 属性自行调整位置）
---
🇺🇸 English
- Fix: Fixed the problem that when Cascader has suffix and showClear is set, the position of the clear icon and the position of the clear icon are different.
- Style: Modify the problem that when suffix is ​​set in Select, the positional relationship between the suffix and the drop-down icon is not consistent with TreeSelect/Cascader. ((If you have other position requirements, you can adjust the position by setting the order …

fix: fix Selct, Cascader suffix icon style error

---

packages/semi-foundation/treeSelect/treeSelect.scss
packages/semi-ui/cascader/_story/cascader.stories.jsx
packages/semi-ui/cascader/item.tsx
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx
packages/semi-ui/treeSelect/index.tsx

Fixes #
**修改前，emptyContent 为 null 时，显示默认内容 **
**修改后，emptyContent 为 null 时，不展示选项内容 **
🇨🇳 Chinese
- Fix: 修改 Cascader, TreeSelect 当 emptyContent 为 null 的行为，同 Select 保持一致
---
🇺🇸 English
- Fix: Modify the behavior of Cascader, TreeSelect when emptyContent is null, consistent with Select

Fix/cascader, TreeSelect emptyContent is null

---

packages/semi-foundation/pincode/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 修复 PinCode 在非受控模式下，onChange 不触发的问题
---
🇺🇸 English
- Fix: Fixed the issue where onChange does not trigger in PinCode in uncontrolled mode

fix: pinCode onChange on no control mode

---

packages/semi-ui/typography/_story/typography.stories.jsx
packages/semi-ui/typography/base.tsx
packages/semi-ui/typography/util.tsx

…ribute is true
ellipsisContainer 无法准确获取宽度。原因是最终渲染形式为 `<strong><span /></strong>`，而实际计算基于 `<span></span>`。若 ellipsisContainer 能够主动传入 fontWeight 或者在计算时包裹一层 `<strong>` 标签，便可实现准确计算。此外，部分字体的 fontWeight 对宽度影响较为显著。
复现链接 [codesandbox](https://codesandbox.io/p/sandbox/semi-design-simple-story-forked-vstlmt)
🇨🇳 Chinese
- Fix: fix: Typography strong 属性为 true 时 suffix 位置计算不对
---
🇺🇸 English
- Fix: fix: Incorrect suffix position calculation when Typography strong attribute is true

fix: Incorrect suffix position calculation when Typography strong attribute is true

---

packages/semi-rspack/src/rule.ts

Fix: rspack plugin no effect on win32 platform, since win32 use \\ as system default sep.
Fixes #
🇨🇳 Chinese
- Fix: 修复 Rspack plugin 在 win32 平台不生效的问题
---
🇺🇸 English
- Fix: Fixed the issue that Rspack plugin does not work on win32 platform

Fix: rspack plugin no effect on win32 platform

---

cypress/e2e/datePicker.spec.js
packages/semi-foundation/datePicker/foundation.ts
packages/semi-ui/datePicker/_story/datePicker.stories.jsx
packages/semi-ui/datePicker/_story/v2/FixedControlledValue.jsx
packages/semi-ui/datePicker/_story/v2/index.js
packages/semi-ui/datePicker/datePicker.tsx

问题见 #2521
问题原因：受控时，获取 state.value 不正确
解决方式：使用 setTimeout 保证获取 state.value 是最新的
此问题由 #2388 引入
🇨🇳 Chinese
- Fix: 修复 DatePicker 在受控状态下选择后，第一次打开面板选中态未展示问题（影响 v2.64 ~ v2.67） #2521 
---
🇺🇸 English
- Fix: fixed selected value does not show when value is controlled （affects v2.64 ~ v2.67） #2521

fix: fixed selected value does not show when value is controlled #2521

---

packages/semi-foundation/cascader/cascader.scss
packages/semi-foundation/cascader/variables.scss

Fixes #
PR [2472](https://github.com/DouyinFE/semi-design/pull/2475) 对 icon 宽度做了修改，影响到了面板中的 icon 宽度。
修复方式：
新增加 token 用于表示面板中的 icon 的 token
修复前
修复后
🇨🇳 Chinese
- Fix: 修复 Cascader 面板 icon 宽度错误问题，影响版本2.67.0～2.67.1
- Style: 新增加 $width-cascader-option-icon 用于表示面板中的 icon 的宽度
---
🇺🇸 English
- Fix: Fixed the issue of incorrect width of Cascader panel icon, affecting versions 2.67.0～2.67.1
- Style: Newly added $width-cascader-option-icon is used to represent the width of the icon in the panel

fix: [Cascader] fix icon width error in option list pannel

---

packages/semi-foundation/chat/chat.scss

Fixes #
🇨🇳 Chinese
- Style: Chat 组件样式的 align-items 属性的 start/end 修改为 flex-start/flex-end
---
🇺🇸 English
- Style: The start/end of the align-items attribute of the Chat component style is modified to flex-start/flex-end

style: [chat] start/end to flex-start/flex-end for align-items

---

cypress/e2e/select.spec.js
packages/semi-foundation/select/foundation.ts
packages/semi-foundation/select/select.scss
packages/semi-ui/select/_story/select.stories.jsx

如下 Demo，点击选项然后点击 clearIcon后，state中的 showInput状态不正确，导致 placeholder 的 text 依然激活了 .semi-select-selection-text-inactive样式，opactiy为0.4，没有正确恢复到点击前的状态。
Ps：为了更明显观测到现象，这里覆盖了一下样式。
```
import React from 'react';
import { Select } from '@douyinfe/semi-ui';
() => {
const data = [
{
label: 'Asia',
children: [
{ value: 'a-1', label: 'China' },
{ value: 'a-2', label: 'Koera' },
]
},
{
label: 'Europe',
children: [
{ value: 'b-1', label: 'Germany' },
{ value: 'b-2', label: 'France' },
]
},
{
label: 'South America',
children: [
{ value: 'c-1', label: 'Peru' },
]
}
];
return (
<> 
<Select showClear placeholder="请选择" style={{ width: 180 }} filter>
{
data.map((group, index) => (
<Select.OptGroup …
```

Style - select placeholder inactive

---

packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
packages/semi-ui/datePicker/_story/datePicker.stories.jsx

Fixes #2567 
点击前时间： 2024-11 到 2025-01
点击右侧面板的 2024 后，理论上时间会变为 2023-11 到 2024-01，**此时命中了禁用区间所以无法跳转成功**。
修复逻辑如下 👇
如果进行某个年份选择，在 autoSelectMonth func 中，会对不符合要求的时间进行月份矫正，矫正到当前年月为非禁用态。
那么针对两个面板的时间可能出现以下 4 种状态 
1. 左 ✅，右 ✅。无需进行月份矫正。
2. 左 ✅，右 ❌。仅右侧进行月份矫正。
3. 左 ❌，右 ✅。仅右左侧进行月份矫正。
4. 左 ❌，右 ❌。两个时间均进行月份矫正。
矫正方式为 对齐当前面板矫正后（如需）的时间。
🇨🇳 Chinese
- Fix: 修复 MonthRange DatePicker 在存在 disabledDate 情况下点击非禁用年份不跳转问题
---
🇺🇸 English
- Fix: fix the issue that MonthRange DatePicker does not jump when clicking on a non-disabled year when there is a disabledDate

Fix：Datepicker disabledDate + monthRange does not behave as expected

---

cypress/e2e/datePicker.spec.js
packages/semi-foundation/datePicker/_utils/getYearAndMonth.ts
packages/semi-foundation/datePicker/_utils/index.ts
packages/semi-ui/datePicker/yearAndMonth.tsx

Fixes #
🇨🇳 Chinese
- Fix: 修复 Datepicker 类型为 monthRange 时，面板默认选中的年月无法选中跨年情况
---
🇺🇸 English
- Fix: Fixed the issue that when the Datepicker type is monthRange, the default selected year and month in the panel cannot be selected across the year

fix: Update the display logic of months in different years under type monthRange

---

packages/semi-foundation/tooltip/foundation.ts

Fixes #
🇨🇳 Chinese
- Fix: 对于非展示状态的 Tooltip，页面尺寸变化时不做位置计算
---
🇺🇸 English
- Fix: For invisible Tooltips, position calculation is not performed when resizing

fix: Remove resize event listening in non-display state of Tooltip

---

packages/semi-foundation/carousel/foundation.ts
packages/semi-ui/carousel/_story/carousel.stories.jsx
packages/semi-ui/carousel/index.tsx

Fixes #2633
之前的写法将 children 放在 state 中维护，仅在 key 值改变的时候更新 children，导致在 children 渲染 state （如 currentIndex 值）仅能得到一开始的初始值。
修复后 children 根据当前 props 生成，在 children 渲染 state 值能够正确更新。
🇨🇳 Chinese
- Fix: 修复 Carousel 在 children 中渲染 state 的值不更新问题
---
🇺🇸 English
- Fix: fix render state value in Carousel children always get the init one

fix: render state value in children render always get init one

---

packages/semi-ui/navigation/Item.tsx
packages/semi-ui/navigation/_story/navigation.stories.jsx

Fixes #2636 
修改前 Tooltip 包裹元素不是一个 valid children 命中 wrapSpan 逻辑，导致 disabled 项目并排展示，加一个 span 包裹保证元素为 valid children
🇨🇳 Chinese
- Fix: 修复竖向 Navigation 在收起状态下 disabled subNavItem 展示不符合预期问题
---
🇺🇸 English
- Fix: fixed the issue that the display of disabled subNavItem in vertical Navigation does not meet expectations when it is collapsed

fix: The display of disabled subNavItem in vertical Navigation is not as expected when it is collapsed

---

packages/semi-ui/jsonViewer/index.tsx

Fixes #
prevProps.options !== this.props.options 这一行通常会返回 true，除非 options 属性引用的是同一个对象
加上value更新时重新init。
之前写法，恰好当其他属性比如value属性改变是也会重新init。
🇨🇳 Chinese
- Fix:  修复JsonViewer 是否重新init的判断条件
---
🇺🇸 English
- Fix: Fix JsonViewer the judgment condition for whether to re-init.
- [] Changelog or no need

fix: [JsonViewer] Fix the judgment condition for whether to re-init.

---

packages/semi-json-viewer-core/src/view/edit/editWidget.ts

修复输入小写z无效的问题
🇨🇳 Chinese
- Fix: 修复JsonViewer输入小写z无效的问题
---
🇺🇸 English
- Fix: fixed the issue that the lowercase z input in JsonViewer is invalid

fix: resolve keyboard event handling logic issue

---

packages/semi-foundation/audioPlayer/foundation.ts
packages/semi-ui/audioPlayer/index.tsx

Compatible with other framework
🇨🇳 Chinese
- Fix: Compatible with other framework
---
🇺🇸 English
- Fix: 兼容其他框架，比如vue

fix: [AudioPlayer] Compatible with other framework

---

packages/semi-foundation/steps/bacisSteps.scss

Fixes #2688 
🇨🇳 Chinese
- Fix: 修复类型为 basic 的 Steps icon 和 title 未与 line 居中对齐问题 #2688 
---
🇺🇸 English
- Fix: fixed the issue that the Steps icon and title of type basic were not centered with the line #2688

fix: change Steps padding-bottom to margin bottom to make line center

---

content/input/upload/index-en-US.md
content/input/upload/index.md
packages/semi-ui/upload/_story/upload.stories.jsx
packages/semi-ui/upload/fileCard.tsx
packages/semi-ui/upload/index.tsx
packages/semi-ui/upload/interface.ts

Feat #2713
🇨🇳 Chinese
- Feat: 在图片墙场景下添加 renderPicClose 用于自定义关闭图标
---
🇺🇸 English
- Feat: add renderPicClose to custom close icon under listType picture

feat: add renderPicClose suppport in upload

---

packages/semi-foundation/cascader/cascader.scss
packages/semi-foundation/cascader/variables.scss
packages/semi-foundation/select/select.scss
packages/semi-foundation/select/variables.scss
packages/semi-foundation/treeSelect/treeSelect.scss
packages/semi-foundation/treeSelect/variables.scss
packages/semi-ui/cascader/_story/cascader.stories.jsx
packages/semi-ui/select/_story/select.stories.jsx
packages/semi-ui/treeSelect/_story/treeSelect.stories.jsx

Fixes #2721 
对 Select/Cascader/TreeSelect 新增加用于控制控制前后缀颜色的 token，并根据将 font-size 和 font-weight 的设置和 insetLabal的设置保持统一
🇨🇳 Chinese
- Style: Select 新增 $color-select_prefix_suffix_text-default， Cascader 新增 $color-cascader_prefix_suffix_text-default， TreeSelect 新增 $color-treeSelect_prefix_text-default 用于控制控制前后缀颜色。另外，将前后缀的 font-size 和 font-weight 的设置和 insetLabal的设置保持统一（**注意：修改前后样式有变化**）
#2721 
---
🇺🇸 English
- Style: Select adds $color-select_prefix_suffix_text-default, Cascader adds $color-cascader_prefix_suffix_text-default, and TreeSelect adds $color-treeSelect_prefix_text-default to control the prefix and suffix colors. In addition, keep the font-size and font-weight settings of …

fix: add prefix/suffix color token in Select/Cascader/TreeSelect

---

packages/semi-ui/scrollList/scrollItem.tsx

Fixes #2722
🇨🇳 Chinese
- Fix: 修复 Chrome v133 版本无障碍 Bug 导致的点击 DatePicker 月份选择器后 Chrome 崩溃问题
---
🇺🇸 English
- Fix: Fixed the Chrome v133 accessibility bug that caused Chrome to crash after clicking the DatePicker month selector

fix(datepicker): fixed chrome crashed bug by scrollList aria prop #2722

---

packages/semi-foundation/timePicker/ComboxFoundation.ts

Fixes #2726 
🇨🇳 Chinese
- Fix: 修复 TimePicker 在不填默认值的情况下，不同时区用户打开模版选中的默认值不同问题
---
🇺🇸 English
- Fix: fix when TimePicker does not fill in the default value, users in different time zones open the template and select different default values

fix: modify createDateDefault to a time zone-independent function in TimePicker

---

packages/semi-ui/form/_story/form.stories.tsx
packages/semi-ui/form/interface.ts

🇨🇳 Chinese
- Fix: 修复 Form validateFields 类型定义不支持 promise 的问题
---
🇺🇸 English
- Fix: Fixed the problem that the type definition of Form validateFields does not support return promise.

fix: type define miss promise of formProps.validateFields

---

cypress/e2e/tabs.spec.js
packages/semi-ui/tabs/TabBar.tsx
packages/semi-ui/tabs/_story/tabs.stories.jsx

Fixes #2781 
🇨🇳 Chinese
- Fix: 修复 Collaspe Tabs 初次加载无法将 actvieTab 滚动到视口内问题
---
🇺🇸 English
- Fix: fix the issue that Collaspe Tabs cannot scroll actvieTab into the viewport when first loaded

fix: tabs add scrollActiveTabItemIntoView to componentDidMount

---

packages/semi-foundation/backtop/foundation.ts

Fixes #
用户反馈在上报中有发现 Backtop 的 TypeError，实际上是用户的 target 函数返回值有问题。我们这边做下兜底，避免 TypeError导致页面问题
🇨🇳 Chinese
- Fix:  BackTop 组件的 target 不存在时候的兜底操作，避免 TypeError
---
🇺🇸 English
- Fix: A fallback operation to avoid TypeError when target does not exist in BackTop component

Fix: Fallback operation when targetNode does not exist

---

packages/semi-foundation/chat/chat.scss
packages/semi-foundation/chat/variables.scss
packages/semi-ui/chat/_story/chat.stories.jsx
packages/semi-ui/chat/_story/constant.js

…etched by the table
Fixes #2776 
🇨🇳 Chinese
- Style: 修复 Chat 内容区域的宽度被内容中的 table 撑开, 滚动区域为整条内容的问题，修改后滚动区域在 table 内部 #2776 
- Style: Chat 增加 $width-chat_chatBox_avatar 用于设置头像宽度 
---
🇺🇸 English
- Style: Fixed the problem that the width of the Chat content area was stretched by the table in the content, and the scrolling area was the entire content. After modification, the scrolling area is inside the table #2776 
- Style: Chat adds $width-chat_chatBox_avatar to set avatar width

style: Fix the problem that the width of the chat content area is stretched by the table

---

packages/semi-foundation/scrollList/scrollList.scss

Fixes #
<strong>问题</strong>
用户反馈在主题配置的时候，有以下问题：
当 timePicker 下拉面板中的 x 方向的 padding 为 0 时候，被选中的/hover 的块在边缘会有颜色透出
<strong>原因</strong>
TimePicker 的下拉面板中的内容使用的是 scrollList， scrollList 的的最外层有设置 border-radius，但是无 overflow 相关的设置，因此添加 overflow: hidden 放置内容透出。
<strong>影响面考虑</strong>
对于 scrollList 来说，结构是 header，body， footer，从使用上来说，是希望三者不需要通过滚动条来调节是否显示，滚动区域应该只出现在 body 部分。因此认为增加 overflow：hidden 是合理的
🇨🇳 Chinese
- Style: ScrollList 最外层增加 overflow: hidden 的样式设置
---
🇺🇸 English
- Fix: Add overflow: hidden style setting to the outermost layer of ScrollList

style: [ScrollList] add overflow hidden for the outer layer

---

packages/semi-ui/form/interface.ts

Fixes #
🇨🇳 Chinese
- Fix: 更新 BaseFormProps 的 render 和 children 属性类型，支持泛型 Values
---
🇺🇸 English
- Fix: Update the type of render and children properties of BaseFormProps to support generic Values

fix: 更新 BaseFormProps 的 render 和 children 属性类型，支持泛型 Values

---

packages/semi-ui/select/_story/select.stories.jsx
packages/semi-ui/select/index.tsx
packages/semi-ui/select/utils.tsx

Fixes #2853 
🇨🇳 Chinese
- Fix: 修复 Select 在分组 label 为 ReactNode 的情况下，filter 后 optionList 展示有误问题
---
🇺🇸 English
- Fix: fix the problem that when the Select group label is ReactNode, the optionList display is incorrect after filtering

fix: add child key to restGroupProps to make group key unique

---

packages/semi-foundation/datePicker/yearAndMonthFoundation.ts
packages/semi-ui/locale/_story/locale.stories.jsx

Fixes #2870 
预期是比较 8 和 7 这两个月份的数字位去判断要不要自动滚动，但是在英文情况下 item.value 值为 August ，和数字比较导致判断错误。将 item.value 改成 item.month 即可
🇨🇳 Chinese
- Fix: 修复 DatePicker 在 monthRange 且多语言情况下，点击月份无法自动滚动到非禁用项问题 #2870 
---
🇺🇸 English
- Fix: fix the issue that DatePicker cannot automatically scroll to non-disabled items when clicking on the month in monthRange and multi-language #2870

fix: convert item.value to item.month to ensure that the datepicker can compare the correct numbers instead of letters in monthRange

---

packages/semi-foundation/button/animation.scss
packages/semi-foundation/button/iconButton.scss
packages/semi-ui/_utils/semi-global.ts
packages/semi-ui/iconButton/index.tsx
packages/semi-ui/spin/icon.tsx
packages/semi-ui/spin/index.tsx

Fixes #2695
🇨🇳 Chinese
- Feat: 支持配置全局的 Spin 的指示器，新增 $animation_duration-button_icon_loading，$animation_duration-button_icon_customIcon_loading 设计 token 用于配置 button 中不同类型的 loading 的动画时长  #2695 
---
🇺🇸 English
- Feat: Supports configuring global Spin indicators, Added $animation_duration-button_icon_loading, $animation_duration-button_icon_customIcon_loading design token used to configure the animation duration of different types of loading in the button #2695

feat: custom global indicator for loading

---

packages/semi-foundation/tag/tag.scss
packages/semi-ui/tag/_story/tag.stories.jsx

修复前：
修复后：
增加 storybook 用例， cypress 监测
Fixes #
🇨🇳 Chinese
- Style: 修复 type 为 solid，color 为 white 的 Tag 的关闭图标颜色错误问题
---
🇺🇸 English
- Style: Fixed the issue that the close icon of a tag with type solid and color white has incorrect color

style: Fixed the closeIcon color error of solid and white tags

---

packages/semi-foundation/utils/number.ts
packages/semi-ui/inputNumber/__test__/inputNumber.test.js
packages/semi-ui/inputNumber/_story/inputNumber.stories.jsx

Fixes #2936
add 逻辑中需要通过 `Math.abs(numberMinus(max, curNum)) >= stepAbs` 计算 `curNum`
max = 0.08，step = 0.01，curNum = 0.07 时，numberMinus 通过 utils/number 下的 plus 计算 `numberMinus(max, curNum)`
计算结果如下
num1 * baseNum + num2 * baseNum 必定为整数，故加上一个四舍五入的计算即可得到正解
🇨🇳 Chinese
- Fix: 修复 InputNumber 因为 js 精度计算有误问题
---
🇺🇸 English
- Fix: fix the problem that InputNumber calculation is incorrect due to js precision

fix: inputnumber plus calculate wrong cause by js precision

---

packages/semi-rspack/src/rule.ts
packages/semi-webpack/src/semi-webpack-plugin.ts

针对 /@douyinfe(\/|\\)+semi-(ui|icons|foundation)(\/|\\)+lib(\/|\\)+.+\.scss$/ 下的文件进行 sass-loader 配置，静默 sass 弃用警告
🇨🇳 Chinese
- Feat: semi webpack 和 rspack 插件在 sass-loader 中添加内置 silenceDeprecations 选项（'import', 'legacy-js-api', 'global-builtin'）静默 sass 相关的弃用警告
---
🇺🇸 English
- Feat: webpack and rspack plugins in semi add built-in silenceDeprecations options ('import', 'legacy-js-api', 'global-builtin') to sass-loader to silence sass-related deprecation warnings

feat: webpack and rspack plugin add built-in silenceDeprecations in sass-loader

---

packages/semi-foundation/tagInput/tagInput.scss
packages/semi-foundation/tagInput/variables.scss

Fixes #
🇨🇳 Chinese
- Style: 增加禁用态的 TagInput 的背景色 token，$color-tagInput_disabled-bg
---
🇺🇸 English
- Style: Add a background color token for disabled TagInput, $color-tagInput_disabled-bg

style: add $color-tagInput_disabled-bg for disabled Taginput background
